import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'
import { documentHarness, documentUpload } from '../fixtures/document-control.fixture'

test.setTimeout(60000)
const region = (page, name) => page.getByRole('region', { name, exact: true })
const register = page => region(page, 'Document register')
const details = page => region(page, 'Document details')
const indicators = page => page.locator('.dc-kpis')
const downloadFile = page => details(page).locator('.dc-document-file').getByRole('button', { name: /^Download / })
const search = page => page.getByRole('searchbox', { name: 'Search document title or file', exact: true })
const select = (page, name) => page.getByRole('combobox', { name, exact: true })
const addMenu = page => page.locator('summary[aria-label="Add document"]')

async function loaded(page) {
  await expect(page.getByRole('heading', { name: 'Project Documents', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Management', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.pp-header-actions').getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled()
}
async function noOverflow(page) {
  const result = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }))
  expect(result.document, JSON.stringify(result)).toBeLessThanOrEqual(result.viewport + 1)
}
async function accessible(page, selector = '.project-performance-workspace') {
  const scan = await new AxeBuilder({ page }).include(selector).analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
}
async function selectMatching(locator, pattern) {
  const option = locator.getByRole('option').filter({ hasText: pattern }).first()
  await locator.selectOption(await option.evaluate(element => element.value))
}
async function pickDocument(page, title) {
  await search(page).fill(title)
  await register(page).getByRole('button', { name: `Select document ${title}`, exact: true }).click()
  await expect(details(page)).toContainText(title)
  await expect(details(page).getByRole('button', { name: 'Edit metadata', exact: true })).toBeVisible()
}
async function uploadDialog(page) {
  await addMenu(page).click()
  await page.getByRole('button', { name: 'New document', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'New document', exact: true })
  await expect(dialog).toBeVisible()
  return dialog
}
async function captureDownload(page, trigger) {
  const pending = page.waitForEvent('download')
  await trigger()
  const download = await pending
  return { filename: download.suggestedFilename(), body: await readFile(await download.path()) }
}

test('desktop documents show every API page, recorded metadata and honest workflow indicators', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await documentHarness(page)
  await loaded(page)
  await expect(indicators(page).locator('button')).toHaveCount(6)
  await expect(indicators(page)).toContainText('12')
  await expect(indicators(page)).toContainText('Review dates not tracked')
  for (const name of ['Deliverable progress', 'Document register', 'Review & comment workload', 'Document actions', 'Document details', 'Transmittals', 'Document data quality']) await expect(region(page, name)).toBeVisible()
  await expect(register(page)).toContainText('Process P&ID package')
  await expect(details(page)).toContainText('Metadata processed')
  expect(state.requests.filter(item => item.path.endsWith('/documents/')).map(item => item.query.page || '1')).toEqual(['1', '2', '3'])
  expect(state.writes).toEqual([])
  expect(state.unknown).toEqual([])
  await noOverflow(page)
  await page.screenshot({ path: '../artifacts/document-control-desktop.png', animations: 'disabled' })
  await accessible(page)
})

test('search and type processing uploader and date filters operate on all fetched records', async ({ page }) => {
  await documentHarness(page)
  await loaded(page)
  await search(page).fill('Commissioning')
  await expect(register(page)).toContainText('Commissioning procedure')
  await expect(register(page)).not.toContainText('Process P&ID package')
  await search(page).fill('')
  await selectMatching(select(page, 'Document type'), /^Drawing$/)
  await expect(register(page)).toContainText('Process P&ID package')
  await expect(register(page)).toContainText('Instrument data sheet')
  await expect(register(page)).not.toContainText('September progress report')
  await selectMatching(select(page, 'Document type'), /^All/)
  await selectMatching(select(page, 'Processing'), /failed/i)
  await expect(register(page)).toContainText('Pump equipment specification')
  await expect(register(page)).not.toContainText('Process P&ID package')
  await selectMatching(select(page, 'Processing'), /^All/)
  await selectMatching(select(page, 'Uploaded by'), /^Maya/)
  await expect(register(page)).not.toContainText('September progress report')
  await selectMatching(select(page, 'Uploaded by'), /^All/)
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Uploaded from', { exact: true }).fill('2026-08-01')
  await page.getByLabel('Uploaded to', { exact: true }).fill('2026-08-31')
  await expect(register(page)).toContainText('Site survey photo')
  await expect(register(page)).toContainText('Commissioning procedure')
  await expect(register(page)).not.toContainText('Legacy handover record')
  await page.getByRole('checkbox', { name: 'Only my uploads', exact: true }).check()
  await expect(register(page)).toContainText('Site survey photo')
  await expect(register(page)).not.toContainText('Commissioning procedure')
})

test('selection fetches only document detail and exposes processing failure and missing-file actions', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  const listRequests = state.requests.filter(item => item.path.endsWith('/documents/')).length
  await pickDocument(page, 'Pump equipment specification')
  await expect(details(page)).toContainText('Metadata processing failed for this uploaded file.')
  expect(state.requests.some(item => item.path.endsWith('/documents/7104/'))).toBe(true)
  expect(state.requests.filter(item => item.path.endsWith('/documents/')).length).toBe(listRequests)
  await pickDocument(page, 'Legacy handover record')
  await expect(details(page).getByRole('button', { name: 'Download file', exact: true })).toBeDisabled()
  await expect(downloadFile(page)).toBeDisabled()
  expect(state.writes).toEqual([])
})

test('register grouping sorting and upload history show recorded counts without planned or approved data', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  const progress = region(page, 'Deliverable progress')
  await progress.getByRole('button', { name: 'Table', exact: true }).click()
  await expect(progress.locator('.dc-upload-history tbody tr')).toHaveCount(12)
  await expect(progress.locator('.dc-upload-history tbody tr').last()).toContainText('12')
  await page.getByRole('button', { name: 'Document register', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Document register', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(register(page).locator('tbody tr')).toHaveCount(12)
  await select(page, 'Group by').selectOption('kind')
  await expect(register(page).locator('.dc-group-row')).toHaveCount(7)
  await expect(register(page).locator('.dc-group-row').filter({ hasText: 'Drawing' })).toContainText('2 documents')
  await select(page, 'Group by').selectOption('uploader')
  await expect(register(page).locator('.dc-group-row')).toHaveCount(3)
  await select(page, 'Group by').selectOption('none')
  await select(page, 'Sort documents').selectOption('oldest')
  await expect(register(page).locator('tbody tr').first()).toContainText('Legacy handover record')
  expect(state.writes).toEqual([])
})

test('revision review transmittal and deliverable dialogs disclose unavailable workflows without mutations', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  const cases = [
    [() => details(page).getByRole('button', { name: 'Revision history', exact: true }).click(), 'Revision history', /Revision numbers and superseded files are not tracked/i],
    [() => region(page, 'Review & comment workload').getByRole('button', { name: 'View requirements', exact: true }).click(), 'Document reviews', /approval decisions are not recorded/i],
    [() => region(page, 'Transmittals').getByRole('button', { name: 'View requirements', exact: true }).click(), 'Transmittals', /Transmittal numbers, recipients and issue dates are not recorded/i],
    [() => region(page, 'Deliverable progress').getByRole('button', { name: 'Open deliverable plan', exact: true }).click(), 'Deliverable plan', /Planned deliverables and baseline issue dates are not recorded/i],
    [() => page.getByRole('button', { name: 'Review document quality', exact: true }).click(), 'Document quality', /not.*approval|approval.*not/i],
    [() => region(page, 'Document actions').getByRole('button', { name: 'View all', exact: true }).click(), 'Document actions', /not assigned review tasks/i],
  ]
  for (const [open, title, text] of cases) {
    await open()
    const dialog = page.getByRole('dialog', { name: title, exact: true })
    await expect(dialog).toContainText(text)
    await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  }
  await addMenu(page).click()
  const menu = addMenu(page).locator('..')
  await expect(menu.getByRole('button', { name: 'Upload revision', exact: true })).toBeDisabled()
  await expect(menu.getByRole('button', { name: 'Create transmittal', exact: true })).toBeDisabled()
  expect(state.writes).toEqual([])
})

test('upload title and type editing authenticated download and confirmed deletion persist actual records', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  let dialog = await uploadDialog(page)
  await dialog.getByLabel('Document file', { exact: true }).setInputFiles(documentUpload())
  await dialog.getByRole('textbox', { name: 'Document title', exact: true }).fill('Vendor clarification note')
  await select(dialog, 'Document type').selectOption('minutes')
  await dialog.getByRole('button', { name: 'Upload document', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  const created = state.records[17].documents.find(item => item.title === 'Vendor clarification note')
  expect(created).toMatchObject({ project: 17, kind: 'minutes', parse_status: 'queued', original_filename: 'Vendor-review-note.txt' })
  await expect(details(page)).toContainText('Vendor clarification note')
  await details(page).getByRole('button', { name: 'Edit metadata', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Edit document', exact: true })
  await dialog.getByRole('textbox', { name: 'Document title', exact: true }).fill('Approved meeting title')
  await select(dialog, 'Document type').selectOption('other')
  await dialog.getByRole('button', { name: 'Save document', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes.at(-1)).toMatchObject({ method: 'PATCH', body: { title: 'Approved meeting title', kind: 'other' } })
  expect(Object.keys(state.writes.at(-1).body).sort()).toEqual(['kind', 'title'])
  const download = await captureDownload(page, () => downloadFile(page).click())
  expect(download.filename).toBe('Vendor-review-note.txt')
  expect(download.body.toString()).toContain('Recorded equipment clarification')
  expect(state.requests.some(item => item.path.endsWith(`/documents/${created.id}/download/`))).toBe(true)
  await details(page).getByRole('button', { name: 'Delete', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Delete document', exact: true })
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(state.records[17].documents.some(item => item.id === created.id)).toBe(true)
  await details(page).getByRole('button', { name: 'Delete', exact: true }).click()
  await dialog.getByRole('button', { name: 'Confirm deletion', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.records[17].documents.some(item => item.id === created.id)).toBe(false)
  expect(state.writes.at(-1).method).toBe('DELETE')
})

test('upload validation and server failures retain the form and avoid unsuccessful local changes', async ({ page }) => {
  const state = await documentHarness(page, { prepare: current => { current.maxDocumentBytes = 10 } })
  await loaded(page)
  let dialog = await uploadDialog(page)
  await dialog.getByLabel('Document file', { exact: true }).setInputFiles(documentUpload())
  await dialog.getByRole('button', { name: 'Upload document', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('upload limit')
  expect(state.writes).toEqual([])
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  state.maxDocumentBytes = 104857600
  await page.locator('.pp-header-actions').getByRole('button', { name: 'Refresh', exact: true }).click()
  await loaded(page)
  dialog = await uploadDialog(page)
  await dialog.getByLabel('Document file', { exact: true }).setInputFiles(documentUpload())
  state.saveFailure = true
  await dialog.getByRole('button', { name: 'Upload document', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('could not be saved')
  expect(state.records[17].documents).toHaveLength(12)
  state.saveFailure = false
  await dialog.getByRole('button', { name: 'Upload document', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.records[17].documents[0].title).toBe('Vendor-review-note.txt')
})

test('read-only access retains browsing and protected downloads while preventing uploads edits and deletion', async ({ page }) => {
  const state = await documentHarness(page, { prepare: current => { current.canWrite = false } })
  await loaded(page)
  await expect(addMenu(page)).toHaveAttribute('aria-disabled', 'true')
  await expect(details(page).getByRole('button', { name: 'Edit metadata', exact: true })).toBeDisabled()
  await expect(details(page).getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
  const result = await captureDownload(page, () => downloadFile(page).click())
  expect(result.filename).toBe('5900913-PID-001.pdf')
  expect(result.body.toString().startsWith('%PDF')).toBe(true)
  expect(state.writes).toEqual([])
})

test('safe previews load authenticated text PDF and image bytes and unsupported files remain downloadable', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  await pickDocument(page, 'Commissioning procedure')
  await details(page).getByRole('button', { name: 'Open document', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Document preview', exact: true })
  await expect(dialog.locator('pre')).toContainText('Recorded document content for project 5900913')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(details(page).getByRole('button', { name: 'Open document', exact: true })).toBeFocused()
  await pickDocument(page, 'Process P&ID package')
  await details(page).getByRole('button', { name: 'Open document', exact: true }).click()
  await expect(dialog.locator('iframe')).toHaveAttribute('src', /^blob:/)
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await pickDocument(page, 'Site survey photo')
  await details(page).getByRole('button', { name: 'Open document', exact: true }).click()
  await expect(dialog.getByRole('img', { name: 'Site survey photo' })).toBeVisible()
  await expect.poll(() => dialog.locator('img').evaluate(element => element.naturalWidth)).toBeGreaterThan(0)
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await pickDocument(page, 'Tender quantity schedule')
  await expect(details(page).getByRole('button', { name: 'Open document', exact: true })).toHaveCount(0)
  const download = await captureDownload(page, () => details(page).getByRole('button', { name: 'Download file', exact: true }).click())
  expect(download.filename).toBe('Tender-BOQ.xlsx')
  expect(state.writes).toEqual([])
})

test('failed protected downloads show an error and preview retry uses the same document', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  await pickDocument(page, 'Commissioning procedure')
  state.failures.add('/documents/7111/download/')
  await details(page).getByRole('button', { name: 'Open document', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Document preview', exact: true })
  await expect(dialog.getByRole('alert')).toContainText('temporarily unavailable')
  await expect(dialog.getByRole('button', { name: 'Download file', exact: true })).toBeDisabled()
  state.failures.clear()
  await dialog.getByRole('button', { name: 'Retry preview', exact: true }).click()
  await expect(dialog.locator('pre')).toContainText('Commissioning procedure')
  expect(state.writes).toEqual([])
})

test('CSV exports the full project register despite active search and preserves unknown workflow fields', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  await search(page).fill('Pump')
  const result = await captureDownload(page, () => page.getByRole('button', { name: 'Export register', exact: true }).click())
  expect(result.filename).toMatch(/\.csv$/i)
  for (const text of ['Process P&ID package', 'Commissioning procedure', 'Legacy handover record', '5900913', 'Processing failed']) expect(result.body.toString()).toContain(text)
  expect(state.writes).toEqual([])
})

test('Refresh and project switching reload the correct register and selected document', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  state.records[17].documents[0].title = 'Refreshed P&ID title'
  await page.locator('.pp-header-actions').getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(details(page)).toContainText('Refreshed P&ID title')
  const picker = select(page, 'Active Project')
  await picker.fill('5900738'); await picker.press('Enter')
  await expect(page).toHaveURL(/project=18/)
  await expect(page).toHaveURL(/view=documents/)
  await expect(details(page)).toContainText('Process P&ID package')
  await expect(register(page)).not.toContainText('Refreshed P&ID title')
  expect(state.requests.some(item => item.project === 18 && item.path.endsWith('/documents/8101/'))).toBe(true)
  expect(state.unknown).toEqual([])
})

test('empty and failed registers remain distinct and a failed detail preserves the complete list', async ({ page }) => {
  const state = await documentHarness(page, { prepare: current => { current.records[17].documents = [] } })
  await loaded(page)
  await expect(register(page)).toContainText(/No.*documents/i)
  state.failures.add('/documents/')
  await page.locator('.pp-header-actions').getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert').first()).toContainText(/register.*unavailable/i)
  await expect(page.getByRole('button', { name: 'Export register', exact: true })).toBeDisabled()
  state.failures.clear()
  state.records[17].documents = state.records[18].documents.map(item => ({ ...item, id: item.id - 1000, project: 17 }))
  state.failures.add('/documents/7101/')
  await page.locator('.pp-header-actions').getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert').first()).toContainText(/details.*unavailable/i)
  await expect(register(page)).toContainText('Process P&ID package')
  await expect(indicators(page)).toContainText('12')
  await expect(details(page)).toContainText(/unavailable/i)
  expect(state.writes).toEqual([])
})

test('server files retain project folder browsing extraction evidence and review', async ({ page }) => {
  const state = await documentHarness(page)
  await loaded(page)
  await page.getByRole('button', { name: 'Server files', exact: true }).click()
  await page.getByRole('button', { name: 'Reports', exact: true }).click()
  await page.getByRole('button', { name: 'Server progress.txt', exact: true }).click()
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(page.locator('pre')).toContainText('Progress: 25%')
  await page.getByRole('button', { name: 'Extract information', exact: true }).click()
  await expect(page.getByText('Source: Line 1')).toBeVisible()
  await page.getByLabel('Review notes').fill('Checked against the connected source.')
  await page.getByRole('button', { name: 'Accept evidence', exact: true }).click()
  await expect(page.getByText('accepted', { exact: true })).toBeVisible()
  expect(state.writes.at(-1)).toMatchObject({ project: 17, body: { status: 'accepted', notes: 'Checked against the connected source.' } })
  expect(state.requests.filter(item => item.path.endsWith('/entries/')).every(item => item.query.project === '17' && item.query.scope === 'scope-17')).toBe(true)
  await page.getByRole('button', { name: 'Document register', exact: true }).click()
  await expect(register(page)).toContainText('Process P&ID package')
})

test('mobile documents and dialogs remain accessible within the viewport with focus restored', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await documentHarness(page)
  await loaded(page)
  await noOverflow(page)
  await page.screenshot({ path: '../artifacts/document-control-mobile.png', animations: 'disabled' })
  await page.screenshot({ path: '../artifacts/document-control-mobile-full.png', animations: 'disabled', fullPage: true })
  await accessible(page)
  const dialog = await uploadDialog(page)
  await expect.poll(() => dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await dialog.press('Tab')
  await expect.poll(() => dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await accessible(page, 'dialog[open]')
  const bounds = await dialog.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(391)
  await dialog.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(addMenu(page)).toBeFocused()
})
