import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { epcHarness } from '../fixtures/epc-lifecycle-data'

test.setTimeout(60000)
const panel = (page, name) => page.getByRole('region', { name, exact: true })
const stage = (page, number) => page.getByRole('navigation', { name: 'EPC lifecycle stages' }).getByRole('button', { name: new RegExp(`^${number}\\.`) }).click()
const loaded = async page => { await expect(page.getByRole('heading', { name: 'EPC lifecycle', exact: true })).toBeVisible(); await expect(page.getByRole('button', { name: 'Save EPC setup' })).toBeEnabled() }
const writes = state => state.requests.filter(row => row.method !== 'GET')
const refresh = async page => { await page.getByRole('button', { name: 'Refresh lifecycle' }).click(); await expect(page.getByText('Loading EPC lifecycle records…', { exact: true })).not.toBeVisible() }
const accessibility = async page => {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  const result = await new AxeBuilder({ page }).analyze()
  expect(result.violations.filter(row => ['serious', 'critical'].includes(row.impact))).toEqual([])
}
async function createDraft(page) {
  await page.getByRole('button', { name: 'New work item', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'New EPC work item' })
  await dialog.getByRole('textbox', { name: 'Work item code', exact: true }).fill('PROC-PKG-02')
  await dialog.getByRole('textbox', { name: 'Work item title', exact: true }).fill('Procurement release evidence')
  await dialog.getByRole('combobox', { name: 'Execution phase', exact: true }).selectOption('procurement')
  await dialog.getByRole('combobox', { name: 'Work package WBS', exact: true }).selectOption('171')
  await dialog.getByRole('combobox', { name: 'Work owner', exact: true }).selectOption('7')
  await dialog.getByRole('combobox', { name: 'Evidence reviewer', exact: true }).selectOption('8')
  await dialog.getByRole('combobox', { name: 'Progress activity', exact: true }).selectOption('1709')
  await dialog.getByRole('combobox', { name: 'Integrated EPC baseline', exact: true }).selectOption('1702')
  await dialog.getByLabel('Work data date', { exact: true }).fill('2026-09-15')
  await dialog.getByRole('textbox', { name: 'Acceptance criteria', exact: true }).fill('Supplier package is complete.\nPurchase order acceptance is recorded.')
  await dialog.getByRole('checkbox', { name: 'Engineering review evidence' }).check()
  await dialog.getByRole('textbox', { name: 'Evidence notes' }).fill('Verified source package.')
  return dialog
}

test('desktop EPC setup, real phase WBS, navigation and accessibility', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await epcHarness(page, { shell: true }); await loaded(page)
  await expect(panel(page, 'EPC work breakdown structure').getByRole('row')).toHaveCount(5)
  await expect(page.getByRole('navigation', { name: 'Project work areas' }).getByRole('button', { name: 'EPC lifecycle' })).toHaveAttribute('aria-current', 'page')
  await accessibility(page)
  await page.screenshot({ path: 'artifacts/epc-lifecycle-setup-desktop.png' })
  await stage(page, 3)
  await expect(panel(page, 'Work item detail')).toContainText('Engineering package release')
  await expect(panel(page, 'EPC execution work items')).toContainText('Not earned')
  await accessibility(page)
  await page.screenshot({ path: 'artifacts/epc-lifecycle-execution-desktop.png' })
  expect(writes(state)).toEqual([]); expect(state.unknown).toEqual([])
})

test('setup writes validated project fields and refreshes four phase roots', async ({ page }) => {
  const state = await epcHarness(page, { prepare: state => { state.records[17].ready = false } }); await loaded(page)
  await expect(panel(page, 'Phase WBS')).toContainText('Save the validated setup')
  await page.getByRole('textbox', { name: 'Client', exact: true }).fill('Confirmed synthetic client')
  await page.getByRole('combobox', { name: 'Project currency' }).selectOption('USD')
  await page.getByRole('button', { name: 'Save EPC setup' }).click()
  await expect(panel(page, 'EPC work breakdown structure').getByRole('row')).toHaveCount(5)
  expect(writes(state)[0].body).toMatchObject({ client_name: 'Confirmed synthetic client', owner: '7', scope_type: 'epc', currency: 'USD', start_date: '2026-09-01', end_date: '2027-03-31' })
  await expect(page.getByRole('textbox', { name: 'Client', exact: true })).toHaveValue('Confirmed synthetic client')
})

test('WBS activity links create edit and explicitly remove', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 2)
  await page.getByRole('button', { name: 'Link activity', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Link schedule activity' })
  await dialog.getByRole('combobox', { name: 'Project WBS', exact: true }).selectOption('171')
  await dialog.getByRole('combobox', { name: 'EPC phase' }).selectOption('procurement')
  await dialog.getByRole('combobox', { name: 'Schedule activity' }).selectOption('1709')
  await dialog.getByRole('button', { name: 'Save activity link' }).click()
  await expect(dialog).not.toBeVisible()
  let row = panel(page, 'WBS schedule links').getByRole('row').filter({ hasText: 'PROC-200' })
  await row.getByRole('button', { name: 'Edit', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Edit activity link' })
  await dialog.getByRole('textbox', { name: 'Link notes' }).fill('Approved procurement activity source.')
  await dialog.getByRole('button', { name: 'Save activity link' }).click(); await expect(dialog).not.toBeVisible()
  row = panel(page, 'WBS schedule links').getByRole('row').filter({ hasText: 'PROC-200' })
  await row.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Remove activity link' })).toBeVisible()
  expect(writes(state).filter(row => row.method === 'DELETE')).toHaveLength(0)
  await page.getByRole('button', { name: 'Confirm removal' }).click()
  await expect(row).toHaveCount(0)
  expect(writes(state).at(-1)).toMatchObject({ method: 'DELETE', body: { id: 999 } })
})

test('ambiguous requisition association requires explicit authority review', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 2)
  await page.getByRole('button', { name: 'Associate', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Associate purchase requisition' })
  await dialog.getByRole('combobox', { name: 'Procurement WBS' }).selectOption('171')
  await dialog.getByRole('textbox', { name: 'Association reason' }).fill('Confirmed against the approved project requisition source.')
  await dialog.getByRole('button', { name: 'Save requisition association' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Review the ambiguous reference')
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Save requisition association' }).click()
  await expect(dialog).not.toBeVisible()
  expect(writes(state).at(-1).body).toMatchObject({ requisition: '00000000-0000-4000-8000-000000000017', wbs_node: 171, review_confirmed: true })
})

test('baseline capture selects approved sources and preserves manifest', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 2)
  await page.getByRole('button', { name: 'Capture EPC baseline', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Capture EPC baseline' })
  await expect(dialog.getByRole('button', { name: 'Capture baseline', exact: true })).toBeDisabled()
  await dialog.getByRole('textbox', { name: 'Baseline name', exact: true }).fill('Approved revision two')
  await dialog.getByLabel('Baseline data date').fill('2026-09-15')
  await dialog.getByRole('combobox', { name: 'Approved schedule baseline' }).selectOption('170')
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button', { name: 'Capture baseline', exact: true }).click(); await expect(dialog).not.toBeVisible()
  expect(writes(state).at(-1).body).toEqual({ name: 'Approved revision two', data_date: '2026-09-15', schedule_baseline: 170, budget_ids: [170] })
  await panel(page, 'Captured EPC baseline records').getByRole('row').filter({ hasText: 'Approved revision two' }).getByRole('button', { name: 'View source' }).click()
  await expect(page.getByRole('dialog', { name: 'EPC baseline source' })).toContainText('schedule_baseline_id')
})

test('draft creation preserves evidence criteria and editing retains existing activity and milestone', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 3)
  await expect(page.getByRole('button', { name: 'Edit draft' })).toBeEnabled()
  await page.getByRole('button', { name: 'Edit draft' }).click()
  const edit = page.getByRole('dialog', { name: 'Edit work item', exact: true })
  await expect(edit.getByRole('combobox', { name: 'Progress activity' })).toHaveValue('1700')
  await expect(edit.getByRole('combobox', { name: 'Linked milestone' })).toHaveValue('175')
  await edit.getByRole('textbox', { name: 'Evidence notes' }).fill('Updated design evidence note.')
  await edit.getByRole('button', { name: 'Save draft' }).click(); await expect(edit).not.toBeVisible()
  expect(writes(state).at(-1).body).toMatchObject({ activity: '1700', milestone: '175', evidence_note: 'Updated design evidence note.' })
  const dialog = await createDraft(page)
  await dialog.getByRole('button', { name: 'Save draft' }).click(); await expect(dialog).not.toBeVisible()
  await expect(panel(page, 'EPC execution work items').getByRole('row').filter({ hasText: 'PROC-PKG-02' })).toContainText('Not earned')
  expect(writes(state).at(-1).body).toMatchObject({ phase: 'procurement', documents: [1701], acceptance_criteria: ['Supplier package is complete.', 'Purchase order acceptance is recorded.'], data_date: '2026-09-15' })
  expect(writes(state).some(row => row.path.includes('/accept/'))).toBeFalsy()
})

test('submit then assigned-reviewer approval then authorized acceptance earns progress only once accepted', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 3)
  await expect(page.getByRole('button', { name: 'Submit for review', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Submit for review', exact: true }).click()
  await page.getByRole('dialog', { name: 'Submit work for review' }).getByRole('button', { name: 'Submit for review', exact: true }).click()
  await expect(panel(page, 'Work item detail')).toContainText('Submitted')
  await expect(page.getByRole('button', { name: 'Review evidence', exact: true })).toBeDisabled()
  state.reviewer = true; await refresh(page)
  await expect(page.getByRole('button', { name: 'Review evidence', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Review evidence', exact: true }).click()
  const review = page.getByRole('dialog', { name: 'Review work evidence' })
  await expect(review.getByRole('button', { name: 'Approve evidence review' })).toBeDisabled()
  await review.getByRole('checkbox').check(); await review.getByRole('textbox', { name: 'Review note' }).fill('Verified both criteria against the signed review record.')
  await review.getByRole('button', { name: 'Approve evidence review' }).click(); await expect(review).not.toBeVisible()
  await expect(panel(page, 'EPC execution work items')).toContainText('Not earned')
  state.reviewer = false; await refresh(page)
  await expect(page.getByRole('button', { name: 'Accept work', exact: true })).toBeEnabled()
  const projectReadsBeforeAcceptance = state.requests.filter(row => row.path.endsWith('/projects/17/') && row.method === 'GET').length
  await page.getByRole('button', { name: 'Accept work', exact: true }).click()
  const accept = page.getByRole('dialog', { name: 'Accept completed work' })
  await accept.getByRole('textbox', { name: 'Acceptance note' }).fill('Accepted the reviewed engineering package.')
  await accept.getByRole('button', { name: 'Accept work and post progress' }).click(); await expect(accept).not.toBeVisible()
  await expect(panel(page, 'EPC execution work items')).toContainText('100% posted')
  await expect(page.getByRole('button', { name: 'Edit draft' })).toBeDisabled()
  expect(writes(state).find(row => row.path.includes('/review/')).body).toMatchObject({ decision: 'approve', criteria_confirmed: true })
  expect(writes(state).filter(row => row.path.includes('/accept/'))).toHaveLength(1)
  expect(state.requests.filter(row => row.path.endsWith('/projects/17/') && row.method === 'GET').length).toBeGreaterThan(projectReadsBeforeAcceptance)
})

test('reviewer return reopens draft; changed evidence rejection does not display earned progress', async ({ page }) => {
  const state = await epcHarness(page, { prepare: state => { state.reviewer = true; state.records[17].items[0].status = 'submitted' } }); await loaded(page); await stage(page, 3)
  await page.getByRole('button', { name: 'Review evidence', exact: true }).click()
  const review = page.getByRole('dialog', { name: 'Review work evidence' })
  await review.getByRole('combobox', { name: 'Review decision' }).selectOption('return')
  await review.getByRole('textbox', { name: 'Review note' }).fill('Attach the missing signature page.')
  await review.getByRole('button', { name: 'Return to draft' }).click(); await expect(review).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Edit draft' })).toBeEnabled()
  state.reviewer = false; state.records[17].items[0].status = 'reviewed'; state.rejectAccept = true; await refresh(page)
  await page.getByRole('button', { name: 'Accept work', exact: true }).click()
  const accept = page.getByRole('dialog', { name: 'Accept completed work' })
  await accept.getByRole('textbox', { name: 'Acceptance note' }).fill('Attempt acceptance after source changed.')
  await accept.getByRole('button', { name: 'Accept work and post progress' }).click()
  await expect(accept.getByRole('alert')).toContainText('Evidence changed after review')
  expect(state.records[17].items[0].status).toBe('reviewed')
  await accept.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(panel(page, 'EPC execution work items')).not.toContainText('100% posted')
})

test('server permissions blockers and partial-source failures stay explicit', async ({ page }) => {
  const state = await epcHarness(page, { prepare: state => { state.readOnly = true; state.records[17].items[0].blocked = true; state.failSource = 'baseline' } })
  await expect(page.getByRole('button', { name: 'Save EPC setup' })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('baseline service unavailable')
  await stage(page, 3)
  await expect(page.getByRole('button', { name: 'New work item', exact: true })).toBeDisabled()
  await expect(panel(page, 'Work item detail')).toContainText('Link approved project evidence before submission')
  await expect(page.getByRole('button', { name: 'Submit for review', exact: true })).toBeDisabled()
  await stage(page, 2); await expect(page.getByRole('button', { name: 'Capture EPC baseline', exact: true })).toBeDisabled()
  expect(writes(state)).toEqual([])
})

test('project switching clears selected execution and document evidence opens its actual record', async ({ page }) => {
  const state = await epcHarness(page); await loaded(page); await stage(page, 3)
  await expect(panel(page, 'Work item detail')).toContainText('Engineering review evidence')
  await page.getByRole('combobox', { name: 'Active Project' }).click()
  await page.getByRole('option', { name: /EPC-18/ }).click()
  await expect(page.getByRole('textbox', { name: 'Project code' })).toHaveValue('EPC-18')
  await stage(page, 3)
  await expect(panel(page, 'Work item detail')).toContainText('EPC-ENG')
  await panel(page, 'Work item detail').getByRole('button', { name: 'Engineering review evidence', exact: true }).click()
  await expect(page).toHaveURL(/view=documents/)
  await expect(page).toHaveURL(/project=18/)
  await expect(page.getByRole('heading', { name: 'Project Documents', exact: true })).toBeVisible()
  await expect.poll(() => state.requests.some(row => row.path.endsWith('/documents/1801/'))).toBeTruthy()
  expect(writes(state)).toEqual([])
})

test('mobile layout and draft dialog support accessible keyboard focus without page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await epcHarness(page); await loaded(page); await stage(page, 3)
  await expect(panel(page, 'Work item detail')).toContainText('Engineering review evidence')
  await accessibility(page)
  await page.screenshot({ path: 'artifacts/epc-lifecycle-mobile.png', fullPage: true })
  const opener = page.getByRole('button', { name: 'New work item', exact: true })
  await opener.click(); const dialog = page.getByRole('dialog', { name: 'New EPC work item' })
  await expect(dialog).toBeVisible(); await accessibility(page)
  await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible(); await expect(opener).toBeFocused()
})

test('detailed engineering setup preserves scope and distinguishes controlled work from external dependencies', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await epcHarness(page, { shell: true, prepare: state => {
    state.records[17].project.scope_type = 'detailed_engineering'
    state.records[17].project.status = 'planning'
    state.records[17].project.custom_fields = { control_setup: { operational_status_confirmed: false, progress_confirmed: false } }
  } }); await loaded(page)
  const scope = page.getByRole('combobox', { name: 'Delivery scope', exact: true })
  await expect(scope).toHaveValue('detailed_engineering')
  await expect(page.locator('.pp-title-row')).toContainText('Status to confirm')
  await expect(page.locator('.pp-title-row')).not.toContainText('Planning')
  const wbs = panel(page, 'EPC work breakdown structure')
  await expect(wbs.getByRole('row').filter({ hasText: 'Controlled scope' })).toHaveCount(1)
  await expect(wbs.getByRole('row').filter({ hasText: 'External dependency' })).toHaveCount(3)
  await page.getByRole('textbox', { name: 'Client', exact: true }).fill('Confirmed engineering client')
  await page.getByRole('button', { name: 'Save EPC setup' }).click()
  await expect(page.getByText('Project setup saved with the selected delivery scope.', { exact: true })).toBeVisible()
  expect(writes(state)[0].body.scope_type).toBe('detailed_engineering')
  await expect(scope).toHaveValue('detailed_engineering')
  await expect(wbs.getByRole('row').filter({ hasText: 'External dependency' })).toHaveCount(3)
  await accessibility(page)
  await page.screenshot({ path: 'artifacts/epc-detailed-engineering-setup.png' })
  await page.getByRole('navigation', { name: 'Project work areas' }).getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(panel(page, 'Reporting source')).toContainText('Progress to confirm')
  const progress = panel(page, 'Performance indicators').getByRole('button', { name: /Physical progress/ })
  await expect(progress).toContainText('Not available')
  await expect(progress).not.toContainText('0%')
})

test('detailed engineering permits external links while execution remains engineering only', async ({ page }) => {
  const state = await epcHarness(page, { prepare: state => { state.records[17].project.scope_type = 'detailed_engineering' } }); await loaded(page)
  await stage(page, 2)
  await page.getByRole('button', { name: 'Link activity', exact: true }).click()
  const link = page.getByRole('dialog', { name: 'Link schedule activity' })
  await link.getByRole('combobox', { name: 'Project WBS', exact: true }).selectOption('171')
  await link.getByRole('combobox', { name: 'EPC phase' }).selectOption('procurement')
  await link.getByRole('combobox', { name: 'Schedule activity' }).selectOption('1709')
  await link.getByRole('button', { name: 'Save activity link' }).click()
  await expect(link).not.toBeVisible()
  await expect(panel(page, 'WBS schedule links').getByRole('row').filter({ hasText: 'PROC-200' })).toContainText('External dependency')
  await page.getByRole('button', { name: 'Capture EPC baseline', exact: true }).click()
  const capture = page.getByRole('dialog', { name: 'Capture EPC baseline' })
  await expect(capture).toContainText('External dependencies do not earn project progress or control budget')
  await capture.getByRole('button', { name: 'Cancel', exact: true }).click()
  await stage(page, 3)
  await page.getByRole('button', { name: 'New work item', exact: true }).click()
  const work = page.getByRole('dialog', { name: 'New EPC work item' })
  await expect(work.getByRole('combobox', { name: 'Execution phase' }).locator('option')).toHaveText(['Select phase', 'Engineering'])
  await expect(work.getByRole('combobox', { name: 'Work package WBS' }).locator('option')).toHaveCount(2)
  expect(writes(state).filter(row => row.path.endsWith('/epc-work-items/'))).toHaveLength(0)
})
