import { test, expect } from '@playwright/test'
import { Buffer } from 'node:buffer'
import AxeBuilder from '@axe-core/playwright'
import { masterScheduleHarness, registerNames } from '../fixtures/master-schedule.fixture'
import { scheduleAction, scheduleActionButton, scheduleArea, scheduleMenu, closeScheduleMenu, scheduleVersion } from '../fixtures/schedule-controls.js'

test.setTimeout(60000)
const workspace = page => page.getByRole('region', { name: 'Master schedule workspace', exact: true })
const inputs = page => page.getByRole('dialog', { name: 'Documents & project inputs', exact: true })
const simpleWrites = state => state.writes.filter(item => item.path.includes('/simple-plan/'))
const clean = state => { expect(state.pageErrors).toEqual([]); expect(state.unknownWrites).toEqual([]); expect(state.unknown).toEqual([]) }
async function open(page, options) {
  const state = await masterScheduleHarness(page, options)
  await expect(workspace(page).getByRole('heading', { name: 'Master Schedule', exact: true })).toBeVisible()
  return state
}
async function projectInputs(page) {
  await scheduleAction(page, 'Project inputs')
  await expect(inputs(page)).toBeVisible()
  return inputs(page)
}
async function setDates(dialog) {
  await expect(dialog.getByLabel('Project start date', { exact: true })).toBeEnabled()
  await dialog.getByLabel('Project start date', { exact: true }).fill('2026-09-21')
  await dialog.getByLabel('Project end date', { exact: true }).fill('2026-12-20')
}

test('Schedule opens directly into a single Master Schedule with exact register names and Gantt', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 1050 })
  const state = await open(page)
  await expect(page.getByRole('heading', { name: 'Project Planning', exact: true })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { level: 1, name: state.records[17].project.name, exact: true })).toBeVisible()
  await expect(page.getByRole('group', { name: 'Schedule workspace mode' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Performance', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Planning', exact: true })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Planning stages' })).toHaveCount(0)
  const grid = workspace(page).getByRole('region', { name: 'Schedule activities and Gantt' })
  for (const title of registerNames) await expect(grid.getByRole('button', { name: title, exact: true })).toBeVisible()
  await expect(grid.getByRole('button', { name: /^View P&ID - Amine/ })).toHaveCount(1)
  await expect(grid.locator('.p6-activity-bar')).toHaveCount(2)
  const gridBox = await grid.boundingBox(), barBox = await grid.locator('.p6-activity-bar').first().boundingBox()
  expect(barBox.x).toBeGreaterThan(gridBox.x)
  expect(barBox.x).toBeLessThan(gridBox.x + gridBox.width)
  const names = await grid.locator('.sc-task-name').allTextContents()
  expect(names).toEqual(registerNames)
  await workspace(page).getByRole('textbox', { name: 'Search schedule activities' }).fill('LOAD LIST')
  await expect(grid.locator('.sc-task-name')).toHaveText([registerNames[1]])
  await workspace(page).getByRole('textbox', { name: 'Search schedule activities' }).clear()
  await scheduleArea(page, 'evidence')
  await expect(workspace(page)).toContainText('Approved MDR.csv')
  await expect(workspace(page)).toContainText('Row 12')
  await expect(workspace(page)).toContainText(registerNames[0])
  await scheduleArea(page, 'activities')
  await page.screenshot({ path: '../artifacts/master-schedule-desktop.png', fullPage: true, animations: 'disabled' })
  expect(state.writes).toEqual([])
  clean(state)
})

test('documents upload before project dates and analysis preserves the exact MDR deliverables', async ({ page }) => {
  const state = await open(page, { empty: true, noWorkspace: true, blankDates: true })
  const dialog = await projectInputs(page)
  await dialog.getByRole('textbox', { name: 'Scope summary', exact: true }).fill('Deliver the exact approved register scope.')
  await expect(dialog.getByLabel('Project start date', { exact: true })).toHaveValue('')
  await expect(dialog.getByLabel('Project end date', { exact: true })).toHaveValue('')
  await dialog.getByRole('combobox', { name: 'Document type', exact: true }).selectOption('mdr')
  await dialog.getByLabel('Upload reference documents', { exact: true }).setInputFiles({ name: 'Approved MDR.csv', mimeType: 'text/csv', buffer: Buffer.from(`Document Number,Title\nRAD-210-PID-001,"${registerNames[0]}"\nRAD-210-EL-001,"${registerNames[1]}"`) })
  await expect(dialog.getByText('Approved MDR.csv', { exact: true })).toBeVisible()
  await expect(dialog.getByText('Ready to analyze', { exact: true })).toBeVisible()
  const create = state.writes.find(item => item.method === 'POST' && item.path.endsWith('/planning-intelligence/projects/'))
  expect(create.data).toMatchObject({ enterprise_project: 17, name: state.records[17].project.name })
  expect(create.data).not.toHaveProperty('effective_date')
  expect(create.data).not.toHaveProperty('planned_end_date')
  expect(create.data).not.toHaveProperty('scope_summary')
  expect(state.writes.find(item => item.path.endsWith('/files/')).data).toMatchObject({ project: 71, category: 'mdr', name: 'Approved MDR.csv' })
  await expect(dialog.getByRole('textbox', { name: 'Scope summary', exact: true })).toHaveValue('Deliver the exact approved register scope.')
  await expect(dialog.getByLabel('Project start date', { exact: true })).toHaveValue('')
  await setDates(dialog)
  await dialog.getByRole('button', { name: 'Analyze & update schedule', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(workspace(page).locator('.sc-task-name')).toHaveText(registerNames)
  expect(simpleWrites(state)).toEqual([expect.objectContaining({ method: 'POST', path: '/api/v1/planning-intelligence/projects/71/simple-plan/analyse/', data: { revision: 0, rebuild: false } })])
  clean(state)
})

test('scope-only planning opens without uploads and assigns a saved activity to a real employee', async ({ page }) => {
  const state = await open(page, { empty: true, blankDates: true, manual: true })
  const dialog = await projectInputs(page)
  await dialog.getByRole('textbox', { name: 'Scope summary', exact: true }).fill('Launch the internal software after testing and fixes.')
  await dialog.getByLabel('Phase', { exact: true }).fill('Phase 1 launch')
  await setDates(dialog)
  await dialog.getByRole('button', { name: 'Open schedule', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await scheduleAction(page, 'Add activity')
  const task = page.getByRole('dialog', { name: 'Add task', exact: true })
  await task.getByLabel('Task / deliverable', { exact: true }).fill('Verify employee onboarding workflow')
  await task.getByRole('combobox', { name: 'Assigned to', exact: true }).fill('Omar')
  await task.getByRole('option', { name: /Omar Saleh/ }).click()
  await task.getByLabel('Duration (working days)', { exact: true }).fill('2')
  await task.getByLabel('Planned start', { exact: true }).fill('2026-09-21')
  await task.getByLabel('Planned effort (hours)', { exact: true }).fill('12')
  await task.getByRole('button', { name: 'Add task', exact: true }).click()
  await expect(task).toHaveCount(0)
  await expect(workspace(page).getByRole('button', { name: 'Verify employee onboarding workflow', exact: true })).toBeVisible()
  const write = simpleWrites(state).find(item => item.method === 'PUT')
  expect(write.data).toMatchObject({ revision: 1, tasks: [expect.objectContaining({ title: 'Verify employee onboarding workflow', assignee_id: 8, duration_days: 2, planned_start_date: '2026-09-21', effort_hours: 12 })] })
  expect(state.writes.some(item => item.path.includes('/files/'))).toBe(false)
  expect(state.writes.some(item => item.path.includes('preview-confirmation'))).toBe(false)
  await page.reload()
  await expect(workspace(page).getByRole('button', { name: 'Verify employee onboarding workflow', exact: true })).toBeVisible()
  await workspace(page).getByRole('button', { name: 'Verify employee onboarding workflow', exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'Activity details', exact: true }).getByRole('button', { name: 'View activity for Omar Saleh', exact: true })).toBeVisible()
  expect(state.records[17].simplePlan.tasks[0].planned_finish_date).toBe('2026-09-22')
  clean(state)
})

test('failed activity save keeps edits then the reviewed revision is submitted and published', async ({ page }) => {
  const state = await open(page)
  await workspace(page).getByRole('button', { name: registerNames[0], exact: true }).click()
  await page.getByRole('complementary', { name: 'Activity details', exact: true }).getByRole('button', { name: 'Edit activity', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit task', exact: true })
  await editor.getByLabel('Duration (working days)', { exact: true }).fill('4')
  state.saveError = { error: 'The plan changed in another session. Your edits have not been saved.', code: 'simple_plan_revision_conflict' }
  await editor.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(editor.getByRole('alert')).toContainText('Your edits have not been saved')
  await expect(editor.getByLabel('Duration (working days)', { exact: true })).toHaveValue('4')
  expect(state.records[17].simplePlan.revision).toBe(4)
  state.saveError = null
  await editor.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(editor).toHaveCount(0)
  expect(state.records[17].simplePlan.revision).toBe(5)
  expect(simpleWrites(state).filter(item => item.method === 'PUT').map(item => item.data.revision)).toEqual([4, 4])
  expect(state.records[17].simplePlan.tasks[0].title).toBe(registerNames[0])
  await workspace(page).getByRole('button', { name: 'Review & approve', exact: true }).click()
  const approval = page.getByRole('dialog', { name: 'Review & publish baseline', exact: true })
  await expect(approval).toBeVisible()
  await approval.getByRole('combobox', { name: 'Plan approver', exact: true }).selectOption('7')
  await approval.getByRole('button', { name: 'Submit for approval', exact: true }).click()
  await expect(approval.getByRole('button', { name: 'Approve & publish baseline', exact: true })).toBeEnabled()
  expect(simpleWrites(state).find(item => item.path.endsWith('/submit/')).data).toEqual({ revision: 5, approver_id: 7 })
  await approval.getByRole('button', { name: 'Approve & publish baseline', exact: true }).click()
  await expect(approval.getByRole('heading', { name: 'Baseline published', exact: true })).toBeVisible()
  expect(simpleWrites(state).find(item => item.path.endsWith('/approve-publish/')).data).toEqual({ revision: 6 })
  await approval.getByRole('button', { name: 'Close Review & publish baseline', exact: true }).click()
  await expect(await scheduleActionButton(page, 'Add activity')).toBeDisabled()
  await scheduleAction(page, 'New version')
  await expect(await scheduleActionButton(page, 'Add activity')).toBeEnabled()
  await closeScheduleMenu(page, 'Schedule actions')
  expect(simpleWrites(state).find(item => item.path.endsWith('/reopen/')).data).toEqual({ revision: 7 })
  expect(state.records[17].simplePlan.baseline.name).toBe('Approved Phase 1 baseline')
  clean(state)
})

test('failed project connection does not expose duplicate workspace creation and can be retried', async ({ page }) => {
  const state = await masterScheduleHarness(page, { projectListError: true })
  await expect(page.getByRole('alert').filter({ hasText: 'Planning workspace connection temporarily unavailable.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Project inputs', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Upload documents / Project inputs', exact: true })).toHaveCount(0)
  expect(state.writes).toEqual([])
  state.projectListError = false
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(workspace(page).getByRole('heading', { name: 'Master Schedule', exact: true })).toBeVisible()
  expect(state.writes).toEqual([])
  clean(state)
})

test('saving an unchanged submitted plan preserves its approval request', async ({ page }) => {
  const state = await open(page, { prepare(current) {
    current.records[17].simplePlan.state = 'submitted'
    current.records[17].simplePlan.review = { id: 505, status: 'pending' }
  } })
  await scheduleAction(page, 'Save draft')
  await expect(page.getByRole('status').filter({ hasText: 'The plan is saved and awaiting approval.' })).toBeVisible()
  expect(simpleWrites(state)).toEqual([])
  expect(state.records[17].simplePlan.review.status).toBe('pending')
  clean(state)
})

test('saved schedule versions are fetched explicitly and stay read only', async ({ page }) => {
  const state = await open(page, { history: true })
  await scheduleMenu(page, 'Schedule filters')
  await expect(workspace(page).getByRole('checkbox', { name: 'Critical only', exact: true })).toBeDisabled()
  await closeScheduleMenu(page, 'Schedule filters')
  await scheduleVersion(page, '90')
  await expect(await scheduleActionButton(page, 'Add activity')).toBeDisabled()
  await expect(await scheduleActionButton(page, 'Save draft')).toBeDisabled()
  await closeScheduleMenu(page, 'Schedule actions')
  await expect(page.getByText('You are viewing a saved schedule version.', { exact: false })).toBeVisible()
  expect(state.requests.some(item => item.path.endsWith('/simple-plan/') && item.query.version_id === '90')).toBe(true)
  await scheduleMenu(page, 'Schedule filters')
  await expect(workspace(page).getByRole('checkbox', { name: 'Critical only', exact: true })).toBeEnabled()
  await closeScheduleMenu(page, 'Schedule filters')
  await scheduleVersion(page, 'current')
  await expect(await scheduleActionButton(page, 'Add activity')).toBeEnabled()
  await closeScheduleMenu(page, 'Schedule actions')
  await scheduleMenu(page, 'Schedule filters')
  await expect(workspace(page).getByRole('checkbox', { name: 'Critical only', exact: true })).toBeDisabled()
  await closeScheduleMenu(page, 'Schedule filters')
  expect(state.writes).toEqual([])
  clean(state)
})

test('mobile schedule scrolls within its panel and activity details support keyboard navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const state = await open(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  const activity = workspace(page).getByRole('button', { name: registerNames[0], exact: true })
  await activity.focus()
  await page.keyboard.press('Enter')
  const drawer = page.getByRole('complementary', { name: 'Activity details', exact: true })
  await expect(drawer).toBeVisible()
  await expect(drawer).toContainText(registerNames[0])
  const box = await drawer.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  await drawer.getByRole('button', { name: 'Close activity details', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(drawer).toHaveCount(0)
  await activity.focus()
  await page.keyboard.press('Enter')
  await expect(drawer).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(activity).toBeFocused()
  const scan = await new AxeBuilder({ page }).include('.schedule-canvas').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  await page.screenshot({ path: '../artifacts/master-schedule-mobile.png', fullPage: true, animations: 'disabled' })
  expect(state.writes).toEqual([])
  clean(state)
})
