import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'
import { milestoneHarness } from '../fixtures/milestone-control.fixture'

test.setTimeout(60000)
const region = (page, name) => page.getByRole('region', { name, exact: true })
const register = page => region(page, 'Milestone register')
const row = (page, name) => register(page).getByRole('row').filter({ hasText: name })
const workAreas = page => page.getByRole('navigation', { name: 'Project work areas', exact: true })

async function loaded(page) {
  await expect(page.getByRole('heading', { name: 'Milestone Control', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Management', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(register(page)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled()
}

async function selectMatching(select, pattern) {
  const option = select.getByRole('option').filter({ hasText: pattern }).first()
  await select.selectOption(await option.evaluate(element => element.value))
}

async function selectMilestone(page, name) {
  await row(page, name).getByRole('button', { name, exact: true }).click()
}

async function noHorizontalOverflow(page) {
  const dimensions = await page.evaluate(() => ({
    viewport: innerWidth, document: document.documentElement.scrollWidth,
    overflowing: [...document.querySelectorAll('.project-performance-workspace *')].filter(element => {
      for (let parent = element.parentElement; parent && !['BODY', 'HTML'].includes(parent.tagName); parent = parent.parentElement) {
        if (['hidden', 'auto', 'scroll', 'clip'].includes(getComputedStyle(parent).overflowX)) return false
      }
      return element.getBoundingClientRect().right > innerWidth + 1
    }).slice(0, 12).map(element => ({ tag: element.tagName, className: element.className?.baseVal ?? element.className, right: Math.round(element.getBoundingClientRect().right) })),
  }))
  expect(dimensions.document, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.viewport + 1)
}

async function accessible(page) {
  const scan = await new AxeBuilder({ page }).include('.project-performance-workspace').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
}

test('desktop Milestone Control combines eight recorded milestones with honest source and readiness details', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await milestoneHarness(page)
  await loaded(page)
  const indicators = region(page, 'Milestone indicators')
  for (const label of ['Total milestones', 'Achieved', 'Due next 30 days', 'Overdue', 'Blocked', 'Forecast confidence']) await expect(indicators.getByText(label, { exact: true })).toBeVisible()
  await expect(indicators.getByRole('article').filter({ hasText: 'Total milestones' })).toContainText('8')
  await expect(indicators.getByRole('article').filter({ hasText: 'Forecast confidence' })).toContainText('Not assessed')
  for (const name of ['Milestone roadmap', 'Milestone actions', 'Milestone details', 'Acceptance & evidence', 'Downstream impact', 'Milestone data quality']) await expect(region(page, name)).toBeVisible()
  await expect(register(page).getByRole('row')).toHaveCount(9)
  await expect(row(page, 'Design basis approved')).toContainText(/Achieved|Complete/)
  await expect(row(page, 'Vendor data approval')).toContainText('Overdue')
  await expect(row(page, 'Mechanical completion')).toContainText(/Blocked|At risk|Late/)
  await expect(row(page, 'Mechanical completion')).toContainText('Omar Saleh')
  await expect(row(page, 'IFC package release')).toContainText('MS-IFC')
  await expect(row(page, 'Project handover')).toContainText(/PRJ-|Project/)
  await noHorizontalOverflow(page)
  await page.screenshot({ path: '../artifacts/milestone-control-desktop.png', animations: 'disabled' })
  await accessible(page)
  expect(state.unknown).toEqual([])
  expect(state.writes).toEqual([])
})

test('milestone filters constrain source, status, owner, due window, criticality, and search', async ({ page }) => {
  await milestoneHarness(page)
  await loaded(page)
  const search = page.getByRole('searchbox', { name: 'Search milestone or reference', exact: true })
  const status = page.getByRole('combobox', { name: 'Status', exact: true })
  await selectMatching(status, /^Overdue$/i)
  await expect(row(page, 'Vendor data approval')).toBeVisible()
  await expect(row(page, 'Design basis approved')).toHaveCount(0)
  await selectMatching(status, /^All/i)
  const type = page.getByRole('combobox', { name: 'Type', exact: true })
  await selectMatching(type, /Schedule/i)
  await expect(row(page, 'IFC package release')).toBeVisible()
  await expect(row(page, 'Vendor data approval')).toHaveCount(0)
  await selectMatching(type, /^All/i)
  const owner = page.getByRole('combobox', { name: 'Owner', exact: true })
  await selectMatching(owner, /Omar Saleh/i)
  await expect(row(page, 'Mechanical completion')).toBeVisible()
  await expect(row(page, 'Vendor data approval')).toHaveCount(0)
  await selectMatching(owner, /^All/i)
  const dateRange = page.getByRole('combobox', { name: 'Date range', exact: true })
  await selectMatching(dateRange, /Next 30 days/i)
  await expect(row(page, 'IFC package release')).toBeVisible()
  await expect(row(page, 'Project handover')).toHaveCount(0)
  await selectMatching(dateRange, /Full project/i)
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Critical only', exact: true }).check()
  await expect(row(page, 'IFC package release')).toBeVisible()
  await expect(row(page, 'Mechanical completion')).toBeVisible()
  await expect(row(page, 'Vendor data approval')).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Critical only', exact: true }).uncheck()
  const source = page.getByRole('combobox', { name: 'Source', exact: true })
  await selectMatching(source, /Project/i)
  await expect(row(page, 'Vendor data approval')).toBeVisible()
  await expect(row(page, 'IFC package release')).toHaveCount(0)
  await selectMatching(source, /^All/i)
  await search.fill('MS-MECH')
  await expect(row(page, 'Mechanical completion')).toBeVisible()
  await expect(register(page).getByRole('row')).toHaveCount(2)
})

test('Timeline and Calendar preserve milestone selection and Register mode retains all records', async ({ page }) => {
  await milestoneHarness(page)
  await loaded(page)
  await page.getByRole('button', { name: 'Calendar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Calendar', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await selectMilestone(page, 'IFC package release')
  await expect(page.getByRole('heading', { name: 'IFC package release', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Timeline', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Timeline', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Register', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Register', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(register(page).getByRole('row')).toHaveCount(9)
  await page.getByRole('button', { name: 'Management', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Timeline', exact: true })).toBeVisible()
})

test('selected milestones disclose real schedule dependencies and missing evidence without invented attachments', async ({ page }) => {
  const state = await milestoneHarness(page)
  await loaded(page)
  await selectMilestone(page, 'Mechanical completion')
  await expect(page.getByRole('heading', { name: 'Mechanical completion', exact: true })).toBeVisible()
  await expect(page.getByText('Tie-in window confirmation', { exact: true }).first()).toBeVisible()
  await expect(region(page, 'Downstream impact')).toContainText('Site tie-in installation')
  await selectMilestone(page, 'Vendor data approval')
  const evidence = page.getByRole('button', { name: /Review evidence/i }).first()
  await evidence.click()
  const dialog = page.getByRole('dialog', { name: /Evidence/i })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText(/No.*evidence|not.*linked|not.*recorded|unavailable/i)
  await expect(dialog.getByRole('button', { name: /Upload|Approve evidence/i })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(evidence).toBeFocused()
  await selectMilestone(page, 'IFC package release')
  await page.getByRole('button', { name: 'Update forecast', exact: true }).click()
  await expect(page).toHaveURL(/view=plan-baseline/)
  await expect(page.getByRole('heading', { name: 'Schedule Performance', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Planner', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(state.writes).toEqual([])
})

test('Add and Edit milestone persist only supported fields and retain the selected project association', async ({ page }) => {
  const state = await milestoneHarness(page)
  await loaded(page)
  await page.getByRole('button', { name: 'Add milestone', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Add milestone', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Milestone name', { exact: true }).fill('Operations readiness review')
  await dialog.getByLabel('Description', { exact: true }).fill('Confirm the recorded operations readiness gate.')
  await dialog.getByLabel('Target date', { exact: true }).fill('2026-10-12')
  await dialog.getByRole('button', { name: /Save milestone|Create milestone/, exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(row(page, 'Operations readiness review')).toBeVisible()
  expect(state.writes).toHaveLength(1)
  expect(state.writes[0]).toMatchObject({ method: 'POST', project: 17, body: { project: 17, name: 'Operations readiness review', description: 'Confirm the recorded operations readiness gate.', target_date: '2026-10-12' } })
  expect(Object.keys(state.writes[0].body).every(key => ['project', 'name', 'description', 'target_date', 'is_completed', 'completed_date'].includes(key))).toBe(true)
  await selectMilestone(page, 'Operations readiness review')
  await page.getByRole('button', { name: 'Edit milestone', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Edit milestone', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByLabel('Milestone name', { exact: true }).fill('Operations readiness accepted')
  await dialog.getByLabel('Target date', { exact: true }).fill('2026-10-13')
  await dialog.getByRole('checkbox', { name: 'Completion reported', exact: true }).check()
  await dialog.getByLabel('Completion date', { exact: true }).fill('2026-09-14')
  await dialog.getByRole('button', { name: 'Save milestone', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(row(page, 'Operations readiness accepted')).toBeVisible()
  expect(state.writes).toHaveLength(2)
  expect(state.writes[1]).toMatchObject({ method: 'PATCH', project: 17, body: { name: 'Operations readiness accepted', target_date: '2026-10-13', is_completed: true, completed_date: '2026-09-14' } })
  expect(state.records[18].milestones.some(item => /Operations readiness/.test(item.name))).toBe(false)
  expect(state.unknown).toEqual([])
})

test('failed milestone saves preserve entered values and a retry creates only one record', async ({ page }) => {
  const state = await milestoneHarness(page, { prepare: current => { current.saveFailure = true } })
  await loaded(page)
  await page.getByRole('button', { name: 'Add milestone', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add milestone', exact: true })
  await dialog.getByLabel('Milestone name', { exact: true }).fill('Retry readiness gate')
  await dialog.getByLabel('Target date', { exact: true }).fill('2026-10-09')
  await dialog.getByRole('button', { name: /Save milestone|Create milestone/, exact: true }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog.getByLabel('Milestone name', { exact: true })).toHaveValue('Retry readiness gate')
  expect(state.records[17].milestones.filter(item => item.name === 'Retry readiness gate')).toHaveLength(0)
  state.saveFailure = false
  await dialog.getByRole('button', { name: /Save milestone|Create milestone/, exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(row(page, 'Retry readiness gate')).toBeVisible()
  expect(state.records[17].milestones.filter(item => item.name === 'Retry readiness gate')).toHaveLength(1)
})

test('schedule import previews without a write and creates only selected milestones with source provenance', async ({ page }) => {
  const state = await milestoneHarness(page)
  await loaded(page)
  const importer = page.getByRole('button', { name: 'Import from schedule', exact: true })
  await importer.click()
  let dialog = page.getByRole('dialog', { name: 'Import milestones from schedule', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('Mechanical completion')
  expect(state.writes).toEqual([])
  await page.keyboard.press('Escape')
  await expect(importer).toBeFocused()
  expect(state.writes).toEqual([])
  await importer.click()
  dialog = page.getByRole('dialog', { name: 'Import milestones from schedule', exact: true })
  await dialog.getByRole('checkbox', { name: /Mechanical completion/ }).check()
  await dialog.getByRole('button', { name: /Import selected/i }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes).toHaveLength(1)
  expect(state.writes[0]).toMatchObject({ method: 'POST', project: 17, body: { name: 'Mechanical completion', target_date: '2026-10-10' } })
  expect(state.writes[0].body.description).toMatch(/RADAI schedule milestone.*71:81:MS-MECH/)
  await expect(row(page, 'Mechanical completion')).toHaveCount(1)
  await expect(register(page).getByRole('row')).toHaveCount(9)
  expect(state.records[17].milestones.filter(item => item.name === 'Mechanical completion')).toHaveLength(1)
  await importer.click()
  dialog = page.getByRole('dialog', { name: 'Import milestones from schedule', exact: true })
  await expect(dialog.getByRole('checkbox', { name: /Mechanical completion/ })).toBeDisabled()
  await page.keyboard.press('Escape')
  expect(state.writes).toHaveLength(1)
})

test('milestone CSV retains combined source records outside the active filters', async ({ page }) => {
  const state = await milestoneHarness(page)
  await loaded(page)
  await page.getByRole('searchbox', { name: 'Search milestone or reference', exact: true }).fill('Vendor')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export milestone report', exact: true }).click()
  const download = await pending
  expect(download.suggestedFilename()).toMatch(/\.csv$/i)
  const contents = await readFile(await download.path(), 'utf8')
  expect(contents).toContain('5900913')
  expect(contents).toContain('Vendor data approval')
  expect(contents).toContain('Project handover')
  expect(contents).toContain('MS-MECH')
  expect(contents).toContain('MS-IFC')
  expect(contents).toContain('2026-12-20')
  expect(state.writes).toEqual([])
})

test('partial schedule import preserves successful rows and retries only the remaining selection', async ({ page }) => {
  const state = await milestoneHarness(page, { prepare: current => { current.saveFailureName = 'Mechanical completion' } })
  await loaded(page)
  const importer = page.getByRole('button', { name: 'Import from schedule', exact: true })
  await importer.click()
  let dialog = page.getByRole('dialog', { name: 'Import milestones from schedule', exact: true })
  await dialog.getByRole('checkbox', { name: /IFC package release/ }).check()
  await dialog.getByRole('checkbox', { name: /Mechanical completion/ }).check()
  await dialog.getByRole('button', { name: 'Import selected', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('1 milestone(s) saved')
  expect(state.records[17].milestones.filter(item => item.name === 'IFC package release')).toHaveLength(1)
  expect(state.records[17].milestones.filter(item => item.name === 'Mechanical completion')).toHaveLength(0)
  await page.keyboard.press('Escape')
  await expect(importer).toBeFocused()
  await expect(register(page).getByRole('row')).toHaveCount(9)
  state.saveFailureName = null
  await importer.click()
  dialog = page.getByRole('dialog', { name: 'Import milestones from schedule', exact: true })
  await expect(dialog.getByRole('checkbox', { name: /IFC package release/ })).toBeDisabled()
  await dialog.getByRole('checkbox', { name: /Mechanical completion/ }).check()
  await dialog.getByRole('button', { name: 'Import selected', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.records[17].milestones.filter(item => item.name === 'IFC package release')).toHaveLength(1)
  expect(state.records[17].milestones.filter(item => item.name === 'Mechanical completion')).toHaveLength(1)
  expect(state.writes.filter(write => write.body.name === 'IFC package release')).toHaveLength(1)
  expect(state.writes.filter(write => write.body.name === 'Mechanical completion')).toHaveLength(2)
  await expect(register(page).getByRole('row')).toHaveCount(9)
})

test('Refresh and project switching reload milestones and preserve the selected work area', async ({ page }) => {
  const state = await milestoneHarness(page)
  await loaded(page)
  state.records[17].milestones.find(item => item.id === 902).name = 'Vendor data approval updated'
  state.records[17].project.client_name = 'Updated Refining Client'
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(row(page, 'Vendor data approval updated')).toBeVisible()
  await expect(page.getByText('Client: Updated Refining Client', { exact: true })).toBeVisible()
  const selector = page.getByRole('combobox', { name: 'Active Project', exact: true })
  await selector.fill('5900738')
  await selector.press('Enter')
  await expect(page).toHaveURL(/project=18/)
  await expect(page).toHaveURL(/view=milestones/)
  await expect(row(page, 'Vendor data approval updated')).toHaveCount(0)
  await expect(row(page, 'Vendor data approval')).toBeVisible()
  await expect.poll(() => state.requests.some(request => request.path.endsWith('/projects/milestones/') && request.project === 18)).toBe(true)
  expect(state.unknown).toEqual([])
})

test('empty project and schedule milestones stay distinct from failed sources', async ({ page }) => {
  const state = await milestoneHarness(page, { prepare: current => {
    current.records[17].milestones = []
    current.noLinked = true
  } })
  await loaded(page)
  await expect(register(page)).toContainText(/No.*milestone/i)
  state.failures.add('/projects/milestones/')
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert').first()).toBeVisible()
  await expect(page.getByRole('alert').first()).toContainText(/unavailable|could not be loaded/i)
  await expect(register(page)).toContainText(/unavailable|could not be loaded/i)
  state.failures.clear()
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(register(page)).toContainText(/No.*milestone/i)
})

test('mobile Milestone Control and native forms fit the viewport and preserve keyboard focus', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await milestoneHarness(page)
  await loaded(page)
  await noHorizontalOverflow(page)
  await page.screenshot({ path: '../artifacts/milestone-control-mobile.png', animations: 'disabled' })
  await page.screenshot({ path: '../artifacts/milestone-control-mobile-full.png', fullPage: true, animations: 'disabled' })
  const add = page.getByRole('button', { name: 'Add milestone', exact: true })
  await add.click()
  const dialog = page.getByRole('dialog', { name: 'Add milestone', exact: true })
  await expect(dialog).toBeVisible()
  const bounds = await dialog.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(391)
  expect(bounds.height).toBeLessThanOrEqual(844)
  await noHorizontalOverflow(page)
  await page.keyboard.press('Escape')
  await expect(add).toBeFocused()
  await accessible(page)
  await workAreas(page).getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project Performance', exact: true })).toBeVisible()
})
