import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { delayHarness, delayResult } from '../fixtures/delay-analysis.fixture.js'
import { scheduleArea, scheduleVersion, scheduleWorkspace } from '../fixtures/schedule-controls.js'

test.setTimeout(60000)
const panel = page => page.getByRole('region', { name: 'Delay and recovery analysis', exact: true })
const open = async page => { await scheduleArea(page, 'delay'); await expect(panel(page).getByRole('heading', { name: 'Delay & recovery', exact: true })).toBeVisible() }
const view = (page, title) => panel(page).getByRole('tab', { name: title, exact: true }).click()
const clean = state => { expect(state.pageErrors).toEqual([]); expect(state.unknown).toEqual([]); expect(state.unknownWrites).toEqual([]); expect(state.writes).toEqual([]) }
const durationChange = async (page, prefix = 'Impact', proposed = '6') => {
  const p = panel(page)
  await p.getByRole('button', { name: `Add ${prefix.toLowerCase()} change`, exact: true }).click()
  await p.getByLabel(`${prefix} event 1`, { exact: true }).selectOption('41')
  await p.getByLabel(`${prefix} field 1`, { exact: true }).selectOption('remaining_duration_days')
  await p.getByLabel(`${prefix} activity 1`, { exact: true }).selectOption('101')
  await p.getByLabel(`${prefix} proposed value 1`, { exact: true }).fill(proposed)
  await p.getByLabel(`${prefix} evidence 1`, { exact: true }).fill('Approved access record 42')
  await p.getByLabel(`${prefix} reason 1`, { exact: true }).fill('Explicit remaining work estimate under the recorded access condition.')
}

test('delay area loads lazily without writes or assumed impact when a baseline is missing', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { Object.assign(current.delay, { baseline: null, baselines: [], case: null, cases: [], events: [], published_reports: [] }) } })
  expect(state.delayReads).toEqual([])
  await open(page)
  await expect(panel(page)).toContainText('An approved baseline is required for delay analysis')
  await expect(scheduleWorkspace(page).getByRole('button', { name: 'Save', exact: true })).toHaveCount(0)
  await expect(scheduleWorkspace(page).getByText('Changes saved', { exact: true })).toHaveCount(0)
  expect(state.delayWrites).toEqual([]); clean(state)
})

test('recording an event requires explicit activity and evidence but preserves unknown dates', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); const p = panel(page)
  await p.getByRole('button', { name: 'Record delay event', exact: true }).click()
  await p.getByLabel('Delay event title', { exact: true }).fill('Supplier hold')
  await p.getByLabel('Delay event description', { exact: true }).fill('Supplier record identifies a hold.')
  await p.getByLabel('ACT-002 · Equipment installation', { exact: true }).check()
  await expect(p.getByRole('button', { name: 'Record event', exact: true })).toBeDisabled()
  await p.getByLabel('Delay event evidence 1', { exact: true }).fill('Supplier notice 17')
  await p.getByRole('button', { name: 'Record event', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Delay event recorded')
  expect(state.delayWrites).toEqual([{ action: 'create_event', baseline_id: 11, title: 'Supplier hold', description: 'Supplier record identifies a hold.', start_date: null, end_date: null, activity_ids: [102], evidence: [{ reference: 'Supplier notice 17' }], governance_item_id: null, risk_id: null }]); clean(state)
})

test('new impact case requires explicit published reference and recorded events', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); const p = panel(page)
  await p.getByRole('button', { name: 'New impact case', exact: true }).click()
  await p.getByLabel('Delay case name', { exact: true }).fill('Permit impact comparison')
  await expect(p.getByLabel('Delay case published report', { exact: true })).toHaveValue('')
  await p.getByLabel('Delay case published report', { exact: true }).selectOption('31')
  await p.getByLabel('Include delay event Recorded access hold', { exact: true }).check()
  await p.getByRole('button', { name: 'Create impact case', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Case created')
  expect(state.delayWrites[0]).toEqual({ action: 'create_case', baseline_id: 11, reference_report_id: '31', name: 'Permit impact comparison', event_ids: [41] }); clean(state)
})

test('impact edits retain published expected values and survive Gantt navigation until explicitly saved', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); await view(page, 'Impact & recovery inputs'); await durationChange(page)
  const p = panel(page)
  await expect(p.getByLabel('Impact expected before 1', { exact: true })).toHaveValue('3')
  await expect(p.getByLabel('Requested extension calendar days', { exact: true })).toHaveValue('')
  await scheduleArea(page, 'activities'); await scheduleArea(page, 'delay')
  await expect(p.getByLabel('Impact proposed value 1', { exact: true })).toHaveValue('6')
  await expect(p.getByRole('button', { name: 'Refresh delay analysis', exact: true })).toBeDisabled()
  await p.getByRole('button', { name: 'Save case inputs', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Impact and recovery inputs saved')
  expect(state.delayWrites).toHaveLength(1)
  expect(state.delayWrites[0]).toMatchObject({ action: 'save_case', case_id: 51, revision: 3, changes: [{ event_id: 41, activity_id: 101, field: 'remaining_duration_days', expected_before: 3, value: 6 }], scenarios: [], recommendation: { selected_scenario_id: null, requested_extension_calendar_days: null } }); clean(state)
})

test('recovery is an explicit alternative using impacted expected value and never auto awards time', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); await view(page, 'Impact & recovery inputs'); await durationChange(page)
  const p = panel(page)
  await p.getByRole('button', { name: 'Add recovery alternative', exact: true }).click()
  await p.getByLabel('Recovery alternative name 1', { exact: true }).fill('Additional access shift')
  await durationChange(page, 'Recovery 1', '2')
  await expect(p.getByLabel('Recovery 1 expected before 1', { exact: true })).toHaveValue('6')
  await p.getByRole('button', { name: 'Save case inputs', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Impact and recovery inputs saved')
  expect(state.delayWrites[0].scenarios[0]).toMatchObject({ name: 'Additional access shift', changes: [{ activity_id: 101, expected_before: 6, value: 2 }] })
  expect(state.delayWrites[0].recommendation.requested_extension_calendar_days).toBeNull(); clean(state)
})

test('advanced dependency edits preserve exact reference relationship and require an explicit replacement', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); await view(page, 'Impact & recovery inputs'); const p = panel(page)
  await p.getByRole('button', { name: 'Add impact change', exact: true }).click()
  await p.getByLabel('Impact event 1', { exact: true }).selectOption('41')
  await p.getByLabel('Impact field 1', { exact: true }).selectOption('relationship')
  await p.getByLabel('Impact predecessor 1', { exact: true }).selectOption('101')
  await p.getByLabel('Impact successor 1', { exact: true }).selectOption('102')
  await expect(p.getByLabel('Impact expected 1 relationship type', { exact: true })).toHaveValue('FS')
  await expect(p.getByLabel('Impact expected 1 lag', { exact: true })).toHaveValue('0')
  await expect(p.getByLabel('Impact proposed 1 relationship type', { exact: true })).toHaveValue('')
  await p.getByLabel('Impact proposed 1 relationship type', { exact: true }).selectOption('SS')
  await p.getByLabel('Impact proposed 1 lag', { exact: true }).fill('1')
  await p.getByLabel('Impact evidence 1', { exact: true }).fill('Reviewed method statement 16')
  await p.getByLabel('Impact reason 1', { exact: true }).fill('Explicit overlap sequence for scenario review.')
  await p.getByRole('button', { name: 'Save case inputs', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Impact and recovery inputs saved')
  expect(state.delayWrites[0].changes[0]).toMatchObject({ field: 'relationship', predecessor_id: 101, successor_id: 102, expected_before: { type: 'FS', lag_days: 0 }, value: { type: 'SS', lag_days: 1 } }); clean(state)
})

test('calculated impact and proposed recovery display server values with unknown distinct from zero', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await p.getByRole('button', { name: 'Calculate impact and alternatives', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('comparisons calculated')
  const table = p.getByRole('region', { name: 'Impact and recovery comparison', exact: true })
  await expect(table.getByRole('row').filter({ hasText: 'Combined impact' })).toContainText('5 calendar d')
  await expect(table.getByRole('row').filter({ hasText: 'Additional access shift' })).toContainText('Not Specified')
  await expect(p.getByRole('region', { name: 'Combined impact activity comparison', exact: true }).getByRole('row').filter({ hasText: 'ACT-001' })).toContainText('0')
  await expect(p).toContainText('Not awarded by this review')
  expect(state.delayWrites).toEqual([{ action: 'calculate_case', case_id: 51, revision: 3 }]); clean(state)
})

test('independent recommendation decisions use exact revision and fresh fingerprint without baseline changes', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { Object.assign(current.delay.case, { status: 'calculated', run: { id: 61, fingerprint: 'b'.repeat(64), result: delayResult() } }); current.delay.case.permissions.can_submit = true }, async onCommand({ state, route, reply }, body) { if (body.action === 'submit_case') { Object.assign(state.delay.case, { status: 'submitted', revision: 4, source_fingerprint: 'c'.repeat(64) }); state.delay.case.permissions = { can_edit: false, can_submit: false, can_approve: true, can_export: true } } else { state.delay.case.status = 'approved'; state.delay.case.permissions = { can_export: true, can_revise: true } } await reply(route, state.delay); return true } })
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await p.getByLabel('Delay case review reason', { exact: true }).fill('Evidence and combined impacts reviewed.')
  await p.getByRole('button', { name: 'Submit case for review', exact: true }).click()
  await expect(p.getByRole('button', { name: 'Approve internal recommendation', exact: true })).toBeDisabled()
  await p.getByLabel('Delay case review reason', { exact: true }).fill('Independent technical recommendation review completed.')
  await p.getByRole('button', { name: 'Approve internal recommendation', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('No contractual entitlement was awarded')
  expect(state.delayWrites.map(row => [row.action, row.revision, row.source_fingerprint])).toEqual([['submit_case', 3, 'a'.repeat(64)], ['approve_case', 4, 'c'.repeat(64)]]); clean(state)
})

test('stale source errors preserve the decision reason and never silently retry', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { current.delay.case.permissions.can_submit = true }, async onCommand({ route }) { await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ source_fingerprint: ['Source evidence changed. Refresh and recalculate.'] }) }); return true } })
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await p.getByLabel('Delay case review reason', { exact: true }).fill('Submitted evidence review.')
  await p.getByRole('button', { name: 'Submit case for review', exact: true }).click()
  await expect(p.getByRole('alert')).toContainText('Source evidence changed')
  await expect(p.getByLabel('Delay case review reason', { exact: true })).toHaveValue('Submitted evidence review.')
  expect(state.delayWrites).toHaveLength(1); clean(state)
})

test('unpublished references cannot create a case and historical views remain read only with accessible tabs', async ({ page }) => {
  const state = await delayHarness(page, { history: true, prepare(current) { current.delay.published_reports = [] } })
  await scheduleVersion(page, '90'); await open(page); const p = panel(page)
  await expect(p).toContainText('This historical schedule view is read only')
  await expect(p.getByRole('button', { name: 'New impact case', exact: true })).toHaveCount(0)
  await p.getByRole('tab', { name: 'Event register', exact: true }).focus(); await page.keyboard.press('ArrowRight')
  await expect(p.getByRole('tab', { name: 'Impact & recovery inputs', exact: true })).toBeFocused()
  await expect(p.getByRole('button', { name: 'Add impact change', exact: true })).toBeDisabled()
  expect((await new AxeBuilder({ page }).include('.planning-delay-analysis').analyze()).violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  expect(state.delayWrites).toEqual([]); clean(state)
})

test('case export occurs only on explicit download and carries the selected case identifier', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { current.delay.case.permissions.can_export = true } })
  await open(page); await view(page, 'Compare & review')
  expect(state.delayExports).toEqual([])
  const download = page.waitForEvent('download')
  await panel(page).getByRole('button', { name: 'Download case JSON', exact: true }).click()
  expect((await download).suggestedFilename()).toBe('reviewed-delay-case.json')
  expect(state.delayExports[0]).toMatchObject({ format: 'json' })
  expect(state.delayExports[0].path).toContain('/delay-analysis/cases/51/export/')
  expect(state.delayWrites).toEqual([]); clean(state)
})

test('hold recovery removes only an explicitly recorded boundary and retains its expected date', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { current.delay.case.changes = [{ event_id: 41, activity_id: 101, field: 'remaining_not_before', expected_before: null, value: '2026-09-28', evidence: 'Permit 42', reason: 'Recorded access restart date.' }] } })
  await open(page); await view(page, 'Impact & recovery inputs'); const p = panel(page)
  await p.getByRole('button', { name: 'Add recovery alternative', exact: true }).click()
  await p.getByLabel('Recovery alternative name 1', { exact: true }).fill('Release recorded hold')
  await p.getByRole('button', { name: 'Add recovery 1 change', exact: true }).click()
  await p.getByLabel('Recovery 1 event 1', { exact: true }).selectOption('41')
  await p.getByLabel('Recovery 1 field 1', { exact: true }).selectOption('remaining_not_before')
  await p.getByLabel('Recovery 1 activity 1', { exact: true }).selectOption('101')
  await expect(p.getByLabel('Recovery 1 expected before 1', { exact: true })).toHaveValue('2026-09-28')
  await p.getByLabel('Recovery 1 remove hold 1', { exact: true }).check()
  await p.getByLabel('Recovery 1 evidence 1', { exact: true }).fill('Permit release proposal 43')
  await p.getByLabel('Recovery 1 reason 1', { exact: true }).fill('Test access release without changing recorded actual dates.')
  await p.getByRole('button', { name: 'Save case inputs', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Impact and recovery inputs saved')
  expect(state.delayWrites[0].scenarios[0].changes[0]).toMatchObject({ field: 'remaining_not_before', expected_before: '2026-09-28', value: null }); clean(state)
})

test('stale sources disable decisions and reviewed evidence stays distinct from the current event register', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { Object.assign(current.delay.case, { status: 'submitted', source_stale: true, issues: [{ code: 'reference_corrected_later', message: 'A later published correction exists for this reference.' }], run: { id: 61, fingerprint: 'b'.repeat(64), result: delayResult(), events: [{ ...structuredClone(current.delay.events[0]), title: 'Frozen original access event' }] }, permissions: { can_approve: true, can_return: true, can_calculate: false } }); current.delay.events[0].title = 'Current updated access event' } })
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await p.getByLabel('Delay case review reason', { exact: true }).fill('Awaiting recalculated evidence.')
  await expect(p.getByRole('button', { name: 'Approve internal recommendation', exact: true })).toBeDisabled()
  await expect(p).toContainText('A later published correction exists')
  await p.getByText('Event evidence frozen with this calculation', { exact: true }).click()
  await expect(p.getByRole('heading', { name: 'Frozen original access event · Revision 2', exact: true })).toBeVisible()
  await view(page, 'Event register')
  await expect(p.getByRole('region', { name: 'Recorded delay events', exact: true })).toContainText('Current updated access event')
  expect(state.delayWrites).toEqual([]); clean(state)
})

test('positive extension requests need explicit supporting references and are not copied from impact days', async ({ page }) => {
  const state = await delayHarness(page)
  await open(page); await view(page, 'Impact & recovery inputs'); const p = panel(page)
  await p.getByLabel('Requested extension calendar days', { exact: true }).fill('2')
  await expect(p.getByRole('button', { name: 'Save case inputs', exact: true })).toBeDisabled()
  for (const title of ['Contract clause reference', 'Notice reference', 'Causation assessment', 'Concurrency assessment', 'Mitigation assessment', 'Recommendation basis']) await p.getByLabel(title, { exact: true }).fill(`Reviewed ${title.toLowerCase()}.`)
  await p.getByRole('button', { name: 'Save case inputs', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('Impact and recovery inputs saved')
  expect(state.delayWrites[0].recommendation.requested_extension_calendar_days).toBe(2)
  expect(state.delayWrites[0].changes).toEqual([]); clean(state)
})

test('an author cannot self-approve and reviewed case revision preserves the earlier case', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { Object.assign(current.delay.case, { status: 'approved', created_by_id: 7, reviewed_by_id: 8, permissions: { can_approve: false, can_revise: true, can_edit: false } }) }, async onCommand({ state, route, reply }) { const previous = structuredClone(state.delay.case); state.delay.case = { ...previous, id: 52, name: 'Access impact revision', status: 'draft', revision: 1, supersedes_id: 51, permissions: { can_edit: true, can_calculate: true } }; state.delay.cases = [state.delay.case, previous]; await reply(route, state.delay); return true } })
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await expect(p.getByRole('button', { name: 'Approve internal recommendation', exact: true })).toHaveCount(0)
  await p.getByLabel('Delay case review reason', { exact: true }).fill('New evidence requires a separate reviewed revision.')
  await p.getByRole('button', { name: 'Create case revision', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('earlier reviewed case is preserved')
  expect(state.delayWrites).toEqual([{ action: 'revise_case', case_id: 51, reason: 'New evidence requires a separate reviewed revision.' }])
  expect(state.delay.cases.find(row => row.id === 51).status).toBe('approved'); clean(state)
})

test('independent rejection requires reason and records the exact revision and source fingerprint', async ({ page }) => {
  const state = await delayHarness(page, { prepare(current) { Object.assign(current.delay.case, { status: 'submitted', revision: 7, created_by_id: 8, source_fingerprint: 'd'.repeat(64), permissions: { can_edit: false, can_approve: true, can_return: true } }) }, async onCommand({ state, route, reply }, body) { Object.assign(state.delay.case, { status: 'rejected', revision: 8, reason: body.reason, reviewed_by_id: 7, reviewed_at: '2026-09-23T08:00:00Z', permissions: { can_edit: false, can_revise: true } }); await reply(route, state.delay); return true } })
  await open(page); await view(page, 'Compare & review'); const p = panel(page)
  await expect(p.getByRole('button', { name: 'Reject recommendation', exact: true })).toBeDisabled()
  await p.getByLabel('Delay case review reason', { exact: true }).fill('Evidence does not support the proposed entitlement recommendation.')
  await p.getByRole('button', { name: 'Reject recommendation', exact: true }).click()
  await expect(p.getByRole('status')).toContainText('recommendation rejected')
  await expect(p).toContainText('Reviewed by user 7')
  await expect(p).toContainText('Evidence does not support the proposed entitlement recommendation.')
  expect(state.delayWrites).toEqual([{ action: 'reject_case', case_id: 51, revision: 7, source_fingerprint: 'd'.repeat(64), reason: 'Evidence does not support the proposed entitlement recommendation.' }]); clean(state)
})
