import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { primaveraScheduleHarness, primaveraTitles } from '../fixtures/primavera-schedule.fixture.js'
import { scheduleDiscipline, scheduleCritical, timelineScale } from '../fixtures/schedule-controls.js'

test.setTimeout(60000)
const workspace = page => page.getByRole('region', { name: 'Master schedule workspace', exact: true })
const grid = page => workspace(page).getByRole('region', { name: 'Schedule activities and Gantt', exact: true })
const row = (page, id) => grid(page).locator(`[data-row-id="${id}"]`)
const taskRow = (page, title) => grid(page).locator('[data-row-kind="task"]').filter({ has: page.getByRole('button', { name: title, exact: true }) })
const cell = (target, name) => target.locator(`[data-column="${name}"]`)
const clean = state => {
  expect(state.pageErrors).toEqual([])
  expect(state.unknownWrites).toEqual([])
  expect(state.unknown).toEqual([])
  expect(state.writes).toEqual([])
}
async function open(page, options) {
  await page.setViewportSize({ width: 1740, height: 900 })
  const state = await primaveraScheduleHarness(page, options)
  await expect(workspace(page).getByRole('heading', { name: 'Master Schedule', exact: true })).toBeVisible()
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(44)
  return state
}
async function aligned(page) {
  const rows = await grid(page).locator('.p6-row[data-row-kind]').evaluateAll(elements => elements.map(element => {
    const table = element.querySelector('.p6-table-row')?.getBoundingClientRect()
    const timeline = element.querySelector('.p6-timeline-row')?.getBoundingClientRect()
    return { id: element.dataset.rowId, tableY: table?.y, timelineY: timeline?.y, tableHeight: table?.height, timelineHeight: timeline?.height }
  }))
  expect(rows.length).toBeGreaterThan(0)
  for (const item of rows) {
    expect(item.tableY, item.id).toBeDefined()
    expect(item.timelineY, item.id).toBeDefined()
    expect(Math.abs(item.tableY - item.timelineY), item.id).toBeLessThan(1)
    expect(item.tableHeight, item.id).toBe(item.timelineHeight)
    expect(item.tableHeight, item.id).toBe(32)
  }
}

test('lightweight schedule preserves four WBS levels, exact activity names and stable IDs', async ({ page }) => {
  const state = await open(page)
  await expect(page.getByRole('heading', { name: 'Project Planning', exact: true })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true })).toBeVisible()
  const shell = page.locator('.performance-test-shell')
  expect((await shell.boundingBox()).x).toBe(198)
  await expect(grid(page).locator('[data-row-kind="wbs"]')).toHaveCount(13)
  const divider = await grid(page).getByRole('separator', { name: 'Resize activity table and Gantt', exact: true }).boundingBox()
  const tableScroll = grid(page).getByLabel('Scroll activity columns', { exact: true })
  for (const heading of ['Activity ID', 'Activity Name', 'Duration', 'Start', 'Finish', 'Total\\s*Float']) {
    const header = grid(page).getByRole('columnheader', { name: new RegExp(`^${heading}$`) })
    const right = await header.evaluate(element => element.offsetLeft + element.offsetWidth)
    await tableScroll.evaluate((element, edge) => { element.scrollLeft = Math.max(0, edge - element.clientWidth); element.dispatchEvent(new Event('scroll')) }, right)
    await expect(header).toBeVisible()
    const box = await header.boundingBox()
    expect(box.x + box.width, heading).toBeLessThanOrEqual(divider.x + 1)
  }
  await tableScroll.evaluate(element => { element.scrollLeft = 0; element.dispatchEvent(new Event('scroll')) })
  const tasks = state.records[17].simplePlan.tasks
  expect(await grid(page).locator('.sc-task-name').allTextContents()).toEqual(tasks.map(task => task.title))
  for (const task of tasks) {
    await expect(row(page, task.id)).toHaveAttribute('data-wbs-node-id', String(task.wbs_node_id))
    await expect(cell(row(page, task.id), 'activity-code')).toHaveText(task.activity_code)
  }
  await expect(row(page, 1111)).toContainText('Process Engineering')
  await expect(row(page, 1121)).toContainText('Process Engineering')
  await expect(taskRow(page, primaveraTitles.overlap)).toHaveAttribute('data-wbs-node-id', '1111')
  await expect(taskRow(page, primaveraTitles.overlap)).toHaveAttribute('aria-level', '5')
  await expect(taskRow(page, primaveraTitles.overlap).locator('.p6-ancestor-rails > i')).toHaveCount(4)
  await expect(taskRow(page, primaveraTitles.detailed)).toHaveAttribute('data-wbs-node-id', '1121')
  await aligned(page)
  await page.screenshot({ path: '../artifacts/primavera-schedule-desktop.png', animations: 'disabled' })
  clean(state)
})

test('milestone zero and float zero remain distinct from unknown values; summaries use date spans', async ({ page }) => {
  const state = await open(page)
  const milestone = taskRow(page, primaveraTitles.milestone)
  await expect(cell(milestone, 'duration')).toHaveText('0 d')
  await expect(milestone.locator('.p6-milestone')).toHaveCount(1)
  const unknown = taskRow(page, primaveraTitles.unknown)
  await expect(cell(unknown, 'duration')).toHaveText('Not Specified')
  await expect(cell(unknown, 'float')).toHaveText('—')
  await expect(unknown.locator('.p6-milestone')).toHaveCount(0)
  await expect(unknown.locator('.p6-activity-bar')).toHaveCount(0)
  await expect(cell(taskRow(page, primaveraTitles.overlap), 'float')).toHaveText(/^0(?:\s*d(?:ays?)?)?$/)
  // Both parallel tasks are 10 days. Their common FEED/Process summary is
  // 21 Sep–02 Oct (10 working days), never the summed duration of 20 days.
  await expect(cell(taskRow(page, primaveraTitles.overlap), 'duration')).toHaveText('10 d')
  await expect(cell(taskRow(page, primaveraTitles.parallel), 'duration')).toHaveText('10 d')
  await expect(cell(row(page, 1111), 'duration')).toHaveText('10 d')
  await expect(cell(row(page, 1111), 'start')).toContainText(/21.*Sep/)
  await expect(cell(row(page, 1111), 'finish')).toContainText(/02.*Oct/)
  await expect(row(page, 1111).locator('.p6-summary-bar')).toHaveCount(1)
  const summary = await row(page, 1111).locator('.p6-summary-bar').boundingBox()
  const activity = await taskRow(page, primaveraTitles.overlap).locator('.p6-activity-bar').boundingBox()
  expect(Math.abs(summary.x - activity.x)).toBeLessThan(2)
  expect(Math.abs(summary.width - activity.width)).toBeLessThan(2)
  clean(state)
})

test('nested collapse and search preserve row alignment and never merge same-discipline WBS branches', async ({ page }) => {
  const state = await open(page)
  await row(page, 1110).getByRole('button', { name: 'Collapse RAD-210.1.1 FEED', exact: true }).click()
  await expect(row(page, 1111)).toHaveCount(0)
  await expect(row(page, 1112)).toHaveCount(0)
  await expect(taskRow(page, primaveraTitles.overlap)).toHaveCount(0)
  await expect(taskRow(page, primaveraTitles.detailed)).toHaveCount(1)
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(36)
  await aligned(page)
  await row(page, 1110).getByRole('button', { name: 'Expand RAD-210.1.1 FEED', exact: true }).click()
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(44)
  const search = workspace(page).getByRole('textbox', { name: 'Search schedule activities' })
  await search.fill('P&ID - Amine')
  await expect(grid(page).locator('.sc-task-name')).toHaveText([primaveraTitles.detailed])
  for (const id of [1000, 1100, 1120, 1121]) await expect(row(page, id)).toHaveCount(1)
  await expect(row(page, 1111)).toHaveCount(0)
  await aligned(page)
  await expect(cell(taskRow(page, primaveraTitles.detailed), 'activity-code')).toHaveText('DE-PRO-010')
  await search.fill('Detailed Engineering')
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(26)
  for (const id of [1000, 1100, 1120, 1121, 1122, 1123, 1124]) await expect(row(page, id)).toHaveCount(1)
  await expect(row(page, 1110)).toHaveCount(0)
  await aligned(page)
  await search.clear()
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(44)
  await scheduleDiscipline(page, 'process')
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(10)
  await expect(row(page, 1111)).toHaveCount(1)
  await expect(row(page, 1121)).toHaveCount(1)
  await aligned(page)
  await scheduleDiscipline(page, 'all')
  await scheduleCritical(page, true)
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(14)
  await expect(taskRow(page, primaveraTitles.unknown)).toHaveCount(0)
  await aligned(page)
  clean(state)
})

test('timeline scales, independent horizontal scroll and keyboard/pointer divider work together', async ({ page }) => {
  const state = await open(page)
  const bar = taskRow(page, primaveraTitles.overlap).locator('.p6-activity-bar')
  const week = await bar.boundingBox()
  await timelineScale(page, 'day')
  const day = await bar.boundingBox()
  expect(day.width).toBeGreaterThan(week.width)
  await timelineScale(page, 'month')
  const month = await bar.boundingBox()
  expect(month.width).toBeLessThan(week.width)
  await expect(workspace(page).getByRole('button', { name: 'Zoom out', exact: true })).toBeDisabled()
  await workspace(page).getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(workspace(page).getByRole('combobox', { name: 'Timeline scale', exact: true })).toHaveValue('week')
  await workspace(page).getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(workspace(page).getByRole('button', { name: 'Zoom in', exact: true })).toBeDisabled()
  await expect(workspace(page).getByRole('combobox', { name: 'Timeline scale', exact: true })).toHaveValue('day')
  await workspace(page).getByRole('button', { name: 'Zoom out', exact: true }).click()
  await timelineScale(page, 'week')
  const divider = grid(page).getByRole('separator', { name: 'Resize activity table and Gantt', exact: true })
  await expect(divider).toHaveAttribute('aria-orientation', 'vertical')
  const initial = await divider.boundingBox()
  await divider.focus()
  await page.keyboard.press('ArrowRight')
  expect((await divider.boundingBox()).x).toBeCloseTo(initial.x + 20, 0)
  await page.keyboard.press('ArrowLeft')
  expect((await divider.boundingBox()).x).toBeCloseTo(initial.x, 0)
  await page.mouse.move(initial.x + initial.width / 2, initial.y + 30)
  await page.mouse.down()
  await page.mouse.move(initial.x - 100, initial.y + 30, { steps: 5 })
  await page.mouse.up()
  expect((await divider.boundingBox()).x).toBeLessThan(initial.x - 70)
  const taskTitles = await grid(page).locator('.sc-task-name').allTextContents()
  const ganttScroll = grid(page).getByLabel('Scroll Gantt timeline', { exact: true })
  await ganttScroll.evaluate(element => { element.scrollLeft = 200; element.dispatchEvent(new Event('scroll')) })
  expect(await ganttScroll.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
  expect(await grid(page).locator('.sc-task-name').allTextContents()).toEqual(taskTitles)
  await divider.focus()
  await page.keyboard.press('End')
  await expect(divider).toHaveAttribute('aria-valuenow', await divider.getAttribute('aria-valuemax'))
  await page.keyboard.press('Home')
  await expect(divider).toHaveAttribute('aria-valuenow', await divider.getAttribute('aria-valuemin'))
  const tableScroll = grid(page).getByLabel('Scroll activity columns', { exact: true })
  await tableScroll.evaluate(element => { element.scrollLeft = 100; element.dispatchEvent(new Event('scroll')) })
  expect(await tableScroll.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
  await aligned(page)
  expect((await page.locator('.performance-test-shell').boundingBox()).x).toBe(198)
  await expect(workspace(page).getByRole('button', { name: 'Today', exact: true })).toBeDisabled()
  await page.clock.setFixedTime(new Date('2026-10-20T06:30:00Z'))
  await timelineScale(page, 'day')
  await workspace(page).getByRole('button', { name: 'Today', exact: true }).click()
  const today = await grid(page).locator('.p6-today-line').first().boundingBox()
  const timelinePane = await grid(page).locator('.p6-heading .p6-right-clip').boundingBox()
  expect(today.x).toBeGreaterThanOrEqual(timelinePane.x)
  expect(today.x).toBeLessThan(timelinePane.x + timelinePane.width)
  clean(state)
})

test('activity details retain employee progress history and mobile keyboard access', async ({ page }) => {
  const state = await open(page)
  await grid(page).getByRole('button', { name: primaveraTitles.overlap, exact: true }).click()
  const drawer = page.getByRole('complementary', { name: 'Activity details', exact: true })
  await expect(drawer).toBeVisible()
  await expect(drawer.getByRole('tab', { name: 'Details', exact: true })).toHaveAttribute('aria-selected', 'true')
  await drawer.getByRole('tab', { name: 'Logic', exact: true }).click()
  await expect(drawer.getByRole('tabpanel')).toContainText('No predecessors recorded')
  await expect(drawer.getByRole('button', { name: 'Edit relationships', exact: true })).toBeEnabled()
  await drawer.getByRole('tab', { name: 'Resources', exact: true }).click()
  await expect(drawer.getByRole('tabpanel')).toContainText('Planned effort')
  await expect(drawer.getByRole('button', { name: 'View activity for Omar Saleh', exact: true })).toBeVisible()
  await drawer.getByRole('tab', { name: 'History', exact: true }).click()
  await expect(drawer.getByRole('tabpanel')).toContainText('Approved MDR.csv')
  await page.keyboard.press('Home')
  await expect(drawer.getByRole('tab', { name: 'Details', exact: true })).toBeFocused()
  await expect(drawer.getByRole('tab', { name: 'Details', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: '../artifacts/light-schedule-inspector-desktop.png', animations: 'disabled' })
  await drawer.getByRole('button', { name: 'View activity for Omar Saleh', exact: true }).click()
  const history = page.getByRole('dialog', { name: 'Employee activity', exact: true })
  await expect(history).toBeVisible()
  await expect(history.getByRole('heading', { name: /^Activity history/ })).toBeVisible()
  await expect(history.getByRole('heading', { name: 'Progress updated', exact: true })).toBeVisible()
  await expect(history.getByRole('progressbar', { name: `${primaveraTitles.overlap} progress`, exact: true })).toHaveAttribute('value', '45')
  await expect(history.locator('.pea-task-facts > div').filter({ has: page.getByText('Assigned by', { exact: true }) })).toContainText('Maya Hassan')
  await expect(history.getByRole('button', { name: 'Save task', exact: true })).toHaveCount(0)
  await history.getByRole('button', { name: 'Close employee activity', exact: true }).click()
  await drawer.getByRole('button', { name: 'Close activity details', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  const title = grid(page).getByRole('button', { name: primaveraTitles.overlap, exact: true })
  await title.focus()
  await page.keyboard.press('Enter')
  await expect(drawer).toBeVisible()
  const box = await drawer.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(391)
  await page.keyboard.press('Escape')
  await expect(drawer).toHaveCount(0)
  await expect(title).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const results = await new AxeBuilder({ page }).include('.schedule-canvas').analyze()
  expect(results.violations.filter(violation => ['serious', 'critical'].includes(violation.impact))).toEqual([])
  clean(state)
})
