import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { projectLinksHarness } from '../fixtures/project-links.fixture'
import { orderFormNumber, orderFormRecommendation } from '../fixtures/purchase-order-form.fixture'

test.setTimeout(120000)
test.use({ serviceWorkers: 'block', viewport: { width: 1672, height: 941 } })
const projects = page => page.getByRole('region', { name: 'Projects', exact: true })
const orders = page => page.getByRole('region', { name: 'Purchase orders', exact: true })
const project = (page, code = '5900985') => projects(page).getByRole('button').filter({ hasText: code })
const connect = page => page.getByRole('button', { name: 'Connect PO to project', exact: true })
const selectPO = (page, number = 'PO-2026-0048') => orders(page).getByRole('button', { name: `Select ${number}`, exact: true }).click()
const open = async (page, options) => {
  const state = await projectLinksHarness(page, options)
  await expect(page.getByRole('heading', { name: 'Project Links', exact: true })).toBeVisible()
  await expect(project(page)).toBeVisible()
  return state
}
const checkClean = state => { expect(state.unknown).toEqual([]); expect(state.pageErrors).toEqual([]) }
const writes = state => state.requests.filter(row => ['POST', 'PATCH', 'PUT', 'DELETE'].includes(row.method) && row.path.includes('/procurement/'))

test('simple split workspace lists every server project folder and selection is read-only', async ({ page }) => {
  const state = await open(page)
  await expect(projects(page).getByRole('button')).toHaveCount(54)
  await expect(connect(page)).toBeDisabled()
  await project(page).click()
  await selectPO(page)
  await expect(connect(page)).toBeEnabled()
  await expect(page.getByRole('checkbox', { name: /reviewed/ })).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: /Reason/ })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Advanced reconciliation' })).toHaveAttribute('href', '/procurement/projects/reconciliation/advanced')
  const left = await projects(page).boundingBox(), right = await orders(page).boundingBox()
  expect(left.x + left.width).toBeLessThan(right.x)
  const button = await connect(page).boundingBox()
  expect(button.y + button.height).toBeLessThan(942)
  expect(writes(state)).toEqual([])
  await page.screenshot({ path: '../artifacts/project-links-desktop.png', fullPage: true })
  const a11y = await new AxeBuilder({ page }).include('.project-links-workspace').analyze()
  expect(a11y.violations).toEqual([])
  checkClean(state)
})

test('explicit Connect saves only the selected PO and folder with both current project guards', async ({ page }) => {
  const state = await open(page)
  const before = state.linkOrders.map(({ id, po_number, total_amount, currency }) => ({ id, po_number, total_amount, currency }))
  await project(page).click(); await selectPO(page); await connect(page).click()
  await expect(page.locator('.plw-success[role="status"]')).toContainText('PO-2026-0048 is connected')
  expect(state.connections).toEqual([{ scope_id: 'folder-17', order_id: 'order-1', expected_project_id: null, expected_folder_project_id: '17' }])
  expect(state.preparations).toEqual([])
  expect(state.linkOrders.map(({ id, po_number, total_amount, currency }) => ({ id, po_number, total_amount, currency }))).toEqual(before)
  await expect(orders(page).getByRole('button', { name: "Selected project's POs", exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Connected', exact: true })).toBeDisabled()
  checkClean(state)
})

test('unprepared folders are listed immediately and only explicit Connect prepares their project', async ({ page }) => {
  const state = await open(page)
  await project(page, '5900738').click()
  expect(state.folderProjects.find(row => row.scope_id === 'folder-new').project_id).toBeNull()
  expect(writes(state)).toEqual([])
  await selectPO(page); await connect(page).click()
  await expect(page.locator('.plw-success[role="status"]')).toContainText('EPCM-Grid Power Integration Project')
  expect(state.connections).toEqual([{ scope_id: 'folder-new', order_id: 'order-1', expected_project_id: null, expected_folder_project_id: null }])
  expect(state.preparations).toEqual([])
  await expect(orders(page).getByRole('button', { name: 'Select PO-2026-0048' })).toBeVisible()
  checkClean(state)
})

test('project search and PO filters/search clear selection and query the server', async ({ page }) => {
  const state = await open(page)
  await project(page).click(); await selectPO(page)
  await orders(page).getByRole('button', { name: 'All POs', exact: true }).click()
  await expect(connect(page)).toBeDisabled()
  await selectPO(page, 'PO-2026-0049')
  await expect(page.getByText('This changes the PO connection from 5901142 to 5900985.')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search purchase orders' }).fill('Petroserve')
  await expect(orders(page).getByRole('button', { name: /^Select PO-/ })).toHaveCount(1)
  await expect(connect(page)).toBeDisabled()
  expect(state.workspaceQueries.at(-1).search).toBe('Petroserve')
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('5900738')
  await expect(projects(page).getByRole('button')).toHaveCount(1)
  await project(page, '5900738').click()
  await expect(connect(page)).toBeDisabled()
  expect(writes(state)).toEqual([])
  checkClean(state)
})

test('stale identity errors preserve choices but require an explicit refresh before retry', async ({ page }) => {
  const state = await open(page, { prepare: state => { state.connectError = { status: 400, body: { expected_project_id: ['The purchase order project changed. Refresh before retrying.'] } } } })
  await project(page).click(); await selectPO(page); await connect(page).click()
  await expect(page.getByRole('alert')).toContainText('The purchase order project changed')
  await expect(connect(page)).toBeDisabled()
  await expect(project(page)).toHaveAttribute('aria-pressed', 'true')
  state.connectError = null
  await page.getByRole('button', { name: 'Refresh records' }).click()
  await expect(connect(page)).toBeEnabled()
  expect(state.connections).toHaveLength(1)
  checkClean(state)
})

test('server capabilities control writes while folders and orders remain available', async ({ page }) => {
  const state = await open(page, { prepare: state => { state.permissions = { can_connect: false, can_create_po: false } } })
  await project(page).click(); await selectPO(page)
  await expect(connect(page)).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Create PO', exact: true })).toBeDisabled()
  await expect(page.getByText('Procurement update access is required to connect orders.')).toBeVisible()
  expect(writes(state)).toEqual([])
  checkClean(state)
})

test('Create PO validates the selected folder on click and preserves its project through a matching PR', async ({ page }) => {
  const state = await open(page)
  await project(page).click()
  expect(writes(state)).toEqual([])
  await page.getByRole('button', { name: 'Create PO', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'New purchase order', exact: true })).toBeVisible()
  expect(state.preparations).toEqual([{ scope_id: 'folder-17', expected_folder_project_id: '17' }])
  await expect(page.locator('#po-project-search')).toHaveValue(/5900985/)
  await page.locator('#po-pr-search').fill('9001')
  await page.getByRole('option', { name: new RegExp(orderFormRecommendation.pr_number) }).click()
  await expect(page.getByLabel('PO Number', { exact: true })).toHaveValue(orderFormNumber)
  await expect(page.locator('#po-project-search')).toHaveValue(/5900985/)
  expect(state.requests.filter(row => row.path.endsWith('/create-project/'))).toEqual([])
  await page.getByRole('combobox', { name: 'Price basis', exact: true }).selectOption('exclusive')
  await page.locator('.purchase-order-form-workspace').getByRole('button', { name: /^Save draft$/i }).first().click()
  await expect(page.getByRole('heading', { name: 'New purchase order', exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(/\/procurement\/projects\/reconciliation$/)
  expect(state.acceptedWrites).toHaveLength(1)
  expect(state.record).toMatchObject({ enterprise_project: '17', project_number: '5900985', pr_reference: orderFormRecommendation.id })
  checkClean(state)
})

test('Create PO on an unprepared folder creates the project only after the explicit click', async ({ page }) => {
  const state = await open(page)
  await project(page, '5900738').click()
  expect(writes(state)).toEqual([])
  await page.getByRole('button', { name: 'Create PO', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'New purchase order', exact: true })).toBeVisible()
  expect(state.preparations).toEqual([{ scope_id: 'folder-new', expected_folder_project_id: null }])
  await expect(page.locator('#po-project-search')).toHaveValue(/5900738/)
  expect(state.connections).toEqual([])
  checkClean(state)
})

test('mobile keeps both lists usable without horizontal page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const state = await open(page)
  await project(page).click(); await selectPO(page)
  await expect(connect(page)).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await connect(page).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '../artifacts/project-links-mobile.png' })
  checkClean(state)
})
