import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { reconciliationHarness, reconciliationRows } from '../fixtures/project-reconciliation.fixture.js'

test.setTimeout(90000)
test.use({ serviceWorkers: 'block', viewport: { width: 1672, height: 941 } })
const queue = page => page.getByRole('region', { name: 'Records requiring review', exact: true })
const resolver = page => page.getByRole('region', { name: 'Resolve project link', exact: true })
const reviewed = page => page.getByRole('checkbox', { name: 'I reviewed the source and target project', exact: true })
const review = async (page, identifier = 'PR-2026-1043') => {
  await queue(page).getByRole('button', { name: `Review ${identifier}`, exact: true }).click()
  await expect(queue(page).getByRole('button', { name: `Review ${identifier}`, exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(resolver(page)).toContainText(identifier)
}
const chooseSuggested = page => page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true }).check()
const financialSnapshot = state => state.sources.map(({ id, record_type, amount, currency, reference }) => ({ id, record_type, amount, currency, reference }))
const writes = state => state.requests.filter(request => ['POST', 'PATCH', 'PUT', 'DELETE'].includes(request.method)
  && /^\/api\/v1\/(procurement|project-control)\//.test(request.path))
const metric = (page, label) => page.getByRole('article').filter({ has: page.getByRole('heading', { name: label, exact: true }) })
const clean = state => { expect(state.unknown).toEqual([]); expect(state.pageErrors).toEqual([]) }
const open = async (page, options) => {
  const state = await reconciliationHarness(page, options)
  await expect(page.getByRole('heading', { name: 'Project Reconciliation', exact: true })).toBeVisible()
  return state
}
const desktopActionsFit = async page => {
  const main = await page.locator('#application-content > main.main-content').boundingBox()
  const appFooter = await page.locator('#application-content > footer').boundingBox()
  const queueFooter = await page.locator('.pcr-queue-footer').boundingBox()
  const confirm = await page.getByRole('button', { name: 'Confirm project link', exact: true }).boundingBox()
  const heading = await page.getByRole('heading', { name: 'Project Reconciliation', exact: true }).boundingBox()
  expect(queueFooter.y + queueFooter.height).toBeLessThanOrEqual(main.y + main.height + 1)
  expect(confirm.y + confirm.height).toBeLessThanOrEqual(main.y + main.height + 1)
  expect(main.y + main.height).toBeLessThanOrEqual(appFooter.y + 1)
  expect(heading.y).toBeGreaterThanOrEqual(main.y)
}

test('real application shell presents a review queue, evidence and currency-separated exposure', async ({ page }) => {
  const state = await open(page)
  await review(page)
  await expect(page.locator('#application-sidebar')).toBeVisible()
  await expect(queue(page)).toBeVisible()
  await expect(resolver(page)).toBeVisible()
  for (const heading of ['Review source record', 'Choose target project', 'Review impact and confirm']) await expect(resolver(page).getByRole('heading', { name: heading, exact: true })).toBeVisible()
  await expect(page.locator('.pcr-guide')).not.toHaveAttribute('open', '')
  await expect(resolver(page).getByRole('link', { name: 'Open source record', exact: true })).toHaveAttribute('href', '/procurement/requisitions/pr-001')
  await expect(metric(page, 'Safely linked')).toContainText('0')
  await expect(metric(page, 'Safely linked')).toContainText('This session')
  await expect(metric(page, 'Financial value affected')).toHaveAttribute('title', 'AED 190,750 + USD 2,750')
  await expect(resolver(page)).toContainText('Project code appears in the legacy reference.')
  await expect(page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true })).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeDisabled()
  expect(await resolver(page).textContent()).not.toMatch(/\d+(?:\.\d+)?\s*%/)
  const left = await queue(page).boundingBox(), right = await resolver(page).boundingBox()
  expect(left.x + left.width).toBeLessThanOrEqual(right.x + 2)
  await desktopActionsFit(page)
  await page.screenshot({ path: '../artifacts/project-reconciliation-desktop-1672.png', fullPage: true })
  expect(writes(state)).toEqual([])
  clean(state)
})

test('record filters and sorting keep exceptions reachable and combine without writes', async ({ page }) => {
  const state = await open(page)
  await page.getByRole('combobox', { name: 'Record type', exact: true }).selectOption('purchase_requisition')
  await page.getByRole('combobox', { name: 'Issue', exact: true }).selectOption('no_exact_match')
  await page.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('AED')
  await page.getByRole('textbox', { name: 'Search records', exact: true }).fill('revision a')
  await expect(queue(page).getByRole('button', { name: /^Review / })).toHaveCount(1)
  await expect(queue(page).getByRole('button', { name: 'Review PR-2026-1043', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search records', exact: true }).fill('')
  await page.getByRole('combobox', { name: 'Review status', exact: true }).selectOption('exceptions')
  await page.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('USD')
  await expect(queue(page).getByRole('button', { name: 'Review PR-2026-1044', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Review status', exact: true }).selectOption('all')
  await page.getByRole('combobox', { name: 'Record type', exact: true }).selectOption('')
  await page.getByRole('combobox', { name: 'Issue', exact: true }).selectOption('')
  await page.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('')
  await page.getByRole('combobox', { name: 'Sort records', exact: true }).selectOption('newest')
  await expect(queue(page).getByRole('button', { name: /^Review / }).first()).toHaveAccessibleName('Review PO-2026-0087')
  expect(writes(state)).toEqual([])
  clean(state)
})

test('confirmed whole-record link sends an optimistic identity guard without financial edits', async ({ page }) => {
  const state = await open(page)
  const before = financialSnapshot(state)
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('other')
  await page.getByRole('textbox', { name: 'Review reason', exact: true }).fill('Checked the signed engineering package and project register.')
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeDisabled()
  await reviewed(page).check()
  await page.getByRole('switch', { name: 'Move to next after confirmation', exact: true }).check()
  await page.getByRole('button', { name: 'Confirm project link', exact: true }).click()
  await expect.poll(() => state.resolutions.length).toBe(1)
  expect(state.resolutions[0]).toEqual({ record_type: 'purchase_requisition', record_id: 'pr-001', enterprise_project_id: '17', expected_project_id: null, reason: expect.stringContaining('Checked the signed engineering package and project register.') })
  await expect(queue(page).getByRole('button', { name: 'Review PR-2026-1043', exact: true })).toHaveCount(0)
  await expect(metric(page, 'Safely linked').locator('strong')).toHaveText('1')
  expect(financialSnapshot(state)).toEqual(before)
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/procurement/projects/resolve-relationship/'])
  clean(state)
})

test('search includes unsuggested projects and skip advances without persisting a draft selection', async ({ page }) => {
  const state = await open(page)
  await review(page)
  await page.getByRole('textbox', { name: 'Search projects', exact: true }).fill('Grid Operations')
  const project = page.getByRole('radio', { name: 'Project 5900033 Grid Power Integration', exact: true })
  await expect(project).toBeVisible()
  await project.check()
  await page.getByRole('button', { name: 'Skip for now', exact: true }).click()
  await expect(resolver(page)).not.toContainText('PR-2026-1043')
  await expect(queue(page).getByRole('button', { name: 'Review PR-2026-1043', exact: true })).toBeVisible()
  expect(writes(state)).toEqual([])
  clean(state)
})

test('stale link failure retains the selected source, project and review evidence', async ({ page }) => {
  const message = 'The record was linked by another reviewer. Refresh before retrying.'
  const state = await open(page, { prepare: state => { state.saveError = { status: 409, body: { detail: message } } } })
  const before = financialSnapshot(state)
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('other')
  await page.getByRole('textbox', { name: 'Review reason', exact: true }).fill('Verified source revision A.')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Confirm project link', exact: true }).click()
  await expect(page.getByText(message, { exact: true }).first()).toBeVisible()
  await expect(resolver(page)).toContainText('PR-2026-1043')
  await expect(page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true })).toBeChecked()
  await expect(page.getByRole('textbox', { name: 'Review reason', exact: true })).toHaveValue('Verified source revision A.')
  expect(financialSnapshot(state)).toEqual(before)
  expect(state.report.unresolved.some(row => row.id === 'pr-001')).toBe(true)
  clean(state)
})

test('save as exception records a reason and exposes it through exception review and audit', async ({ page }) => {
  const state = await open(page)
  const before = financialSnapshot(state)
  await review(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('other')
  await page.getByRole('textbox', { name: 'Review reason', exact: true }).fill('Project owner must confirm the mixed legacy references.')
  await page.getByRole('button', { name: 'Save as exception', exact: true }).click()
  await expect.poll(() => state.exceptions.length).toBe(1)
  expect(state.exceptions[0]).toEqual({ record_type: 'purchase_requisition', record_id: 'pr-001', reason: expect.stringContaining('Project owner must confirm the mixed legacy references.') })
  expect(state.resolutions).toEqual([])
  expect(financialSnapshot(state)).toEqual(before)
  await expect(metric(page, 'Safely linked').locator('strong')).toHaveText('0')
  await page.getByRole('combobox', { name: 'Review status', exact: true }).selectOption('exceptions')
  await review(page)
  await expect(resolver(page)).toContainText('Project owner must confirm the mixed legacy references.')
  await page.getByRole('button', { name: 'View audit log', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Project owner must confirm the mixed legacy references.')
  await expect(page.getByRole('dialog')).toContainText('Maya Hassan')
  clean(state)
})

test('WBS split saves a draft for independent approval and never approves or links the source', async ({ page }) => {
  const state = await open(page)
  const before = financialSnapshot(state)
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('radio', { name: 'Allocate cost to WBS', exact: true }).check()
  await page.getByRole('combobox', { name: 'Target WBS', exact: true }).selectOption('201')
  await expect(page.getByRole('combobox', { name: 'Approved budget', exact: true }).getByRole('option', { name: /Unapproved allowance/ })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Approved budget', exact: true }).selectOption('301')
  await page.getByRole('spinbutton', { name: 'Allocation amount', exact: true }).fill('25000.00')
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('source')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Save allocation for approval', exact: true }).click()
  await expect.poll(() => state.allocations.length).toBe(1)
  expect(state.allocations[0]).toMatchObject({ project: '17', wbs_node: '201', budget_allocation: '301', source_type: 'purchase_requisition', source_id: 'pr-001', amount: '25000.00', status: 'draft' })
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/project-control/cost-allocations/'])
  expect(state.resolutions).toEqual([])
  expect(state.report.unresolved.some(row => row.id === 'pr-001')).toBe(true)
  await expect(metric(page, 'Safely linked').locator('strong')).toHaveText('0')
  expect(financialSnapshot(state)).toEqual(before)
  await expect(page.getByText('Allocation saved for independent approval', { exact: false }).first()).toBeVisible()
  clean(state)
})

test('invoice reconciliation uses the PO matching service without direct project assignment', async ({ page }) => {
  const state = await open(page)
  await review(page, 'INV-2026-0331')
  await page.getByRole('combobox', { name: 'Purchase order', exact: true }).selectOption('canonical-po-032')
  await page.getByRole('spinbutton', { name: 'Invoice allocation amount', exact: true }).fill('15750.00')
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('source')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Confirm PO match', exact: true }).click()
  await expect.poll(() => state.invoiceMatches.length).toBe(1)
  expect(state.invoiceMatches[0]).toEqual({ invoice_id: 'invoice-001', purchase_order_id: 'canonical-po-032', allocated_amount: '15750.00', reason: expect.stringContaining('Verified against source document') })
  expect(state.resolutions).toEqual([])
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/procurement/projects/resolve-invoice-po/'])
  clean(state)
})

test('loading and recoverable report failure offer a retry without enabling mutations', async ({ page }) => {
  const state = await open(page, { prepare: state => { state.holdReport = true; state.reportError = { message: 'The reconciliation service is temporarily unavailable.' } } })
  await expect(page.getByText(/Loading reconciliation/)).toBeVisible()
  expect(writes(state)).toEqual([])
  state.releaseReport()
  await expect(page.getByText('The reconciliation service is temporarily unavailable.', { exact: true })).toBeVisible()
  state.reportError = null
  await page.getByRole('button', { name: /Try again|Retry report/, exact: true }).click()
  await review(page)
  expect(writes(state)).toEqual([])
  clean(state)
})

test('an empty report shows a useful complete state without a link action', async ({ page }) => {
  const state = await open(page, { rows: [] })
  await expect(page.getByRole('heading', { name: 'All project links are up to date', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toHaveCount(0)
  expect(writes(state)).toEqual([])
  clean(state)
})

test('mobile and dark review keep controls reachable without horizontal page overflow', async ({ page }) => {
  const state = await open(page, { theme: 'dark' })
  await review(page)
  await desktopActionsFit(page)
  await page.screenshot({ path: '../artifacts/project-reconciliation-dark-1672.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await review(page)
  const main = page.locator('#application-content > main.main-content')
  await expect.poll(() => main.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  expect((await page.locator('#application-content > header').boundingBox()).y).toBe(0)
  await expect(resolver(page).getByRole('link', { name: 'Open source record', exact: true })).toHaveAttribute('href', '/procurement/requisitions/pr-001')
  await expect(page.getByRole('textbox', { name: 'Search projects', exact: true })).toBeVisible()
  await chooseSuggested(page)
  await expect(page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true })).toBeChecked()
  await main.evaluate(element => element.scrollTo({ top: element.scrollHeight, behavior: 'instant' }))
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => window.scrollY)).toBe(0)
  const widths = await page.evaluate(() => ({ viewport: innerWidth, content: document.documentElement.scrollWidth }))
  expect(widths.content).toBeLessThanOrEqual(widths.viewport + 1)
  await page.screenshot({ path: '../artifacts/project-reconciliation-mobile-390.png' })
  const audit = await new AxeBuilder({ page }).include('[aria-label="Resolve project link"]').analyze()
  expect(audit.violations.filter(violation => ['critical', 'serious'].includes(violation.impact))).toEqual([])
  expect(writes(state)).toEqual([])
  clean(state)
})

test('previous and next navigation do not mutate sources or keep stale form selections', async ({ page }) => {
  const state = await open(page, { rows: reconciliationRows.slice(0, 2) })
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('button', { name: 'Next record', exact: true }).click()
  await expect(resolver(page)).toContainText('PO-2026-0087')
  await page.getByRole('button', { name: 'Previous record', exact: true }).click()
  await expect(resolver(page)).toContainText('PR-2026-1043')
  await expect(page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true })).not.toBeChecked()
  expect(writes(state)).toEqual([])
  clean(state)
})

test('turning off move-next keeps the next record unselected after a successful link', async ({ page }) => {
  const state = await open(page, { rows: reconciliationRows.slice(0, 2) })
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('code')
  await reviewed(page).check()
  await page.getByRole('switch', { name: 'Move to next after confirmation', exact: true }).uncheck()
  await page.getByRole('button', { name: 'Confirm project link', exact: true }).click()
  await expect.poll(() => state.resolutions.length).toBe(1)
  await expect(resolver(page).getByRole('heading', { name: 'Choose a record to review', exact: true })).toBeVisible()
  await expect(queue(page).getByRole('button', { name: 'Review PO-2026-0087', exact: true })).toBeVisible()
  await expect(metric(page, 'Safely linked').locator('strong')).toHaveText('1')
  clean(state)
})

test('allocation-only access can save a WBS draft but cannot link or save a relationship exception', async ({ page }) => {
  const state = await open(page, { actor: { is_superuser: false, module_actions: { procurement: ['read'], project_control: ['read', 'create'] } } })
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('source')
  await reviewed(page).check()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Save as exception', exact: true })).toBeDisabled()
  await page.getByRole('radio', { name: 'Allocate cost to WBS', exact: true }).check()
  await page.getByRole('combobox', { name: 'Target WBS', exact: true }).selectOption('201')
  await page.getByRole('spinbutton', { name: 'Allocation amount', exact: true }).fill('1000.00')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Save allocation for approval', exact: true }).click()
  await expect.poll(() => state.allocations.length).toBe(1)
  expect(state.resolutions).toEqual([])
  expect(state.exceptions).toEqual([])
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/project-control/cost-allocations/'])
  clean(state)
})

test('WBS currency mismatch cannot be silently converted into an allocation', async ({ page }) => {
  const state = await open(page)
  await review(page)
  await page.getByRole('textbox', { name: 'Search projects', exact: true }).fill('5900033')
  await page.getByRole('radio', { name: 'Project 5900033 Grid Power Integration', exact: true }).check()
  await page.getByRole('radio', { name: 'Allocate cost to WBS', exact: true }).check()
  await page.getByRole('combobox', { name: 'Target WBS', exact: true }).selectOption('201')
  await page.getByRole('spinbutton', { name: 'Allocation amount', exact: true }).fill('1000.00')
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('source')
  await reviewed(page).check()
  await expect(resolver(page)).toContainText('The project uses USD; the source uses AED.')
  await expect(page.getByRole('button', { name: 'Save allocation for approval', exact: true })).toBeDisabled()
  expect(writes(state)).toEqual([])
  clean(state)
})

test('All projects and search expose choices beyond twelve without inventing suggestion evidence', async ({ page }) => {
  const additional = Array.from({ length: 18 }, (_, index) => ({ id: `extra-${index + 1}`, code: `8800${String(index + 1).padStart(2, '0')}`, name: `Register extension ${index + 1}`, client_name: 'Additional client', status: 'active', currency: 'AED' }))
  const state = await open(page, { prepare: state => { state.report.canonical_projects.push(...additional) } })
  await review(page)
  const reportCalls = () => state.requests.filter(request => request.path.endsWith('/relationship-report/')).length
  const initialCalls = reportCalls()
  await expect(resolver(page).getByRole('radio', { name: /^Project / })).toHaveCount(2)
  await page.getByRole('button', { name: /^All projects/ }).click()
  await expect(resolver(page).getByRole('radio', { name: /^Project / })).toHaveCount(6)
  await page.getByRole('button', { name: /^Show more projects/ }).click()
  await expect(resolver(page).getByRole('radio', { name: /^Project / })).toHaveCount(12)
  await page.getByRole('button', { name: /^Show more projects/ }).click()
  await expect(resolver(page).getByRole('radio', { name: /^Project / })).toHaveCount(18)
  const target = additional.at(-1)
  await page.getByRole('textbox', { name: 'Search projects', exact: true }).fill(target.code)
  const result = page.getByRole('radio', { name: `Project ${target.code} ${target.name}`, exact: true })
  await expect(result).toBeVisible()
  await expect(result).not.toBeChecked()
  expect(reportCalls()).toBe(initialCalls)
  await result.check()
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('code')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Confirm project link', exact: true }).click()
  await expect.poll(() => state.resolutions.length).toBe(1)
  expect(state.resolutions[0]).toMatchObject({ record_id: 'pr-001', enterprise_project_id: target.id, expected_project_id: null })
  clean(state)
})

test('an exact-code candidate stays in the review queue and requires an explicit project and reviewed confirmation', async ({ page }) => {
  const state = await open(page, { prepare: state => {
    state.report.unresolved[0].reason = 'exact_match_available'
    state.report.unresolved[0].reference = '5900985'
  } })
  await page.getByRole('combobox', { name: 'Issue', exact: true }).selectOption('exact_match_available')
  await review(page)
  await expect(queue(page)).toContainText('Exact code ready for review')
  await expect(page.getByRole('radio', { name: 'Project 5900985 PE4 Compression Upgrade', exact: true })).not.toBeChecked()
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('code')
  await reviewed(page).check()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeDisabled()
  await chooseSuggested(page)
  await expect(reviewed(page)).not.toBeChecked()
  await reviewed(page).check()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeEnabled()
  expect(writes(state)).toEqual([])
  clean(state)
})

test('refreshing a changed source project invalidates reviewed confirmation before saving with its new identity', async ({ page }) => {
  const state = await open(page)
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('code')
  await reviewed(page).check()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeEnabled()
  state.report.unresolved[0].current_project = state.report.canonical_projects[1]
  await page.getByRole('button', { name: /Refresh report|Refresh/, exact: true }).click()
  await expect(resolver(page)).toContainText('5901142')
  await expect(reviewed(page)).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Confirm project link', exact: true })).toBeDisabled()
  expect(writes(state)).toEqual([])
  await chooseSuggested(page)
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('code')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Confirm project link', exact: true }).click()
  await expect.poll(() => state.resolutions.length).toBe(1)
  expect(state.resolutions[0].expected_project_id).toBe('18')
  clean(state)
})

test('an optional budget lookup failure keeps WBS draft allocation available without approving or linking', async ({ page }) => {
  const state = await open(page, { prepare: state => { state.budgetError = { detail: 'Budget choices are temporarily unavailable.' } } })
  await review(page)
  await chooseSuggested(page)
  await page.getByRole('radio', { name: 'Allocate cost to WBS', exact: true }).check()
  await page.getByRole('combobox', { name: 'Target WBS', exact: true }).selectOption('201')
  await expect(resolver(page)).toContainText('Optional budget lines could not be loaded. You can still save a WBS allocation without a budget line.')
  await page.getByRole('spinbutton', { name: 'Allocation amount', exact: true }).fill('1000.00')
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('source')
  await reviewed(page).check()
  await page.getByRole('button', { name: 'Save allocation for approval', exact: true }).click()
  await expect.poll(() => state.allocations.length).toBe(1)
  expect(state.allocations[0]).toMatchObject({ wbs_node: '201', budget_allocation: null, amount: '1000.00', status: 'draft' })
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/project-control/cost-allocations/'])
  expect(state.resolutions).toEqual([])
  clean(state)
})

test('a fully allocated invoice with exceptions explains its existing PO match and keeps an exception action available', async ({ page }) => {
  const state = await open(page, { prepare: state => {
    const invoice = state.report.unresolved.find(row => row.record_type === 'invoice')
    invoice.reason = 'no_verified_po'
    invoice.invoice_match = { status: 'exceptions', allocated_amount: 15750, remaining_amount: 0, existing_pos: ['PO-2026-0032'], exception_codes: ['receipt_missing'] }
  } })
  await review(page, 'INV-2026-0331')
  await expect(resolver(page)).toContainText('PO-2026-0032')
  await expect(resolver(page)).toContainText(/receipt[ _]missing/i)
  await expect(resolver(page).getByRole('link', { name: 'Open invoice review', exact: true })).toHaveAttribute('href', '/finance/incoming-invoices/invoice-001')
  await expect(page.getByRole('button', { name: 'Confirm PO match', exact: true })).toBeDisabled()
  await page.getByRole('combobox', { name: 'Reason for manual link', exact: true }).selectOption('other')
  await page.getByRole('textbox', { name: 'Review reason', exact: true }).fill('Receiving team must record acceptance against the existing PO match.')
  await page.getByRole('button', { name: 'Save as exception', exact: true }).click()
  await expect.poll(() => state.exceptions.length).toBe(1)
  expect(state.invoiceMatches).toEqual([])
  expect(writes(state).map(request => request.path)).toEqual(['/api/v1/procurement/projects/relationship-exception/'])
  clean(state)
})
