import { test, expect } from '@playwright/test'
import { Buffer } from 'node:buffer'
import { mkdir } from 'node:fs/promises'
import { pairedImportHarness, syntheticApprovedPdf, syntheticPoPdf, pairedPoNumber } from '../fixtures/purchase-recommendation-paired-import.fixture'

test.setTimeout(150000)
test.use({ serviceWorkers: 'block', viewport: { width: 1672, height: 941 } })
const dialog = page => page.getByRole('dialog', { name: 'Upload PR, PO and Vendor', exact: true })
const prFile = page => dialog(page).getByLabel('Select signed or approved PR PDF', { exact: true })
const poFile = page => dialog(page).getByLabel('Select signed or approved PO PDF', { exact: true })
const save = page => dialog(page).getByRole('button', { name: 'Upload PR and PO', exact: true })
const clean = state => { expect(state.unknown).toEqual([]); expect(state.pageErrors).toEqual([]) }
async function open(page) {
  await expect(page.getByRole('heading', { name: 'Purchase Recommendations', exact: true })).toBeVisible({ timeout: 100000 })
  await expect(page.getByRole('complementary', { name: 'Recommendation details' })).toHaveAttribute('aria-busy', 'false')
  await page.getByRole('button', { name: 'More recommendation actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Import signed PDF', exact: true }).click()
  await expect(dialog(page)).toBeVisible()
}
async function previewPair(page) {
  await open(page)
  await prFile(page).setInputFiles(syntheticApprovedPdf)
  await poFile(page).setInputFiles(syntheticPoPdf)
  await dialog(page).getByRole('button', { name: 'Preview OCR', exact: true }).click()
  await expect(dialog(page).getByLabel('PO Number', { exact: true })).toHaveValue(pairedPoNumber)
}
async function sourceUrls(page) {
  const urls = []
  for (const kind of ['PR', 'PO']) {
    await dialog(page).getByRole('tab', { name: `${kind} PDF`, exact: true }).click()
    await expect(dialog(page).getByRole('region', { name: `Approved ${kind} source PDF`, exact: true })
      .getByRole('img', { name: `Approved ${kind} source PDF, page 1 of 1`, exact: true })).toBeVisible({ timeout: 30000 })
    const link = dialog(page).getByRole('link', { name: `Open ${kind} PDF in new tab`, exact: true })
    await expect(link).toHaveAttribute('href', /^blob:/)
    urls.push(await link.getAttribute('href'))
  }
  return urls
}

test('reviews separate source PDFs and saves both linked records with independent PO evidence in one request', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await previewPair(page)
  const prSource = dialog(page).getByRole('region', { name: 'Approved PR source PDF', exact: true })
  const poSource = dialog(page).getByRole('region', { name: 'Approved PO source PDF', exact: true })
  await expect(poSource.getByRole('img', { name: 'Approved PO source PDF, page 1 of 1', exact: true })).toBeVisible({ timeout: 30000 })
  await expect(dialog(page).locator('canvas')).toHaveCount(1)
  await dialog(page).getByRole('tab', { name: 'PR PDF', exact: true }).click()
  await expect(prSource.getByRole('img', { name: 'Approved PR source PDF, page 1 of 1', exact: true })).toBeVisible({ timeout: 30000 })
  const prUrl = await dialog(page).getByRole('link', { name: 'Open PR PDF in new tab', exact: true }).getAttribute('href')
  await dialog(page).getByRole('tab', { name: 'PO PDF', exact: true }).click()
  await expect(poSource.getByRole('img', { name: 'Approved PO source PDF, page 1 of 1', exact: true })).toBeVisible({ timeout: 30000 })
  const urls = [prUrl, await dialog(page).getByRole('link', { name: 'Open PO PDF in new tab', exact: true }).getAttribute('href')]
  expect(urls[0]).not.toEqual(urls[1])
  const texts = await page.evaluate(async sources => Promise.all(sources.map(source => fetch(source.split('#')[0]).then(response => response.text()))), urls)
  expect(texts[0]).toBe(syntheticApprovedPdf.buffer.toString())
  expect(texts[1]).toBe(syntheticPoPdf.buffer.toString())
  await expect(dialog(page).getByLabel('Supplier Name', { exact: true })).toHaveValue('PR Supplier Ltd')
  await expect(dialog(page).getByLabel('PO Supplier name', { exact: true })).toHaveValue('PO Supplier Ltd')
  await expect(dialog(page).getByLabel('PO approval signature is visible', { exact: true })).not.toBeChecked()
  await expect(dialog(page).getByLabel('PO company stamp is visible', { exact: true })).not.toBeChecked()
  await expect(dialog(page).getByLabel('PO Approver name', { exact: true })).toHaveValue('PO Approver Only')
  await dialog(page).getByLabel('Product / Service', { exact: true }).fill('Reviewed PR scope')
  await dialog(page).getByLabel('PO Description', { exact: true }).fill('Reviewed PO scope')
  await expect(dialog(page).getByLabel('Vendor email', { exact: true })).toHaveValue('source@example.test')
  await dialog(page).getByLabel('Vendor contact person', { exact: true }).fill('Reviewed seller contact')
  await dialog(page).getByLabel('Vendor email', { exact: true }).fill('reviewed@example.test')
  await dialog(page).getByLabel('PO approval signature is visible', { exact: true }).check()
  await mkdir('artifacts', { recursive: true })
  await dialog(page).locator('.procurement-import-review__form').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: 'artifacts/paired-pr-po-import-review.png', fullPage: false })
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  expect(state.pairPreviews).toHaveLength(1)
  expect(state.pairSaves).toHaveLength(1)
  expect(state.pairWrites).toHaveLength(1)
  const payload = state.pairSaves[0]
  expect(payload.file).toEqual({ filename: syntheticApprovedPdf.name, content: syntheticApprovedPdf.buffer.toString() })
  expect(payload.po_file).toEqual({ filename: syntheticPoPdf.name, content: syntheticPoPdf.buffer.toString() })
  expect(JSON.parse(payload.manual_overrides)).toMatchObject({ product_service: 'Reviewed PR scope', currency: 'AED' })
  expect(JSON.parse(payload.po_reviewed_fields)).toMatchObject({ summary: 'Reviewed PO scope', currency: 'USD', vendor_name: 'PO Supplier Ltd', seller_contact_person: 'Reviewed seller contact', seller_email: 'reviewed@example.test', vendor_license_no: 'SOURCE-001' })
  expect(JSON.parse(payload.po_reviewed_fields)).not.toHaveProperty('entered_amount')
  expect(payload).toMatchObject({ po_signature_verified: 'true', po_stamp_verified: 'false', po_approved_by_name: 'PO Approver Only', po_approved_date: '2026-09-12' })
  expect(state.requests.filter(request => ['PATCH', 'PUT'].includes(request.method))).toEqual([])
  expect(state.linkRequests).toEqual([])
  clean(state)
})

test('vendor selection and failed lookup keep reviewed contacts and a changed name clears the selected vendor', async ({ page }) => {
  const state = await pairedImportHarness(page)
  let unavailable = false
  await page.route('**/api/v1/procurement/vendors/**', route => route.fulfill({ status: unavailable ? 503 : 200, contentType: 'application/json', body: JSON.stringify(unavailable ? { detail: 'Vendor search unavailable' } : { results: [{ id: '00000000-0000-4000-8000-000000009801', name: 'PO Supplier Ltd', status: 'active' }] }) }))
  await previewPair(page)
  const supplier = dialog(page).getByRole('combobox', { name: 'PO Supplier name', exact: true })
  await dialog(page).getByLabel('Vendor phone', { exact: true }).fill('+971500000001')
  await supplier.click()
  await dialog(page).getByRole('option', { name: 'PO Supplier Ltd', exact: true }).click()
  await expect(dialog(page)).toContainText('Existing vendor selected.')
  unavailable = true
  await supplier.click()
  await expect(dialog(page)).toContainText('Vendor search is unavailable')
  await expect(dialog(page)).toContainText('Existing vendor selected.')
  await save(page).click()
  expect(JSON.parse(state.pairSaves[0].po_reviewed_fields)).toMatchObject({ vendor_id: '00000000-0000-4000-8000-000000009801', seller_phone: '+971500000001' })
  await dialog(page).getByRole('button', { name: 'Close', exact: true }).click()
  await previewPair(page)
  unavailable = false
  await supplier.click()
  await dialog(page).getByRole('option', { name: 'PO Supplier Ltd', exact: true }).click()
  await supplier.fill('Corrected source supplier')
  await expect(dialog(page).getByText('Existing vendor selected.', { exact: true })).toHaveCount(0)
  await save(page).click()
  expect(JSON.parse(state.pairSaves[1].po_reviewed_fields)).toMatchObject({ vendor_id: null, vendor_name: 'Corrected source supplier' })
  clean(state)
})

test('an atomic save failure retains both files, edited mappings and PO evidence for one-request retry', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await previewPair(page)
  await dialog(page).getByLabel('PO Supplier name', { exact: true }).fill('Reviewed new supplier')
  await dialog(page).getByLabel('PO company stamp is visible', { exact: true }).check()
  const sources = await sourceUrls(page)
  expect(sources).toHaveLength(2)
  state.pairError = { status: 400, body: { po_reviewed_fields: ['PO supplier details need review. Nothing was saved.'] } }
  await save(page).click()
  await expect(dialog(page).getByRole('alert')).toContainText('Nothing was saved')
  await expect(dialog(page).getByRole('alert')).toContainText('PO details: PO supplier details need review.')
  await expect(dialog(page).getByLabel('PO Supplier name', { exact: true })).toHaveValue('Reviewed new supplier')
  await expect(dialog(page).getByLabel('PO company stamp is visible', { exact: true })).toBeChecked()
  expect(await sourceUrls(page)).toEqual(sources)
  expect(state.pairWrites).toEqual([])
  state.pairError = null
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  expect(state.pairSaves).toHaveLength(2)
  expect(state.pairSaves[1]).toEqual(state.pairSaves[0])
  expect(state.pairWrites).toHaveLength(1)
  clean(state)
})

test('changing either file clears stale OCR and confirmations while retaining the other selected file', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await previewPair(page)
  await dialog(page).getByLabel('PO Supplier name', { exact: true }).fill('Stale edited supplier')
  await dialog(page).getByLabel('PO approval signature is visible', { exact: true }).check()
  const replacement = { ...syntheticPoPdf, name: 'replacement-po.pdf', buffer: Buffer.from('%PDF-1.4\n% Replacement PO\n%%EOF') }
  await poFile(page).setInputFiles(replacement)
  await expect(save(page)).toHaveCount(0)
  await expect(dialog(page).getByLabel('PO Supplier name', { exact: true })).toHaveCount(0)
  await expect(dialog(page)).toContainText(syntheticApprovedPdf.name)
  await dialog(page).getByRole('button', { name: 'Preview OCR', exact: true }).click()
  await expect(dialog(page).getByLabel('PO Supplier name', { exact: true })).toHaveValue('PO Supplier Ltd')
  await expect(dialog(page).getByLabel('PO approval signature is visible', { exact: true })).not.toBeChecked()
  expect(state.pairPreviews[1].po_file.filename).toBe(replacement.name)
  await prFile(page).setInputFiles({ ...syntheticApprovedPdf, name: 'replacement-pr.pdf' })
  await expect(save(page)).toHaveCount(0)
  await expect(dialog(page)).toContainText(replacement.name)
  expect(state.pairSaves).toEqual([])
  clean(state)
})

test('invalid optional PO preserves selections and removing it restores the unchanged PR-only save', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await open(page)
  await prFile(page).setInputFiles(syntheticApprovedPdf)
  await poFile(page).setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('not a PDF') })
  await dialog(page).getByRole('button', { name: 'Preview OCR', exact: true }).click()
  await expect(dialog(page).getByRole('alert')).toContainText('Purchase Order must be a PDF')
  await expect(dialog(page)).toContainText(syntheticApprovedPdf.name)
  await expect(dialog(page)).toContainText('invalid.txt')
  expect(state.pairPreviews).toEqual([])
  expect(state.previewRequests).toEqual([])
  await dialog(page).getByRole('button', { name: 'Remove PO PDF', exact: true }).click()
  await dialog(page).getByRole('button', { name: 'Preview OCR', exact: true }).click()
  await dialog(page).getByRole('button', { name: 'Upload PR', exact: true }).click()
  await expect(dialog(page)).toContainText('created from the reviewed PDF')
  expect(state.saveRequests).toHaveLength(1)
  expect(state.saveRequests[0]).not.toHaveProperty('po_file')
  expect(state.saveRequests[0]).not.toHaveProperty('po_reviewed_fields')
  clean(state)
})

test('changed PO price requires VAT confirmation while complete independent approval evidence stays intact', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await previewPair(page)
  await dialog(page).getByLabel('PO approval signature is visible', { exact: true }).check()
  await dialog(page).getByLabel('PO Approver name', { exact: true }).fill('Reviewed PO Signer')
  await dialog(page).getByLabel('PO Entered price', { exact: true }).fill('10000')
  await save(page).click()
  await expect(dialog(page).getByRole('alert')).toContainText('Confirm the PO VAT treatment')
  expect(state.pairSaves).toEqual([])
  await dialog(page).getByLabel('PO VAT price basis', { exact: true }).selectOption('none')
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  expect(JSON.parse(state.pairSaves[0].po_reviewed_fields)).toMatchObject({ entered_amount: '10000', vat_basis: 'none' })
  expect(state.pairSaves[0]).toMatchObject({ po_signature_verified: 'true', po_approved_by_name: 'Reviewed PO Signer', po_approved_date: '2026-09-12', approval_date: '2026-09-15' })
  clean(state)
})

for (const existing of [false, true]) test(`incomplete PO approval evidence saves and links in one request when ${existing ? 'attaching to an existing PR' : 'creating PR and PO'}`, async ({ page }) => {
  const warning = 'PO approval evidence needs review: the approver name or approval date is missing.'
  const state = await pairedImportHarness(page, { existing, poEvidence: { approved_by_name: '', approved_date: '' }, poWorkflowIssues: [warning] })
  await previewPair(page)
  const signature = dialog(page).getByLabel('PO approval signature is visible', { exact: true })
  const name = dialog(page).getByLabel('PO Approver name', { exact: true })
  const date = dialog(page).getByLabel('PO Approval date', { exact: true })
  await expect(signature).not.toBeChecked()
  await expect(name).toHaveValue('')
  await expect(date).toHaveValue('')
  await expect(dialog(page).getByLabel('PO Order date', { exact: true })).toHaveValue('2026-09-12')
  await signature.check()
  if (existing) await name.fill('Source PO signer retained')
  else await date.fill('2026-09-12')
  await dialog(page).getByLabel('PO Approver title', { exact: true }).fill('Source title retained')
  const notice = dialog(page).getByRole('status', { name: 'PO approval evidence warning', exact: true })
  await expect(notice).toContainText(existing ? 'Missing PO approval date.' : 'Missing PO approver name.')
  await expect(notice).toContainText('You can save now.')
  await expect(save(page)).toBeEnabled()
  if (existing) {
    await notice.scrollIntoViewIfNeeded()
    await page.screenshot({ path: '../artifacts/po-approval-evidence-warning.png' })
  }
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  await expect(dialog(page)).toContainText(`PO: ${warning}`)
  expect(state.pairSaves).toHaveLength(1)
  expect(state.pairWrites).toHaveLength(1)
  expect(state.pairSaves[0]).toMatchObject({ po_signature_verified: 'true', po_approved_by_title: 'Source title retained', approval_date: '2026-09-15' })
  if (existing) {
    expect(state.pairSaves[0]).toMatchObject({ attach_only: 'true', po_approved_by_name: 'Source PO signer retained' })
    expect(state.pairSaves[0]).not.toHaveProperty('po_approved_date')
  } else {
    expect(state.pairSaves[0]).toMatchObject({ po_approved_date: '2026-09-12' })
    expect(state.pairSaves[0]).not.toHaveProperty('po_approved_by_name')
  }
  expect(state.pairSaves[0].file.filename).toBe(syntheticApprovedPdf.name)
  expect(state.pairSaves[0].po_file.filename).toBe(syntheticPoPdf.name)
  expect(state.requests.filter(request => ['PATCH', 'PUT'].includes(request.method))).toEqual([])
  await expect(page.getByRole('dialog', { name: 'Edit Signed Purchase Order PDF', exact: true })).toHaveCount(0)
  clean(state)
})

test('a missing captured PO amount is corrected with explicit VAT before one atomic paired save', async ({ page }) => {
  const amountNote = 'The purchase amount could not be confirmed. Review and save the amount from the original PDF.'
  const otherNote = 'Check the delivery terms against the original PDF.'
  const state = await pairedImportHarness(page, { poFields: { total_amount: '0', gross_amount: '0' }, poPreviewIssues: [amountNote, otherNote] })
  await previewPair(page)
  await dialog(page).getByLabel('PO Description', { exact: true }).fill('Reviewed scope retained through amount correction')
  const sources = await sourceUrls(page)
  const amount = dialog(page).getByLabel('PO Entered price', { exact: true })
  await save(page).click()
  await expect(amount).toBeFocused()
  await expect(amount).toHaveAttribute('aria-invalid', 'true')
  await expect(dialog(page).getByRole('alert')).toContainText('Enter a PO amount greater than zero')
  expect(state.pairSaves).toEqual([])
  expect(state.pairWrites).toEqual([])
  await expect(dialog(page).getByLabel('PO Description', { exact: true })).toHaveValue('Reviewed scope retained through amount correction')
  await amount.fill('12500.50')
  await expect(amount).toHaveAttribute('aria-invalid', 'false')
  await save(page).click()
  await expect(dialog(page).getByRole('alert')).toContainText('Confirm the PO VAT treatment')
  expect(state.pairSaves).toEqual([])
  expect(await sourceUrls(page)).toEqual(sources)
  await expect(dialog(page)).toContainText('Captured extraction notes')
  await expect(dialog(page)).toContainText(otherNote)
  await dialog(page).getByLabel('PO VAT price basis', { exact: true }).selectOption('inclusive')
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  expect(state.pairSaves).toHaveLength(1)
  expect(state.pairWrites).toHaveLength(1)
  expect(JSON.parse(state.pairSaves[0].po_reviewed_fields)).toMatchObject({ entered_amount: '12500.50', vat_basis: 'inclusive', summary: 'Reviewed scope retained through amount correction' })
  expect(state.pairSaves[0].file.filename).toBe(syntheticApprovedPdf.name)
  expect(state.pairSaves[0].po_file.filename).toBe(syntheticPoPdf.name)
  clean(state)
})

test('an unverified paired response stays in review and never reports both records saved', async ({ page }) => {
  const state = await pairedImportHarness(page)
  await previewPair(page)
  state.incompleteResponse = true
  await save(page).click()
  await expect(dialog(page).getByRole('alert')).toContainText('combined PR and PO save could not be confirmed')
  await expect(dialog(page).getByLabel('PO Number', { exact: true })).toHaveValue(pairedPoNumber)
  await expect(dialog(page).getByText('Both source PDFs are attached.', { exact: false })).toHaveCount(0)
  expect(state.pairWrites).toEqual([])
  clean(state)
})

test('an existing PR receives both PDFs with its original values preserved and the PO linked', async ({ page }) => {
  const state = await pairedImportHarness(page, { existing: true })
  const previous = structuredClone(state.props.requisitions.find(record => record.pr_number === state.importNumber))
  await previewPair(page)
  await expect(dialog(page).getByLabel('Product / Service', { exact: true })).toHaveValue('PR scope from its own PDF')
  await expect(dialog(page).getByLabel('Product / Service', { exact: true })).toHaveJSProperty('readOnly', true)
  await expect(dialog(page).getByLabel('Entered price', { exact: true })).toHaveJSProperty('readOnly', true)
  await expect(dialog(page).getByLabel('PO Description', { exact: true })).toBeEditable()
  await save(page).click()
  await expect(dialog(page)).toContainText('has the signed PDF attached')
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  expect(state.pairSaves[0]).toMatchObject({ attach_only: 'true', expected_pr_number: state.importNumber })
  expect(JSON.parse(state.pairSaves[0].manual_overrides)).toEqual({})
  expect(state.props.requisitions.find(record => record.id === previous.id)).toMatchObject({ product_service: previous.product_service, total_price: previous.total_price })
  clean(state)
})

test('PR-only operators keep PR import without access to a PO upload control', async ({ page }) => {
  const state = await pairedImportHarness(page, { prepare: current => {
    current.actor.is_superuser = false
    current.actor.module_actions.procurement_orders = ['read']
  } })
  await open(page)
  await expect(poFile(page)).toHaveCount(0)
  await prFile(page).setInputFiles(syntheticApprovedPdf)
  await dialog(page).getByRole('button', { name: 'Preview OCR', exact: true }).click()
  await expect(dialog(page).getByRole('button', { name: 'Upload PR', exact: true })).toBeEnabled()
  expect(state.pairPreviews).toEqual([])
  clean(state)
})

test('attaching an existing PO keeps its values and shows returned PO discrepancy warnings after save', async ({ page }) => {
  const state = await pairedImportHarness(page, { poOperation: 'attached', poIssues: ['Uploaded PO amount differs from the existing purchase order.'] })
  await previewPair(page)
  await save(page).click()
  await expect(dialog(page)).toContainText('Both source PDFs are attached.')
  await expect(dialog(page)).toContainText('Existing PO values were kept.')
  await expect(dialog(page)).toContainText('PO: Uploaded PO amount differs from the existing purchase order.')
  expect(state.pairWrites).toHaveLength(1)
  clean(state)
})
