import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { recommendationHarness, recommendationId as id, recommendationNumber as number } from '../fixtures/purchase-recommendations.fixture'

test.setTimeout(60000)
const register = page => page.getByRole('region', { name: 'Recommendation register', exact: true })
const details = page => page.getByRole('complementary', { name: 'Recommendation details' })
const row = (page, index) => register(page).getByRole('row').filter({ has: page.getByRole('button', { name: `Select ${number(index)}`, exact: true }) })
const loaded = async page => {
  await expect(page.getByRole('heading', { name: 'Purchase Recommendations', exact: true })).toBeVisible()
  await expect(details(page)).toHaveAttribute('aria-busy', 'false')
}
const select = async (page, index) => { await page.getByRole('button', { name: `Select ${number(index)}`, exact: true }).click(); await loaded(page) }
const fact = (page, label) => details(page).getByText(label, { exact: true }).locator('..')
const actions = page => page.evaluate(() => window.recommendationActions)
const clean = (state, allowWrites = false) => {
  expect(state.unknown).toEqual([]); expect(state.pageErrors).toEqual([])
  if (!allowWrites) expect(state.requests.filter(request => request.method !== 'GET')).toEqual([])
}
const accessibility = async page => {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  const result = await new AxeBuilder({ page }).analyze()
  expect(result.violations.filter(value => ['critical', 'serious'].includes(value.impact))).toEqual([])
}
const reset = async page => { await page.getByRole('button', { name: 'Recommendation register options', exact: true }).click(); await page.getByRole('menuitem', { name: 'Reset filters', exact: true }).click() }
const bulk = async page => { await page.getByRole('button', { name: 'Recommendation register options', exact: true }).click(); await page.getByRole('menuitem', { name: 'Select records', exact: true }).click() }

test('desktop register and selected sourcing facts match recorded evidence', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await recommendationHarness(page, { shell: true }); await loaded(page)
  await expect(register(page).getByRole('row')).toHaveCount(9)
  await expect(page.locator('.prw-kpis > button')).toHaveCount(7)
  await expect(details(page)).toContainText('Control valve engineering package')
  await expect(fact(page, 'Quotes evaluated')).toContainText('2')
  await expect(fact(page, 'Funding status')).toContainText('Not recorded')
  await expect(fact(page, 'Buyer')).toContainText('Not assigned')
  await expect(row(page, 6)).toContainText('USD 22,500')
  await page.screenshot({ path: '../artifacts/purchase-recommendations-desktop.png' })
  await accessibility(page); clean(state)
})

test('selection does not infer quotes from shortlist or approval evidence from conversion', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page)
  await select(page, 8)
  await expect(fact(page, 'Quotes evaluated')).toContainText('Not recorded')
  await expect(row(page, 8)).not.toContainText('Review overdue')
  await select(page, 6)
  const approved = details(page).getByRole('list', { name: 'Recommendation lifecycle' }).getByRole('listitem').filter({ hasText: /^Approved/ })
  await expect(approved).toContainText('Not recorded')
  await expect(details(page)).toContainText('Purchase order created')
  await expect(details(page).getByRole('link', { name: 'View purchase order' })).toHaveAttribute('href', '/procurement/orders/101')
  expect(state.requests.filter(request => /\/requisitions\/[^/]+\/$/.test(request.path))).toHaveLength(3)
  clean(state)
})

test('search filters chips and my actions narrow records without assigning draft reviewers', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page)
  await page.getByRole('textbox', { name: 'Search recommendations' }).fill('cable')
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  expect((await actions(page)).at(-1)).toMatchObject({ name: 'export', value: [{ id: id(203) }] })
  await page.getByRole('switch', { name: 'My actions' }).check()
  await expect(page.getByRole('heading', { name: 'No matching recommendations' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByRole('combobox', { name: 'Requester', exact: true }).selectOption('Samir Ali')
  await page.getByRole('combobox', { name: 'Supplier', exact: true }).selectOption('Summit Cable Trading')
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Remove Requester: Samir Ali filter', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Requester', exact: true })).toHaveValue('all')
  await reset(page)
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('urgent')
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await expect(register(page)).toContainText('Review deadline not recorded')
  clean(state)
})

test('stale draft and ready filters preserve actual date and conversion eligibility', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page)
  await page.getByRole('button', { name: 'Review stale drafts', exact: true }).click()
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await expect(register(page)).toContainText(number(3))
  await reset(page)
  await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('ready_for_po')
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await expect(register(page)).toContainText(number(4))
  await loaded(page)
  await expect(details(page)).toContainText('Ready to create purchase order')
  await details(page).getByRole('button', { name: 'Create purchase order', exact: true }).click()
  expect((await actions(page)).at(-1)).toMatchObject({ name: 'convert', value: { id: id(204) } })
  clean(state)
})

test('bulk selection exports selected records and sends only actionable approvals', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page); await bulk(page)
  await page.getByRole('checkbox', { name: 'Select all visible recommendations' }).check()
  await expect(page.getByRole('button', { name: 'Approve selected (2)', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Export selected', exact: true }).click()
  expect((await actions(page)).at(-1).value).toHaveLength(8)
  await page.getByRole('button', { name: 'Approve selected (2)', exact: true }).click()
  expect((await actions(page)).at(-1)).toMatchObject({ name: 'approveSelected', value: [{ id: id(201) }, { id: id(202) }] })
  await expect(page.getByRole('button', { name: 'Approve selected (0)', exact: true })).toBeDisabled()
  clean(state)
})

test('cancelled and partially successful bulk approval preserve outstanding selections', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => { state.props.approvalResult = [] } }); await loaded(page); await bulk(page)
  await page.getByRole('checkbox', { name: `Select for bulk ${number(1)}`, exact: true }).check()
  await page.getByRole('checkbox', { name: `Select for bulk ${number(2)}`, exact: true }).check()
  await page.getByRole('button', { name: 'Approve selected (2)', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: `Select for bulk ${number(1)}`, exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: `Select for bulk ${number(2)}`, exact: true })).toBeChecked()
  await page.evaluate(approvalResult => window.setRecommendationProps({ approvalResult }), [id(201)])
  await page.getByRole('button', { name: 'Approve selected (2)', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: `Select for bulk ${number(1)}`, exact: true })).not.toBeChecked()
  await expect(page.getByRole('checkbox', { name: `Select for bulk ${number(2)}`, exact: true })).toBeChecked()
  await expect(page.getByRole('button', { name: 'Approve selected (1)', exact: true })).toBeEnabled()
  clean(state)
})

test('pagination selection and sorting remain consistent after filters reset the page', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => {
    for (let index = 9; index <= 32; index += 1) {
      const record = { ...state.props.requisitions[2], id: id(index + 200), pr_number: number(index), product_service: `Additional synthetic scope ${index}` }
      state.props.requisitions.push(record); state.details[record.id] = record
    }
  } }); await loaded(page)
  await expect(register(page).getByRole('row')).toHaveCount(26)
  await page.getByRole('combobox', { name: 'Rows per page' }).selectOption('10')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Page 2', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('textbox', { name: 'Search recommendations' }).fill('Control valve')
  await expect(register(page).getByRole('row')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Page 1', exact: true })).toHaveAttribute('aria-current', 'page')
  await reset(page)
  await register(page).getByRole('button', { name: 'PR number', exact: true }).click()
  await expect(register(page).getByRole('columnheader').filter({ hasText: 'PR number' })).toHaveAttribute('aria-sort', 'ascending')
  clean(state)
})

test('menus preserve keyboard focus and delegate create import edit delete and PDF actions', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page)
  const trigger = page.getByRole('button', { name: 'More recommendation actions', exact: true })
  await trigger.click(); await trigger.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Import signed PDF', exact: true })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(trigger).toBeFocused()
  await trigger.click(); await page.getByRole('menuitem', { name: 'Import Excel', exact: true }).click()
  await page.getByRole('button', { name: 'New recommendation', exact: true }).click()
  await page.getByRole('button', { name: `Actions for ${number(7)}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Edit recommendation', exact: true }).click()
  await page.getByRole('button', { name: `Actions for ${number(7)}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete recommendation', exact: true }).click()
  await page.getByRole('button', { name: `Actions for ${number(4)}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Preview signed PDF', exact: true }).click()
  expect((await actions(page)).map(value => [value.name, value.value?.id])).toEqual([
    ['importExcel', undefined], ['create', undefined], ['edit', id(207)], ['delete', id(207)], ['pdf', id(204)],
  ])
  clean(state)
})

test('shared portal menu arrow keys advance once wrap and restore trigger focus', async ({ page }) => {
  const state = await recommendationHarness(page); await loaded(page)
  const trigger = page.getByRole('button', { name: 'More recommendation actions', exact: true })
  const first = page.getByRole('menuitem', { name: 'Import signed PDF', exact: true })
  const second = page.getByRole('menuitem', { name: 'Import Excel', exact: true })
  await trigger.click()
  await trigger.press('ArrowDown')
  await expect(first).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(second).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(first).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(second).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(first).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('menu', { name: 'More recommendation actions', exact: true })).toHaveCount(0)
  expect(await actions(page)).toEqual([])
  clean(state)
})

test('permission callbacks hide writes and unknown values do not become zero or approvals', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => { state.props.readOnly = true; state.props.currentUserId = null } }); await loaded(page)
  await expect(page.getByRole('switch', { name: 'My actions' })).toBeDisabled()
  await select(page, 7)
  await expect(fact(page, 'Total')).toContainText('—')
  await expect(fact(page, 'Budget code')).toContainText('Not recorded')
  await expect(fact(page, 'Savings vs budget')).toContainText('Not recorded')
  await page.getByRole('button', { name: `Actions for ${number(7)}`, exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Edit recommendation', exact: true })).toHaveCount(0)
  await expect(page.getByRole('menuitem', { name: 'Delete recommendation', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await select(page, 4)
  await expect(details(page).getByRole('button', { name: 'Create purchase order', exact: true })).toHaveCount(0)
  await bulk(page); await page.getByRole('checkbox', { name: 'Select all visible recommendations' }).check()
  await expect(page.getByRole('button', { name: 'Approve selected (0)', exact: true })).toBeDisabled()
  clean(state)
})

test('late detail responses cannot overwrite a newly selected recommendation', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => { state.deferred[id(201)] = true } })
  await expect.poll(() => Boolean(state.pending[id(201)])).toBeTruthy()
  await select(page, 2)
  await expect(details(page)).toContainText('Instrumentation inspection services')
  state.pending[id(201)](); delete state.deferred[id(201)]
  await expect.poll(() => Boolean(state.delivered[id(201)])).toBeTruthy()
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
  await expect(details(page)).not.toContainText('Control valve engineering package')
  await expect(page.getByRole('button', { name: `Select ${number(2)}`, exact: true })).toHaveAttribute('aria-pressed', 'true')
  clean(state)
})

test('detail failures mismatched identities and retries preserve the selected record', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => { state.detailErrors[id(201)] = 'Synthetic recommendation details unavailable.' } }); await loaded(page)
  await expect(details(page).getByRole('alert')).toContainText('Synthetic recommendation details unavailable.')
  delete state.detailErrors[id(201)]; state.details[id(201)].id = id(999)
  await details(page).getByRole('button', { name: 'Retry details', exact: true }).click()
  await expect(details(page).getByRole('alert')).toContainText('do not match the selected recommendation')
  state.details[id(201)].id = id(201)
  await details(page).getByRole('button', { name: 'Retry details', exact: true }).click(); await loaded(page)
  await expect(details(page).getByRole('alert')).toHaveCount(0)
  await expect(fact(page, 'Quotes evaluated')).toContainText('2')
  clean(state)
})

test('loading failure empty and refreshed selection remain distinct', async ({ page }) => {
  const state = await recommendationHarness(page, { prepare: state => { state.props = { ...state.props, requisitions: [], loading: true } } })
  await expect(page.getByRole('status')).toContainText('Loading recommendations')
  await expect(page.getByRole('button', { name: 'Export', exact: true })).toBeDisabled()
  await page.evaluate(() => window.setRecommendationProps({ loading: false, error: 'Synthetic register unavailable.' }))
  await expect(page.getByRole('heading', { name: 'Register unavailable' })).toBeVisible()
  await expect(page.locator('.prw-kpi-value')).toHaveText(Array(7).fill('—'))
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await page.evaluate(() => window.setRecommendationProps({ error: null }))
  await expect(page.getByRole('heading', { name: 'No recommendations yet' })).toBeVisible()
  await page.evaluate(requisitions => window.setRecommendationProps({ requisitions }), [state.details[id(203)]])
  await loaded(page); await expect(details(page)).toContainText('Cable installation materials')
  expect(await actions(page)).toEqual([{ name: 'refresh' }]); clean(state)
})

test('mobile layout and open menus remain accessible with local table scrolling', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const state = await recommendationHarness(page); await loaded(page)
  await page.screenshot({ path: '../artifacts/purchase-recommendations-mobile.png' })
  await page.screenshot({ path: '../artifacts/purchase-recommendations-mobile-full.png', fullPage: true })
  await accessibility(page)
  await page.getByRole('button', { name: 'More recommendation actions', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Import Excel', exact: true })).toBeVisible()
  await accessibility(page); await page.keyboard.press('Escape'); clean(state)
})

test('OrderManagement preserves imports PDF preview Excel export refresh and purchase orders navigation', async ({ page }) => {
  const state = await recommendationHarness(page, { integration: true }); await loaded(page)
  await expect(register(page).getByRole('row')).toHaveCount(9)
  await page.getByRole('button', { name: 'More recommendation actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Import Excel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Import Purchase Recommendations', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'More recommendation actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Import signed PDF', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Import Approved PR PDF', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/\.xlsx$/)
  await page.getByRole('button', { name: `Actions for ${number(4)}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Preview signed PDF', exact: true }).click()
  await expect(page.getByRole('dialog', { name: new RegExp(`Print Preview.*${number(4)}`) })).toBeVisible()
  await page.getByRole('button', { name: 'Close print preview', exact: true }).click()
  const before = state.requests.filter(request => request.path === '/api/v1/procurement/requisitions/').length
  await page.getByRole('button', { name: 'Refresh', exact: true }).click(); await loaded(page)
  expect(state.requests.filter(request => request.path === '/api/v1/procurement/requisitions/')).toHaveLength(before + 2)
  await page.getByRole('link', { name: /^Purchase Orders/ }).click()
  await expect(page.getByRole('heading', { name: 'Purchase Orders', exact: true })).toBeVisible()
  clean(state)
})

test('OrderManagement conversion requires confirmation and posts only the chosen approved record', async ({ page }) => {
  const state = await recommendationHarness(page, { integration: true }); await loaded(page); await select(page, 4)
  await details(page).getByRole('button', { name: 'Create purchase order', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Confirm action' })
  await expect(dialog).toContainText(number(4))
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(state.requests.filter(request => request.method !== 'GET')).toEqual([])
  await details(page).getByRole('button', { name: 'Create purchase order', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Confirm action' })
  await dialog.getByRole('button', { name: 'Confirm', exact: true }).click()
  await page.getByRole('dialog', { name: 'Notification' }).getByRole('button', { name: 'OK', exact: true }).click()
  await loaded(page)
  await expect(details(page)).toContainText('Purchase order created')
  expect(state.requests.filter(request => request.method !== 'GET')).toEqual([{ path: `/api/v1/procurement/requisitions/${id(204)}/convert_to_po/`, method: 'POST', body: null }])
  clean(state, true)
})

test('OrderManagement opens the original approval record and preserves new recommendation routing', async ({ page }) => {
  const state = await recommendationHarness(page, { integration: true }); await loaded(page)
  await details(page).getByRole('button', { name: 'View approval record', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.recommendationRoute)).toBe(`/procurement/requisitions/${id(201)}`)
  await expect(page.getByRole('heading', { name: number(1), exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Approval history', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to Purchase Recommendations', exact: true }).click()
  await loaded(page)
  await page.getByRole('button', { name: 'New recommendation', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.recommendationRoute)).toBe('/procurement/requisitions/new')
  await expect(page.getByRole('heading', { name: 'New recommendation route' })).toBeVisible()
  clean(state)
})
