import { test, expect } from '@playwright/test'
import { recommendationFormHarness, formRecordId } from '../fixtures/purchase-recommendation-form.fixture'

test.setTimeout(120000)
test.use({ serviceWorkers: 'block', viewport: { width: 1672, height: 941 } })
const question = 'Are you sure you want to send this request for approval?'
const saves = state => state.requests.filter(({ method, path }) => ['POST', 'PATCH'].includes(method) && /^\/api\/v1\/procurement\/requisitions\/(?:[^/]+\/)?$/.test(path))
const send = page => page.getByRole('button', { name: 'Send for Approval', exact: true }).first()
const save = page => page.getByRole('button', { name: 'Save', exact: true }).first()
const confirmation = page => page.getByRole('dialog', { name: 'Confirm action', exact: true })
const pricing = page => page.getByRole('navigation', { name: 'Recommendation steps' }).getByRole('button', { name: /Supplier & pricing/ }).click()
const clean = state => { expect(state.unknown).toEqual([]); expect(state.pageErrors).toEqual([]) }
async function open(page, options = {}) {
  const state = await recommendationFormHarness(page, options)
  await expect(page.getByRole('heading', { name: options.edit ? 'Edit purchase recommendation' : 'Create purchase recommendation', exact: true })).toBeVisible({ timeout: 90000 })
  return state
}

test('Save creates a draft and subsequent Enter saves the same draft without VAT confirmation or submission', async ({ page }) => {
  const state = await open(page)
  await page.getByRole('textbox', { name: 'PR number', exact: true }).fill('RAD-PRJ-PR-9001_2026')
  await pricing(page)
  await expect(page.getByRole('combobox', { name: 'VAT price basis' })).toHaveCount(0)
  await expect(page.getByText('VAT treatment', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Add line item', exact: true }).click()
  await page.getByRole('textbox', { name: 'Line item 1 description', exact: true }).fill('Engineering review')
  await page.getByRole('textbox', { name: 'Line item 1 unit', exact: true }).fill('EA')
  await page.getByRole('spinbutton', { name: 'Line item 1 quantity', exact: true }).fill('2')
  await page.getByRole('spinbutton', { name: 'Line item 1 unit price', exact: true }).fill('100')
  await expect(page.locator('.prf-sp-grand-total')).toContainText('200.00')
  await save(page).click()
  await expect.poll(() => saves(state).length).toBe(1)
  expect(state.record.status).toBe('draft')
  expect(Number(state.record.total_price)).toBe(200)
  expect(Number(state.record.net_total_excl_vat)).toBe(200)
  expect(state.submissions).toEqual([])
  await expect(page).toHaveURL(/\/requisitions\/new$/)
  await expect(confirmation(page)).toHaveCount(0)
  await page.getByRole('spinbutton', { name: 'Line item 1 quantity', exact: true }).fill('3')
  await page.getByRole('spinbutton', { name: 'Line item 1 quantity', exact: true }).press('Enter')
  await expect.poll(() => saves(state).length).toBe(2)
  expect(saves(state).map(request => request.method)).toEqual(['POST', 'PATCH'])
  expect(saves(state)[1].path).toContain(formRecordId)
  expect(Number(state.record.total_price)).toBe(300)
  expect(state.submissions).toEqual([])
  await expect(confirmation(page)).toHaveCount(0)
  clean(state)
})

test('No cancels sending without saving or submitting and keeps the request editable', async ({ page }) => {
  const state = await open(page, { edit: true })
  await send(page).click()
  await expect(confirmation(page)).toContainText(question)
  await expect(confirmation(page).getByRole('button', { name: 'Yes', exact: true })).toBeVisible()
  expect(saves(state)).toEqual([])
  expect(state.submissions).toEqual([])
  await confirmation(page).getByRole('button', { name: 'No', exact: true }).click()
  expect(saves(state)).toEqual([])
  expect(state.submissions).toEqual([])
  await expect(save(page)).toBeEnabled()
  await expect(page).toHaveURL(new RegExp(`${formRecordId}/edit$`))
  clean(state)
})

test('Save then Yes sends the persisted request through the explicit approval endpoint exactly once', async ({ page }) => {
  const state = await open(page, { edit: true })
  await save(page).click()
  await expect.poll(() => saves(state).length).toBe(1)
  expect(state.submissions).toEqual([])
  expect(state.record.status).toBe('draft')
  await send(page).click()
  await expect(confirmation(page)).toContainText(question)
  expect(saves(state)).toHaveLength(1)
  expect(state.submissions).toEqual([])
  await confirmation(page).getByRole('button', { name: 'Yes', exact: true }).click()
  await expect.poll(() => state.submissions.length).toBe(1)
  expect(saves(state).every(request => request.method === 'PATCH' && request.path.includes(formRecordId))).toBe(true)
  expect(state.record.status).toBe('submitted')
  await expect(page).toHaveURL(/\/requisitions$/)
  clean(state)
})

test('approval tab omits the review card and confirmed submission failure retains a saved draft', async ({ page }) => {
  const state = await open(page, { edit: true, prepare: fixture => { fixture.submitError = { error: 'Approval route is unavailable.' } } })
  await page.getByRole('navigation', { name: 'Recommendation steps' }).getByRole('button', { name: /Approval & submission/ }).click()
  await expect(page.getByRole('heading', { name: 'Review before submission', exact: true })).toHaveCount(0)
  await expect(page.locator('.prf-review-checks')).toHaveCount(0)
  await send(page).click()
  await confirmation(page).getByRole('button', { name: 'Yes', exact: true }).click()
  const errorDialog = page.getByRole('dialog', { name: 'Notification', exact: true })
  await expect(errorDialog).toContainText('Approval route is unavailable.')
  await errorDialog.getByRole('button', { name: 'OK', exact: true }).click()
  expect(state.record.status).toBe('draft')
  expect(state.submissions).toHaveLength(1)
  await expect(save(page)).toBeEnabled()
  await expect(page).toHaveURL(new RegExp(`${formRecordId}/edit$`))
  clean(state)
})
