import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'
import { riskChangeHarness } from '../fixtures/risk-change-control.fixture'

test.setTimeout(60000)
const region = (page, name) => page.getByRole('region', { name, exact: true })
const register = page => region(page, 'Risk & issue register')
const row = (page, title) => register(page).getByRole('row').filter({ hasText: title })
const changes = page => region(page, 'Change control')
const point = (page, title, basis = 'Residual') => region(page, 'Risk exposure').getByRole('button', { name: new RegExp(`^Select .*${title}: ${basis} probability`) })
const workAreas = page => page.getByRole('navigation', { name: 'Project work areas', exact: true })

async function loaded(page) {
  await expect(page.getByRole('heading', { name: 'Risk & Change Control', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Management', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(register(page)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toBeEnabled()
}
async function selectMatching(select, pattern) {
  const option = select.getByRole('option').filter({ hasText: pattern }).first()
  await select.selectOption(await option.evaluate(element => element.value))
}
async function selectRecord(page, title) {
  await row(page, title).getByRole('button', { name: title, exact: true }).click()
}
async function addRecord(page, type) {
  const menu = page.locator('details').filter({ has: page.locator('summary').filter({ hasText: /^Add$/ }) })
  await menu.locator('summary').click()
  await menu.getByRole('button', { name: `Add ${type}`, exact: true }).click()
  const dialog = page.getByRole('dialog', { name: `Add ${type}`, exact: true })
  await expect(dialog).toBeVisible()
  return dialog
}
async function noHorizontalOverflow(page) {
  const dimensions = await page.evaluate(() => ({
    viewport: innerWidth, document: document.documentElement.scrollWidth,
    overflowing: [...document.querySelectorAll('.project-performance-workspace *')].filter(element => {
      for (let parent = element.parentElement; parent && !['BODY', 'HTML'].includes(parent.tagName); parent = parent.parentElement) {
        if (['hidden', 'auto', 'scroll', 'clip'].includes(getComputedStyle(parent).overflowX)) return false
      }
      return element.getBoundingClientRect().right > innerWidth + 1
    }).slice(0, 12).map(element => ({ tag: element.tagName, className: element.className?.baseVal ?? element.className, right: Math.round(element.getBoundingClientRect().right) })),
  }))
  expect(dimensions.document, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.viewport + 1)
}
async function accessible(page) {
  const scan = await new AxeBuilder({ page }).include('.project-performance-workspace').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
}

test('desktop risk control presents actual assessments, separate currencies, and connected governance records', async ({ page }) => {
  await page.setViewportSize({ width: 1672, height: 941 })
  const state = await riskChangeHarness(page)
  await loaded(page)
  for (const title of ['Open risks', 'Critical / High', 'Risk exposure', 'Residual exposure', 'Open issues', 'Pending changes']) await expect(region(page, 'Risk and change indicators').getByText(title, { exact: true })).toBeVisible()
  for (const name of ['Risk exposure', 'Change control', 'Management actions', 'Risk details', 'Change impact & approvals', 'Control status & data quality']) await expect(region(page, name)).toBeVisible()
  await expect(row(page, 'Long-lead pump delivery')).toContainText('Maya Hassan')
  await expect(row(page, 'Access permit uncertainty')).toContainText(/Not assessed|Unassessed/i)
  await expect(point(page, 'Long-lead pump delivery')).toBeVisible()
  await expect(point(page, 'Access permit uncertainty')).toHaveCount(0)
  await expect(point(page, 'Survey data gap')).toHaveCount(0)
  await expect(page.getByText('2 currencies', { exact: true }).first()).toBeVisible()
  await expect(changes(page)).toContainText('Additional insulation quantities')
  await noHorizontalOverflow(page)
  await page.screenshot({ path: '../artifacts/risk-change-control-desktop.png', animations: 'disabled' })
  await accessible(page)
  expect(state.unknown).toEqual([])
  expect(state.writes).toEqual([])
})

test('inherent and residual plots select real records and preserve currency separation', async ({ page }) => {
  await riskChangeHarness(page)
  await loaded(page)
  await region(page, 'Risk exposure').getByRole('button', { name: 'Inherent', exact: true }).click()
  await point(page, 'Long-lead pump delivery', 'Inherent').click()
  await expect(region(page, 'Risk details')).toContainText('Long-lead pump delivery')
  await region(page, 'Risk exposure').getByRole('button', { name: 'Residual', exact: true }).click()
  await expect(point(page, 'Long-lead pump delivery', 'Residual')).toHaveAttribute('aria-label', /probability 2, impact 4$/)
  await expect(point(page, 'Access permit uncertainty', 'Residual')).toHaveCount(0)
  const currency = region(page, 'Risk exposure').getByRole('combobox')
  await currency.selectOption('USD')
  await expect(region(page, 'Risk exposure')).toContainText(/60,000|60k/i)
  await currency.selectOption('AED')
  await expect(region(page, 'Risk exposure')).toContainText(/180,000|180k/i)
  await expect(region(page, 'Risk exposure')).toContainText(/50,000|50k/i)
  await region(page, 'Risk exposure').getByRole('button', { name: 'Inherent', exact: true }).click()
  await expect(point(page, 'Long-lead pump delivery', 'Inherent')).toHaveAttribute('aria-label', /probability 4, impact 5$/)
})

test('owner, category, my-actions, search, source, and issue selectors filter the real register', async ({ page }) => {
  await riskChangeHarness(page)
  await loaded(page)
  const owner = page.getByRole('combobox', { name: 'Owner', exact: true })
  await selectMatching(owner, /Omar Saleh/)
  await expect(row(page, 'Design interface rework')).toBeVisible()
  await expect(row(page, 'Long-lead pump delivery')).toHaveCount(0)
  await selectMatching(owner, /^All/i)
  const category = page.getByRole('combobox', { name: 'Category', exact: true })
  await selectMatching(category, /^Engineering$/)
  await expect(row(page, 'Design interface rework')).toBeVisible()
  await expect(row(page, 'Long-lead pump delivery')).toHaveCount(0)
  await selectMatching(category, /^All/i)
  await page.getByRole('checkbox', { name: 'My actions', exact: true }).check()
  await expect(row(page, 'Long-lead pump delivery')).toBeVisible()
  await expect(row(page, 'Design interface rework')).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'My actions', exact: true }).uncheck()
  const search = page.getByRole('searchbox', { name: 'Search reference, title or owner', exact: true })
  await search.fill('permit')
  await expect(row(page, 'Access permit uncertainty')).toBeVisible()
  await expect(row(page, 'Long-lead pump delivery')).toHaveCount(0)
  await search.fill('')
  await register(page).getByRole('button', { name: /^Issues \(\d+\)$/ }).click()
  await expect(row(page, 'Vendor documentation hold')).toBeVisible()
  await expect(row(page, 'Long-lead pump delivery')).toHaveCount(0)
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await selectMatching(page.getByRole('combobox', { name: 'Due date', exact: true }), /Overdue/i)
  await expect(row(page, 'Vendor documentation hold')).toBeVisible()
  await expect(row(page, 'Cable routing conflict')).toHaveCount(0)
  await selectMatching(page.getByRole('combobox', { name: 'Due date', exact: true }), /^All/i)
  await selectMatching(page.getByRole('combobox', { name: 'Source', exact: true }), /Document/i)
  await expect(changes(page)).toContainText('Additional insulation quantities')
  await expect(changes(page)).not.toContainText('Additional tie-in scope')
  await selectMatching(page.getByRole('combobox', { name: 'Source', exact: true }), /^All/i)
  await page.getByRole('button', { name: 'Registers', exact: true }).click()
  await expect(region(page, 'Risk exposure')).toHaveCount(0)
  await expect(register(page)).toBeVisible()
  await page.getByRole('button', { name: 'Management', exact: true }).click()
  await region(page, 'Risk and change indicators').getByRole('button', { name: /^Open risks / }).click()
  await expect(row(page, 'Long-lead pump delivery')).toBeVisible()
  await expect(row(page, 'Survey data gap')).toHaveCount(0)
  await region(page, 'Risk and change indicators').getByRole('button', { name: /^Pending changes / }).click()
  await expect(changes(page)).toContainText('Additional tie-in scope')
  await expect(changes(page)).toContainText('Additional insulation quantities')
})

test('record details and actual comments support review, updates, and dialog focus restoration', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  await selectRecord(page, 'Long-lead pump delivery')
  const response = page.getByRole('button', { name: 'Review response', exact: true })
  await response.click()
  let dialog = page.getByRole('dialog', { name: 'Review response', exact: true })
  await expect(dialog).toContainText('Vendor recovery plan requested at the coordination meeting.')
  await page.keyboard.press('Escape')
  await expect(response).toBeFocused()
  await page.getByRole('button', { name: 'Add update', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Add update', exact: true })
  await dialog.getByLabel('Update', { exact: true }).fill('Vendor confirmed the revised shipment review date.')
  await dialog.getByRole('button', { name: 'Save update', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes).toHaveLength(1)
  expect(state.writes[0]).toMatchObject({ method: 'POST', body: { item: 2101, body: 'Vendor confirmed the revised shipment review date.' } })
  expect(state.writes[0].path).toMatch(/\/schedule-versions\/91\/governance-comments\/$/)
  await response.click()
  await expect(page.getByRole('dialog', { name: 'Review response', exact: true })).toContainText('Vendor confirmed the revised shipment review date.')
})

test('risk create and edit save explicit assessments and preserve the project and linked activity', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  let dialog = await addRecord(page, 'risk')
  await dialog.getByLabel('Title', { exact: true }).fill('Borehole data uncertainty')
  await dialog.getByLabel('Description', { exact: true }).fill('Review the available investigation data before the design gate.')
  await dialog.getByRole('combobox', { name: 'Priority', exact: true }).selectOption('high')
  await dialog.getByRole('combobox', { name: 'Owner', exact: true }).selectOption('7')
  await dialog.getByLabel('Due date', { exact: true }).fill('2026-09-28')
  await dialog.getByRole('combobox', { name: 'Linked activity', exact: true }).selectOption('402')
  await dialog.getByRole('combobox', { name: 'Category', exact: true }).selectOption('Engineering')
  await dialog.getByLabel('Cause', { exact: true }).fill('Incomplete ground investigation records.')
  await dialog.getByLabel('Event', { exact: true }).fill('Foundation assumptions require revision.')
  await dialog.getByLabel('Effect', { exact: true }).fill('Design rework before the issue date.')
  await dialog.getByRole('combobox', { name: 'Response strategy', exact: true }).selectOption('reduce')
  await dialog.getByRole('combobox', { name: 'Inherent probability', exact: true }).selectOption('4')
  await dialog.getByRole('combobox', { name: 'Inherent impact', exact: true }).selectOption('4')
  await dialog.getByRole('combobox', { name: 'Residual probability', exact: true }).selectOption('2')
  await dialog.getByRole('combobox', { name: 'Residual impact', exact: true }).selectOption('2')
  await dialog.getByLabel('Inherent cost exposure', { exact: true }).fill('300000')
  await dialog.getByLabel('Residual cost exposure', { exact: true }).fill('80000')
  await dialog.getByLabel('Currency', { exact: true }).fill('AED')
  await dialog.getByRole('button', { name: 'Create risk', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(row(page, 'Borehole data uncertainty')).toBeVisible()
  expect(state.writes[0]).toMatchObject({ method: 'POST', project: 17, body: { item_type: 'risk', owner: 7, activity: 402, metadata: { risk_control: { inherent_probability: 4, inherent_impact: 4, residual_probability: 2, residual_impact: 2, inherent_cost_exposure: '300000', residual_cost_exposure: '80000', currency: 'AED' } } } })
  await selectRecord(page, 'Borehole data uncertainty')
  await page.getByRole('button', { name: 'Edit risk', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Edit risk', exact: true })
  await dialog.getByLabel('Title', { exact: true }).fill('Borehole data review')
  await dialog.getByRole('combobox', { name: 'Status', exact: true }).selectOption('in_review')
  await dialog.getByRole('combobox', { name: 'Residual probability', exact: true }).selectOption('1')
  await dialog.getByLabel('Resolution', { exact: true }).fill('Investigation update requested.')
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(row(page, 'Borehole data review')).toBeVisible()
  expect(state.writes).toHaveLength(2)
  expect(state.writes[1]).toMatchObject({ method: 'PATCH', project: 17, body: { title: 'Borehole data review', status: 'in_review', metadata: { risk_control: { residual_probability: 1 } } } })
  expect(state.records[18].governance.items.some(item => /Borehole/.test(item.title))).toBe(false)
})

test('issue and change creation persist assessed zero and estimated impacts without writing document changes', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  let dialog = await addRecord(page, 'issue')
  await dialog.getByLabel('Title', { exact: true }).fill('Cable tray review coordination')
  await dialog.getByRole('combobox', { name: 'Owner', exact: true }).selectOption('8')
  await dialog.getByLabel('Cost impact', { exact: true }).fill('0')
  await dialog.getByLabel('Schedule impact (days)', { exact: true }).fill('0')
  await dialog.getByRole('button', { name: 'Create issue', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes[0]).toMatchObject({ body: { item_type: 'issue', cost_impact: '0', schedule_impact_days: '0', metadata: { risk_control: { cost_impact_assessed: true, schedule_impact_assessed: true } } } })
  dialog = await addRecord(page, 'change')
  await dialog.getByLabel('Title', { exact: true }).fill('Additional instrument supports')
  await dialog.getByLabel('Cost impact', { exact: true }).fill('25000')
  await dialog.getByLabel('Schedule impact (days)', { exact: true }).fill('3')
  await dialog.getByRole('button', { name: 'Create change', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes[1]).toMatchObject({ body: { item_type: 'change_request', cost_impact: '25000', schedule_impact_days: '3' } })
  expect(state.writes.every(write => write.path.endsWith('/governance-items/'))).toBe(true)
  await expect(changes(page)).toContainText('Additional instrument supports')
})

test('failed saves preserve the draft and retry produces a single governance item', async ({ page }) => {
  const state = await riskChangeHarness(page, { prepare: current => { current.saveFailure = true } })
  await loaded(page)
  const dialog = await addRecord(page, 'risk')
  await dialog.getByLabel('Title', { exact: true }).fill('Retry risk assessment')
  await dialog.getByRole('button', { name: 'Create risk', exact: true }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog.getByLabel('Title', { exact: true })).toHaveValue('Retry risk assessment')
  expect(state.records[17].governance.items.filter(item => item.title === 'Retry risk assessment')).toHaveLength(0)
  state.saveFailure = false
  await dialog.getByRole('button', { name: 'Create risk', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.records[17].governance.items.filter(item => item.title === 'Retry risk assessment')).toHaveLength(1)
})

test('document changes preserve their source currency and expose read-only approval provenance', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  await changes(page).getByRole('row').filter({ hasText: 'Imported supplier price revision' }).getByRole('button', { name: 'Imported supplier price revision', exact: true }).click()
  await expect(region(page, 'Change impact & approvals')).toContainText('USD')
  await expect(region(page, 'Change impact & approvals')).toContainText(/25,000|25k/i)
  await expect(region(page, 'Change impact & approvals').getByRole('button', { name: 'Edit change', exact: true })).toHaveCount(0)
  const approval = page.getByRole('button', { name: /Approval record|Review approval/i }).first()
  await approval.click()
  const dialog = page.getByRole('dialog', { name: 'Change approval record', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText(/reviewed|review|source/i)
  await expect(dialog).not.toContainText(/Approved by Maya|Baseline approved/i)
  await page.keyboard.press('Escape')
  await expect(approval).toBeFocused()
  expect(state.writes).toEqual([])
})

test('CSV export includes unfiltered governance and document records with explicit currencies', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  await page.getByRole('searchbox', { name: 'Search reference, title or owner', exact: true }).fill('pump')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export register', exact: true }).click()
  const download = await pending
  expect(download.suggestedFilename()).toMatch(/\.csv$/i)
  const contents = await readFile(await download.path(), 'utf8')
  for (const value of ['5900913', 'Long-lead pump delivery', 'Access permit uncertainty', 'Imported supplier price revision', 'Additional insulation quantities', 'AED', 'USD']) expect(contents).toContain(value)
  expect(state.writes).toEqual([])
})

test('Refresh and project selection reload risks and changes without losing the active work area', async ({ page }) => {
  const state = await riskChangeHarness(page)
  await loaded(page)
  state.records[17].governance.items[0].title = 'Updated pump delivery assessment'
  state.records[17].project.client_name = 'Updated Refining Client'
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(row(page, 'Updated pump delivery assessment')).toBeVisible()
  await expect(page.getByText('Client: Updated Refining Client', { exact: true })).toBeVisible()
  const selector = page.getByRole('combobox', { name: 'Active Project', exact: true })
  await selector.fill('5900738')
  await selector.press('Enter')
  await expect(page).toHaveURL(/project=18/)
  await expect(page).toHaveURL(/view=risk/)
  await expect(row(page, 'Updated pump delivery assessment')).toHaveCount(0)
  await expect(row(page, 'Long-lead pump delivery')).toBeVisible()
  await expect.poll(() => state.requests.some(request => request.project === 18 && request.path.endsWith('/governance/'))).toBe(true)
  expect(state.unknown).toEqual([])
})

test('empty and failed sources remain distinct and unavailable governance disables writes', async ({ page }) => {
  const state = await riskChangeHarness(page, { prepare: current => {
    current.records[17].governance.items = []
    current.records[17].changes = []
  } })
  await loaded(page)
  await expect(register(page)).toContainText(/No.*risk|No.*record/i)
  await expect(region(page, 'Risk exposure')).toContainText(/No.*assess|No.*rat/i)
  state.failures.add('/governance/')
  state.failures.add('/change-events/')
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert').first()).toContainText(/unavailable|could not be loaded/i)
  await expect(register(page)).toContainText(/unavailable/i)
  state.failures.clear()
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(register(page)).toContainText(/No.*risk|No.*record/i)
  expect(state.writes).toEqual([])
})

test('read-only governance permits inspection but does not offer editing controls', async ({ page }) => {
  const state = await riskChangeHarness(page, { prepare: current => { current.records[17].governance.can_manage = false } })
  await loaded(page)
  await selectRecord(page, 'Long-lead pump delivery')
  await expect(page.getByRole('button', { name: 'Edit risk', exact: true })).toHaveCount(0)
  const add = page.locator('summary').filter({ hasText: /^Add$/ })
  await expect(add).toHaveAttribute('aria-disabled', 'true')
  await add.click()
  await expect(page.getByRole('button', { name: 'Add risk', exact: true })).toHaveCount(0)
  expect(state.writes).toEqual([])
})

test('editing a governance item preserves its linked activity when workspace details are unavailable', async ({ page }) => {
  const state = await riskChangeHarness(page, { prepare: current => { current.failures.add('/workspace/') } })
  await loaded(page)
  await selectRecord(page, 'Long-lead pump delivery')
  await page.getByRole('button', { name: 'Edit risk', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit risk', exact: true })
  const activity = dialog.getByRole('combobox', { name: 'Linked activity', exact: true })
  await expect(activity).toHaveValue('404')
  await expect(activity.locator('option:checked')).toContainText('details unavailable')
  await dialog.getByLabel('Title', { exact: true }).fill('Pump delivery assessment retained')
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(state.writes).toHaveLength(1)
  expect(state.writes[0]).toMatchObject({ method: 'PATCH', body: { item_id: 2101, activity: 404 } })
  expect(state.records[17].governance.items.find(item => item.id === 2101).activity).toBe(404)
})

test('mobile risk control, long assessment forms, and local scrollers fit and pass accessibility checks', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await riskChangeHarness(page)
  await loaded(page)
  await noHorizontalOverflow(page)
  await page.screenshot({ path: '../artifacts/risk-change-control-mobile.png', animations: 'disabled' })
  await page.screenshot({ path: '../artifacts/risk-change-control-mobile-full.png', fullPage: true, animations: 'disabled' })
  const dialog = await addRecord(page, 'risk')
  const bounds = await dialog.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(391)
  expect(bounds.height).toBeLessThanOrEqual(844)
  await noHorizontalOverflow(page)
  const formScan = await new AxeBuilder({ page }).include('.rc-dialog').analyze()
  expect(formScan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  await page.keyboard.press('Escape')
  await expect(page.locator('summary').filter({ hasText: /^Add$/ })).toBeFocused()
  await accessible(page)
  await workAreas(page).getByRole('button', { name: 'Overview', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Project Performance', exact: true })).toBeVisible()
})
