import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { mkdir } from 'node:fs/promises'
import { sharedRecordsHarness } from '../fixtures/shared-records.fixture.js'

test.setTimeout(60000)
const workspace = page => page.getByRole('region', { name: 'Shared records workspace', exact: true })
const review = page => page.getByRole('region', { name: 'Record review', exact: true })
const reason = page => review(page).getByLabel('Reason for this connection')
const client = page => review(page).getByLabel('Selected client', { exact: true })
const save = page => review(page).getByRole('button', { name: 'Save connections', exact: true })
async function chooseClient(page) {
  await workspace(page).getByRole('button', { name: 'Review PR-17', exact: true }).click()
  await expect(client(page)).toBeEnabled()
  await client(page).selectOption('client-a')
  await reason(page).fill('Confirmed against the signed source.')
}

test('portfolio opens the shared queue; ambiguous candidates require explicit selection and source values survive linking', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { query: 'view=portfolio' })
  await page.getByRole('button', { name: 'Shared records', exact: true }).click()
  await expect(workspace(page)).toBeVisible()
  await workspace(page).getByRole('button', { name: 'Review PR-17', exact: true }).click()
  await expect(review(page)).toContainText('Multiple client records match')
  await expect(client(page)).toHaveValue('')
  await reason(page).fill('Confirmed against the signed source.')
  await expect(save(page)).toBeDisabled()
  await client(page).selectOption('client-a')
  await save(page).click()
  await expect(review(page).getByText('Shared record links saved.', { exact: true })).toBeVisible()
  await expect(save(page)).toHaveCount(0)
  expect(state.commands).toHaveLength(1)
  expect(state.commands[0].targets).toEqual({ client_id: 'client-a' })
  expect(state.commands[0].expected_token).toBe('token-17')
  expect(state.rows[0].source_values).toEqual({ client_name: 'Acme' })
  await expect(review(page)).toContainText('CL-01 · Acme Engineering')
  expect(state.app.pageErrors).toEqual([]); expect(state.app.unknown).toEqual([])
})

test('stale refresh retains target and reason and saves with a new freshness token', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { saveFailures: [409] })
  await chooseClient(page); await save(page).click()
  await expect(review(page).getByRole('alert')).toContainText('The source changed')
  await expect(client(page)).toHaveValue('client-a'); await expect(reason(page)).toHaveValue('Confirmed against the signed source.')
  await expect(save(page)).toBeDisabled()
  await review(page).getByRole('button', { name: 'Refresh record to review' }).click()
  await expect(save(page)).toBeEnabled()
  await expect(client(page)).toHaveValue('client-a'); await expect(reason(page)).toHaveValue('Confirmed against the signed source.')
  await save(page).click()
  await expect(review(page).getByText('Shared record links saved.', { exact: true })).toBeVisible()
  expect(state.commands[1].expected_token).toBe('refreshed-token')
  expect(state.commands[1].request_id).not.toBe(state.commands[0].request_id)
})

test('uncertain network response retries the identical request and confirms its saved result', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { saveFailures: ['network'] })
  await chooseClient(page); await save(page).click()
  await expect(review(page).getByRole('alert')).toContainText('result is uncertain')
  await expect(reason(page)).toHaveValue('Confirmed against the signed source.')
  await expect(client(page)).toHaveValue('client-a')
  await review(page).getByRole('button', { name: 'Retry same request' }).click()
  await expect(review(page).getByText('The previously saved links are confirmed.', { exact: true })).toBeVisible()
  expect(state.commands).toHaveLength(2); expect(state.commands[1]).toEqual(state.commands[0])
})

test('validation and update denial retain input; read-only records expose no save form', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { saveFailures: [400, 403] })
  await chooseClient(page); await save(page).click()
  await expect(review(page).getByRole('alert')).toContainText('selected client is not valid')
  await save(page).click()
  await expect(review(page).getByRole('alert')).toContainText('update access is denied')
  await expect(client(page)).toHaveValue('client-a'); await expect(reason(page)).toHaveValue('Confirmed against the signed source.')
  await workspace(page).getByLabel('Connection status').selectOption('linked')
  await workspace(page).getByRole('button', { name: 'Review PR-19' }).click()
  await expect(review(page)).toContainText('This connection is read-only.')
  await expect(save(page)).toHaveCount(0)
  expect(state.commands).toHaveLength(2)
})

test('queue denial can retry and filtered empty results retain filters', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { queueFailure: 403 })
  await expect(workspace(page).getByRole('alert')).toContainText('access is denied')
  await expect(workspace(page).getByRole('button', { name: /Review PR/ })).toHaveCount(0)
  state.queueFailure = 0
  await workspace(page).getByRole('button', { name: 'Retry queue' }).click()
  await expect(workspace(page).getByRole('button', { name: 'Review PR-17' })).toBeVisible()
  await workspace(page).getByLabel('Search records').fill('nothing matches')
  await expect(workspace(page)).toContainText('No records to review')
  await expect(workspace(page).getByLabel('Search records')).toHaveValue('nothing matches')
  expect(state.commands).toEqual([])
})

test('queue pagination, source filter and candidate search use server results without automatic selection', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { pageSize: 1, hasMore: true })
  await expect(workspace(page)).toContainText('Page 1 of 2')
  await workspace(page).getByRole('button', { name: 'Next records' }).click()
  await expect(workspace(page).getByRole('button', { name: 'Review PR-20' })).toBeVisible()
  await workspace(page).getByRole('combobox', { name: 'Source', exact: true }).selectOption('approved_hours')
  await expect(workspace(page).getByRole('button', { name: 'Review TIME-18' })).toBeVisible()
  await workspace(page).getByRole('combobox', { name: 'Source', exact: true }).selectOption('project_client')
  await workspace(page).getByRole('button', { name: 'Review PR-17' }).click()
  await expect(review(page)).toContainText('Narrow your search')
  await review(page).getByLabel('Search client records').fill('Energy')
  await expect(client(page).getByRole('option')).toHaveCount(2)
  await expect(client(page)).toHaveValue('')
  await review(page).getByLabel('Search client records').fill('none')
  await expect(review(page)).toContainText('No matching records')
  expect(state.commands).toEqual([])
})

test('switching source prevents delayed record responses from replacing the selected review', async ({ page }) => {
  const state = await sharedRecordsHarness(page)
  state.delayDetail = '17'
  await workspace(page).getByRole('button', { name: 'Review PR-17' }).click()
  await workspace(page).getByRole('combobox', { name: 'Source', exact: true }).selectOption('approved_hours')
  await workspace(page).getByRole('button', { name: 'Review TIME-18' }).click()
  await expect(review(page)).toContainText('Engineering hours')
  await expect(review(page).getByLabel('Selected employee')).toBeEnabled()
  await expect(review(page)).not.toContainText('Process study')
})

test('review is accessible and retains usable controls on a narrow screen', async ({ page }) => {
  const state = await sharedRecordsHarness(page)
  await chooseClient(page)
  const results = await new AxeBuilder({ page }).include('.shared-records-workspace').analyze()
  expect(results.violations).toEqual([])
  await mkdir('artifacts/shared-records', { recursive: true })
  await page.screenshot({ path: 'artifacts/shared-records/desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await reason(page).scrollIntoViewIfNeeded(); await expect(reason(page)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: 'artifacts/shared-records/mobile.png', fullPage: true })
  expect(state.app.pageErrors).toEqual([])
})

test('new project chooses an existing client and sends its canonical ID', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { query: 'view=portfolio' })
  await page.getByRole('button', { name: 'Create project', exact: true }).first().click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Selected client', { exact: true })).toBeEnabled()
  await dialog.getByLabel('Selected client', { exact: true }).selectOption('client-a')
  await expect(dialog.getByLabel('Client Name', { exact: true })).toHaveValue('Acme Engineering')
  await dialog.getByLabel('Project Name', { exact: true }).fill('Connected project')
  await dialog.getByLabel('Project Code', { exact: true }).fill('NEW-01')
  await dialog.getByRole('button', { name: 'Save Project', exact: true }).click()
  await expect.poll(() => state.creates.length).toBe(1)
  expect(state.creates[0].client_id).toBe('client-a')
})

test('project-hour entry selects a scoped employee and retains selection and input after rejection', async ({ page }) => {
  const state = await sharedRecordsHarness(page, { query: 'project=17&view=controls-periods', hoursFlow: true })
  state.hourFailure = 400
  await page.getByRole('button', { name: 'Enter project hours', exact: true }).click()
  const hours = page.getByRole('region', { name: 'Approved hours & reconciled actuals', exact: true })
  await expect(hours.getByLabel('Selected employee', { exact: true })).toBeEnabled()
  await hours.getByLabel('Selected employee', { exact: true }).selectOption('employee-a')
  await expect(hours.getByLabel('Employee code', { exact: true })).toHaveValue('E100')
  await expect(hours.getByLabel('Employee name', { exact: true })).toHaveValue('Alex Employee')
  await hours.getByRole('combobox', { name: 'Control Account', exact: true }).selectOption('account-1')
  await hours.getByRole('combobox', { name: 'Reporting period', exact: true }).selectOption('period-1')
  await hours.getByLabel('Work date', { exact: true }).fill('2026-10-01')
  await hours.getByLabel('Approved hours', { exact: true }).fill('8')
  await hours.getByLabel('Cost rate (AED/hour)', { exact: true }).fill('100')
  await hours.getByLabel('Source reference', { exact: true }).fill('TS-REVIEW-01')
  await hours.getByRole('button', { name: 'Create draft', exact: true }).click()
  await expect(page.getByText('Review the source reference.', { exact: true })).toBeVisible()
  await expect(hours.getByLabel('Selected employee', { exact: true })).toHaveValue('employee-a')
  await expect(hours.getByLabel('Source reference', { exact: true })).toHaveValue('TS-REVIEW-01')
  state.hourFailure = 0
  await hours.getByRole('button', { name: 'Create draft', exact: true }).click()
  await expect(hours.getByLabel('Selected employee', { exact: true })).toHaveCount(0)
  expect(state.hourCreates).toHaveLength(2)
  expect(state.hourCreates[1]).toMatchObject({ employee: 'employee-a', project: 17, hours: '8', source_reference: 'TS-REVIEW-01' })
  expect(state.hourCreates[1]).not.toHaveProperty('employee_code')
  expect(state.lookups).toContainEqual({ kind: 'employee', search: '', project_id: '17' })
})
