import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { verificationScopeMessage, wideTimelineHarness } from '../fixtures/wide-timeline.fixture.js'
import { scheduleAction, scheduleWorkspace, timelineScale } from '../fixtures/schedule-controls.js'

test.setTimeout(60000)
const grid = page => scheduleWorkspace(page).getByRole('region', { name: 'Schedule activities and Gantt', exact: true })
const row = (page, id) => grid(page).locator(`[data-row-id="${id}"]`)
const duration = (page, id) => row(page, id).locator('[data-column="duration"]')
const focusToggle = page => scheduleWorkspace(page).getByRole('button', { name: 'Focus timeline', exact: true })
const splitter = page => grid(page).getByRole('separator', { name: 'Resize activity table and Gantt', exact: true })
const clean = state => { expect(state.pageErrors).toEqual([]); expect(state.unknown).toEqual([]); expect(state.unknownWrites).toEqual([]); expect(state.writes).toEqual([]) }
async function open(page, options) {
  const state = await wideTimelineHarness(page, options)
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(state.records[17].simplePlan.tasks.length)
  return state
}
async function panes(page) {
  return grid(page).locator('.p6-heading').evaluate(element => {
    const table = element.querySelector('.p6-left-clip').getBoundingClientRect()
    const timeline = element.querySelector('.p6-right-clip').getBoundingClientRect()
    return { table: table.width, timeline: timeline.width, ratio: timeline.width / (table.width + timeline.width + 6) }
  })
}

test('desktop timeline receives approximately 60% width while project tabs and activity columns remain accessible', async ({ page }) => {
  await page.setViewportSize({ width: 1900, height: 950 })
  const state = await open(page, { realShell: true })
  const before = await panes(page)
  expect(before.ratio).toBeGreaterThan(.58)
  expect(before.ratio).toBeLessThan(.61)
  expect((await page.locator('.compact-real-shell').boundingBox()).x).toBe(198)
  const areas = page.getByRole('navigation', { name: 'Project work areas', exact: true })
  for (const name of ['Overview', 'Schedule', 'Cost & Commercial', 'Milestones', 'Risks & Changes', 'Estimates', 'Documents', 'Activity & Audit']) await expect(areas.getByRole('button', { name, exact: true })).toBeVisible()
  await page.locator('summary[aria-label="More project actions"]').click()
  await expect(page.locator('.pd-menu').getByRole('button', { name: 'EPC lifecycle', exact: true })).toBeVisible()
  await page.locator('summary[aria-label="More project actions"]').click()
  await expect(page.getByRole('combobox', { name: 'Project section', exact: true })).toHaveCount(0)
  const scroll = grid(page).getByLabel('Scroll activity columns', { exact: true })
  const maximumScroll = await scroll.evaluate(element => Math.max(0, element.scrollWidth - element.clientWidth))
  await scroll.evaluate(element => { element.scrollLeft = element.scrollWidth; element.dispatchEvent(new Event('scroll')) })
  await expect.poll(async () => Math.abs(await scroll.evaluate(element => element.scrollLeft) - maximumScroll)).toBeLessThanOrEqual(1)
  const pane = await grid(page).locator('.p6-heading .p6-left-clip').boundingBox()
  for (const name of ['Duration', 'Start', 'Finish', 'Total Float']) {
    const heading = grid(page).getByRole('columnheader', { name, exact: true })
    const box = await heading.boundingBox()
    expect(box.x).toBeGreaterThanOrEqual(pane.x - 1)
    expect(box.x + box.width).toBeLessThanOrEqual(pane.x + pane.width + 1)
  }
  await scroll.evaluate(element => { element.scrollLeft = 0; element.dispatchEvent(new Event('scroll')) })
  await page.screenshot({ path: '../artifacts/wide-timeline-desktop.png', animations: 'disabled' })
  clean(state)
})

test('timeline focus restores the chosen split and manual keyboard or pointer resize exits focus', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const state = await open(page)
  await expect(focusToggle(page)).toHaveAttribute('aria-pressed', 'false')
  const initial = await panes(page)
  await splitter(page).focus(); await page.keyboard.press('Shift+ArrowRight')
  const saved = await panes(page)
  expect(saved.table).toBeCloseTo(initial.table + 60, 0)
  await focusToggle(page).click()
  await expect(grid(page)).toHaveAttribute('data-timeline-focus', 'true')
  expect((await panes(page)).table).toBe(280)
  expect((await panes(page)).timeline).toBeGreaterThan(saved.timeline)
  await focusToggle(page).click()
  expect((await panes(page)).table).toBeCloseTo(saved.table, 0)
  await focusToggle(page).click()
  await splitter(page).focus(); await page.keyboard.press('ArrowRight')
  await expect(focusToggle(page)).toHaveAttribute('aria-pressed', 'false')
  expect((await panes(page)).table).toBe(300)
  await focusToggle(page).click()
  const drag = await splitter(page).boundingBox()
  await page.mouse.move(drag.x + 3, drag.y + 20); await page.mouse.down()
  await page.mouse.move(drag.x + 103, drag.y + 20, { steps: 4 }); await page.mouse.up()
  await expect(focusToggle(page)).toHaveAttribute('aria-pressed', 'false')
  expect((await panes(page)).table).toBeCloseTo(380, 0)
  await focusToggle(page).click(); await focusToggle(page).click()
  expect((await panes(page)).table).toBeCloseTo(380, 0)
  await splitter(page).dblclick()
  expect((await panes(page)).table).toBeCloseTo(initial.table, 0)
  clean(state)
})

test('keyboard focus on an offscreen date scrolls every activity and column header together', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const state = await open(page)
  await focusToggle(page).click()
  const task = state.records[17].simplePlan.tasks[0]
  const start = row(page, task.id).getByRole('button', { name: `Edit start for ${task.title}`, exact: true })
  await start.focus()
  await expect(start).toBeFocused()
  const scroll = grid(page).getByLabel('Scroll activity columns', { exact: true })
  await expect.poll(() => scroll.evaluate(element => element.scrollLeft)).toBeGreaterThan(0)
  const header = await grid(page).getByRole('columnheader', { name: 'Start', exact: true }).boundingBox()
  for (const id of ['activity-1', 'activity-2', 'activity-3']) {
    const cell = await row(page, id).locator('[data-column="start"]').boundingBox()
    expect(cell.x).toBeCloseTo(header.x, 1)
  }
  const independentClipOffsets = await grid(page).locator('.p6-left-clip').evaluateAll(elements => elements.map(element => element.scrollLeft))
  expect(independentClipOffsets.every(offset => offset === 0)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await panes(page)).timeline).toBeGreaterThanOrEqual(159)
  clean(state)
})

test('proposed task and WBS durations remain estimates and the legend only describes available data', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const state = await open(page, { proposed: true })
  await expect(grid(page).getByRole('columnheader', { name: 'Duration', exact: true })).toBeAttached()
  await expect(grid(page).getByRole('columnheader', { name: 'Original Duration', exact: true })).toHaveCount(0)
  await expect(duration(page, 'activity-1')).toHaveText('5 d')
  await expect(duration(page, 'activity-1')).toHaveAttribute('data-duration-kind', 'proposed')
  await expect(duration(page, '1111')).toHaveText('10 d')
  await expect(duration(page, '1111')).toHaveAttribute('data-duration-kind', 'proposed')
  await expect(duration(page, '1111')).toHaveAttribute('title', /Proposed calendar span.*not an imported original duration/)
  const legend = grid(page).getByRole('region', { name: 'Schedule sequence legend', exact: true })
  await expect(legend).toContainText('Milestone')
  await expect(legend).toContainText('Proposed durations')
  await expect(legend).not.toContainText('*')
  await expect(legend).not.toContainText(/Actual|Baseline|Remaining/)
  clean(state)
})

for (const projectOriginalOnly of [false, true]) test(`explicit ${projectOriginalOnly ? 'project-only' : 'WBS-row'} source original durations including summary 165 and milestone zero survive filters and zoom`, async ({ page }) => {
  await page.setViewportSize({ width: 1900, height: 950 })
  const state = await open(page, { originals: true, proposed: true, projectOriginalOnly })
  await expect(grid(page).getByRole('columnheader', { name: 'Original Duration', exact: true })).toBeAttached()
  await expect(duration(page, 1000)).toHaveText('165 d')
  await expect(duration(page, 1000)).toHaveAttribute('data-duration-kind', 'original')
  await expect(duration(page, 'activity-41')).toHaveText('0 d')
  await expect(duration(page, 'activity-41')).toHaveAttribute('data-duration-kind', 'original')
  await expect(row(page, 'activity-41').locator('.p6-milestone')).toHaveCount(1)
  const sourceSummary = structuredClone(state.records[17].simplePlan.project_summary)
  const search = scheduleWorkspace(page).getByRole('textbox', { name: 'Search schedule activities', exact: true })
  await search.fill('FEED-PRO')
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(2)
  await expect(duration(page, 1000)).toHaveText('165 d')
  await search.clear()
  for (const zoom of ['day', 'week', 'month']) {
    await timelineScale(page, zoom)
    await expect(duration(page, 1000)).toHaveText('165 d')
  }
  await focusToggle(page).click()
  await expect(duration(page, 1000)).toHaveText('165 d')
  expect(state.records[17].simplePlan.project_summary).toEqual(sourceSummary)
  clean(state)
})

test('220 exact register matches never certify source schedule dates, durations or calendar', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  const state = await open(page, { verification: 'missing_reference' })
  const before = structuredClone(state.records[17].simplePlan)
  const trigger = scheduleWorkspace(page).getByRole('button', { name: 'Verify schedule sources', exact: true })
  await expect(trigger).toHaveText('Unverified')
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Source verification', exact: true })
  await expect(dialog).toBeVisible()
  const register = dialog.getByRole('region', { name: 'Document register comparison', exact: true })
  await expect(register).toContainText('Exact register match')
  await expect(register).toContainText('220 of 220 parsed rows match')
  await expect(register).toContainText('This confirms register content only.')
  const summary = dialog.getByRole('region', { name: 'Current calculated summary', exact: true })
  await expect(summary).toContainText('193 working days')
  await expect(summary.locator('dl > div').filter({ has: page.getByText('Original schedule duration', { exact: true }) })).toContainText('Not verified')
  const checks = dialog.getByRole('region', { name: 'Schedule source checks', exact: true })
  await expect(checks).toContainText('Schedule unverified')
  await expect(checks).toContainText('No original reference schedule is uploaded.')
  for (const label of ['Dates compared with source', 'Dependencies compared with source']) await expect(checks.locator('dl > div').filter({ has: page.getByText(label, { exact: true }) })).toContainText('Not verified')
  await expect(checks.locator('dl > div').filter({ has: page.getByText('Verified source dates', { exact: true }) })).toContainText('0')
  await expect(checks).toContainText('220 proposed durations')
  await expect(checks).toContainText('4 inferred predecessor links')
  await expect(checks).toContainText('The original schedule calendar and its exceptions have not been verified.')
  const requirements = dialog.getByRole('region', { name: 'Source requirements', exact: true })
  await expect(requirements).toContainText(verificationScopeMessage)
  await expect(requirements).toContainText('Anchor unconfirmed')
  await expect(requirements).toContainText('Scope of Work.pdf · Page 14')
  await expect(dialog.getByRole('button', { name: /^(Save|Approve|Confirm|Import)$/ })).toHaveCount(0)
  const bounds = await dialog.boundingBox()
  expect(Math.abs(bounds.x + bounds.width / 2 - 720)).toBeLessThan(2)
  const scan = await new AxeBuilder({ page }).include('.psv-dialog').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  await page.screenshot({ path: '../artifacts/schedule-source-verification.png', animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await scheduleAction(page, 'Verify sources')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Project inputs', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: 'Documents & project inputs', exact: true })).toBeVisible()
  expect(state.records[17].simplePlan).toEqual(before)
  clean(state)
})

test('source verification shows missing, changed and extra register rows with their original citations on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const state = await open(page, { verification: 'mismatch' })
  await scheduleWorkspace(page).getByRole('button', { name: 'Verify schedule sources', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Source verification', exact: true })
  await expect(dialog).toContainText('218 of 220 parsed rows match')
  await expect(dialog).toContainText('Differences found')
  const rows = dialog.getByRole('region', { name: 'Register differences', exact: true }).locator('tbody tr')
  await expect(rows).toHaveCount(3)
  const verification = state.records[17].simplePlan.source_verification.document_register
  await expect(rows.nth(0)).toContainText('Missing from plan')
  await expect(rows.nth(0)).toContainText(verification.missing[0].title)
  await expect(rows.nth(1)).toContainText(verification.changed[0].expected_title)
  await expect(rows.nth(1)).toContainText(verification.changed[0].actual_title)
  await expect(rows.nth(1)).toContainText('Synthetic MDR.xlsx · MDR · Row 12')
  await expect(rows.nth(2)).toContainText('No source match')
  await expect(rows.nth(2)).toContainText('Additional planner review')
  const box = await dialog.boundingBox()
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  const scan = await new AxeBuilder({ page }).include('.psv-dialog').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  await dialog.getByRole('button', { name: 'Close source verification', exact: true }).click()
  clean(state)
})

test('an uploaded reference file remains explicitly not imported rather than a verified original schedule', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const state = await open(page, { verification: 'not_imported' })
  await scheduleWorkspace(page).getByRole('button', { name: 'Verify schedule sources', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Source verification', exact: true })
  const checks = dialog.getByRole('region', { name: 'Schedule source checks', exact: true })
  await expect(checks).toContainText('Uploaded; not imported')
  await expect(checks).toContainText('Reference schedule.xer')
  await expect(checks).toContainText('Uploaded text alone cannot establish an exact schedule match.')
  await expect(checks).toContainText('Schedule unverified')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  clean(state)
})

test('printed PDF dates and 165-day duration remain separate from the proposed 193-day plan', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const state = await open(page, { verification: 'not_imported', prepare: state => {
    state.records[17].simplePlan.source_verification.schedule_reference.printed_schedules = [{
      id: 904, name: 'Original Schedule.pdf', status: 'partial', activity_count: 1048,
      project_summary: { planned_start_date: '2026-01-06', planned_finish_date: '2026-09-04', original_duration_days: 165, source_locator: { page: 1, row: 1 } },
    }]
  } })
  const before = structuredClone(state.records[17].simplePlan)
  await scheduleWorkspace(page).getByRole('button', { name: 'Verify schedule sources', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Source verification', exact: true })
  const source = dialog.getByRole('region', { name: 'Printed schedule summary: Original Schedule.pdf', exact: true })
  await expect(source).toContainText('165 days as printed')
  await expect(source).toContainText('06-Jan-26')
  await expect(source).toContainText(/04-Sept?-26/)
  await expect(source).toContainText('Original Schedule.pdf · Page 1 · Row 1')
  await expect(source).toContainText('Unknown values remain unset.')
  await expect(dialog.getByRole('region', { name: 'Current calculated summary', exact: true })).toContainText('193 working days')
  await expect(dialog.getByRole('region', { name: 'Schedule source checks', exact: true })).toContainText('Schedule unverified')
  const scan = await new AxeBuilder({ page }).include('.psv-dialog').analyze()
  expect(scan.violations.filter(item => ['serious', 'critical'].includes(item.impact))).toEqual([])
  await page.screenshot({ path: '../artifacts/printed-schedule-versus-draft.png', animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  expect(state.records[17].simplePlan).toEqual(before)
  clean(state)
})
