import { test, expect } from '@playwright/test'
import { workflowProposalHarness } from '../fixtures/workflow-stage-tree.fixture.js'
import { scheduleWorkspace } from '../fixtures/schedule-controls.js'

test.setTimeout(60000)
const review = page => page.getByRole('dialog', { name: 'Review proposed schedule', exact: true })
const grid = page => scheduleWorkspace(page).getByRole('region', { name: 'Schedule activities and Gantt', exact: true })
const clean = state => { expect(state.pageErrors).toEqual([]); expect(state.unknownWrites).toEqual([]); expect(state.unknown).toEqual([]) }

test('Build schedule requests source evidence without forcing a workflow and preserves reviewed stage counts', async ({ page }) => {
  await page.setViewportSize({ width: 1740, height: 950 })
  const state = await workflowProposalHarness(page)
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(3)
  await scheduleWorkspace(page).getByRole('button', { name: 'Build schedule', exact: true }).click()
  await expect(review(page)).toBeVisible()
  expect(state.writes[0].data).toEqual({ revision: 4, workflow_mode: 'source_only' })
  await expect(review(page).locator('.psq-summary')).toContainText('3 deliverables')
  await expect(review(page).locator('.psq-summary')).toContainText('15 activities')
  await expect(review(page).locator('.psq-summary')).toContainText('5 stages per deliverable')
  await expect(review(page)).toContainText('IFR → Company Review → IFA → Company Approval → Final Issue')
  expect(state.workflowApplied).toBe(0)
  expect(state.records[17].simplePlan.tasks).toHaveLength(3)
  await review(page).getByRole('button', { name: 'Apply draft schedule', exact: true }).click()
  await expect(review(page)).toHaveCount(0)
  await expect(grid(page).locator('[data-row-kind="deliverable"]')).toHaveCount(3)
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(15)
  await expect(scheduleWorkspace(page).locator('.sc-footer')).toContainText('3 deliverables')
  await expect(scheduleWorkspace(page).locator('.sc-footer')).toContainText('15 activities')
  await expect(scheduleWorkspace(page).locator('.sc-footer')).toContainText('1 WBS groups')
  expect(state.workflowApplied).toBe(1)
  expect(state.writes[1].data).toEqual({ revision: 4, proposal_token: 'workflow-71-4' })
  const row = grid(page).locator('[data-row-id="source-a-COMPANY_REVIEW"]')
  await row.getByRole('button', { name: 'HVAC ADEQUEACY REPORT — Company Review', exact: true }).click()
  const drawer = page.getByRole('complementary', { name: 'Activity details', exact: true })
  await expect(drawer.locator('dl > div').filter({ has: page.getByText('Responsible role', { exact: true }) })).toContainText('Company')
  await drawer.getByRole('button', { name: 'Edit activity', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit task', exact: true })
  await expect(editor).toBeVisible()
  await expect(editor.getByRole('button', { name: 'Remove task', exact: true })).toHaveCount(0)
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  await drawer.getByRole('button', { name: 'Close activity details', exact: true }).click()
  const finalRow = grid(page).locator('[data-row-id="source-a-FINAL_ISSUE"]')
  await expect(finalRow.getByRole('button', { name: 'Edit duration for HVAC ADEQUEACY REPORT — Final Issue', exact: true })).toBeDisabled()
  await finalRow.getByRole('button', { name: 'HVAC ADEQUEACY REPORT — Final Issue', exact: true }).click()
  await drawer.getByRole('button', { name: 'Edit activity', exact: true }).click()
  const duration = editor.getByRole('spinbutton', { name: 'Duration (working days)', exact: true })
  await expect(duration).toHaveValue('0')
  await expect(duration).toHaveAttribute('readonly', '')
  expect(await duration.evaluate(element => element.checkValidity())).toBe(true)
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  clean(state)
})

test('workflow expansion blockers are visible once and prevent applying a partial conversion', async ({ page }) => {
  const state = await workflowProposalHarness(page, { blocked: true })
  const before = structuredClone(state.records[17].simplePlan)
  await scheduleWorkspace(page).getByRole('button', { name: 'Build schedule', exact: true }).click()
  await expect(review(page)).toBeVisible()
  const blockers = review(page).getByRole('alert', { name: 'Workflow expansion blockers', exact: true })
  await expect(blockers).toContainText('Review the completed HVAC deliverable before converting it into workflow tasks.')
  await expect(blockers.locator('li')).toHaveCount(1)
  await expect(review(page).getByRole('button', { name: 'Apply draft schedule', exact: true })).toBeDisabled()
  expect(state.records[17].simplePlan).toEqual(before)
  expect(state.workflowApplied).toBe(0)
  expect(state.writes).toHaveLength(1)
  await review(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(3)
  clean(state)
})

test('an existing workflow repair persists its dates and cross-deliverable links through Save and reload', async ({ page }) => {
  const state = await workflowProposalHarness(page, { existingSequence: true })
  const workspace = scheduleWorkspace(page)
  const firstStage = () => grid(page).locator('[data-row-id="source-b-IFR"]')
  const footer = () => workspace.locator('.sc-footer')
  await expect(footer()).toContainText('12 relationships')
  await expect(firstStage().locator('[data-column="start"]')).toHaveText('21-Sept-26')
  await workspace.getByRole('button', { name: 'Build schedule', exact: true }).click()
  await expect(review(page)).toBeVisible()
  await expect(review(page).locator('.psq-summary')).toContainText('14 predecessor links')
  // A preview does not save; the existing canvas retains the old network.
  expect(state.workflowApplied).toBe(0)
  expect(state.records[17].simplePlan.tasks.reduce((sum, task) => sum + task.depends_on.length, 0)).toBe(12)
  await review(page).getByRole('button', { name: 'Apply draft schedule', exact: true }).click()
  await expect(review(page)).toHaveCount(0)
  await expect(footer()).toContainText('14 relationships')
  await expect(firstStage().locator('[data-column="start"]')).toHaveText('05-Oct-26')
  const preserved = plan => plan.tasks.map(task => ({
    id: task.id, parent: task.parent_deliverable_id, stage: task.workflow_stage_code,
    start: task.planned_start_date, finish: task.planned_finish_date,
    depends_on: task.depends_on, dependency_details: task.dependency_details,
  }))
  const applied = preserved(state.records[17].simplePlan)
  const proposal = structuredClone(state.records[17].simplePlan.schedule_proposal)
  await workspace.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => state.writes.filter(write => write.method === 'PUT').length).toBe(1)
  await expect(footer()).toContainText('Changes saved')
  expect(preserved(state.records[17].simplePlan)).toEqual(applied)
  expect(state.records[17].simplePlan.schedule_proposal).toEqual(proposal)
  expect(state.records[17].simplePlan.deliverables).toHaveLength(3)
  const sent = state.writes.find(write => write.method === 'PUT').data.tasks
  expect(sent.find(task => task.id === 'source-b-IFR')).toMatchObject({ planned_start_date: '2026-10-05', depends_on: ['source-a-FINAL_ISSUE'] })
  await page.reload()
  await expect(grid(page).locator('[data-row-kind="task"]')).toHaveCount(15)
  await expect(footer()).toContainText('14 relationships')
  await expect(firstStage().locator('[data-column="start"]')).toHaveText('05-Oct-26')
  expect(preserved(state.records[17].simplePlan)).toEqual(applied)
  expect(state.workflowApplied).toBe(1)
  clean(state)
})
