/* eslint-disable react/prop-types */
import { ArrowPathIcon, ChevronLeftIcon, ChevronRightIcon } from '@heroicons/react/24/outline';
import { RouteLink } from './ExecutivePrimitives';
import { formatDate } from './executivePresentation';
import { revenueDecimal, revenueIdentity, revenueMoney } from './portfolioRevenuePresentation';
import { INVOICE_TOTALS, RECORDED_INVOICE_STATUSES, portfolioSourceRoute, recordedCurrency, recordedMetricNote, recordedMetricValue } from './portfolioInvoicePresentation';
import './PortfolioRecordConnections.css';

export function RecordedInvoiceState({ state, onRefreshWorkbook }) {
  if (state.loading && !state.data) return <p className="prc-state" role="status"><ArrowPathIcon className="cc-spinning" aria-hidden="true" />Loading recorded outgoing invoices…</p>;
  if (state.error) return <div className="prc-state" role="alert"><p>{state.error.message}</p>{state.error.status !== 403 && <button type="button" className="cc-text-button" onClick={state.error.status === 409 ? onRefreshWorkbook : state.retry}>{state.error.status === 409 ? 'Refresh portfolio source' : 'Retry recorded invoices'}</button>}</div>;
  if (!RECORDED_INVOICE_STATUSES.has(state.data?.status)) return <p className="prc-state">{state.data?.status === 'restricted' ? 'Outgoing invoice access is restricted.' : state.data?.description || 'Recorded outgoing invoices are not available for this portfolio scope.'}</p>;
  return null;
}

function RecordedMoney({ metric, currency }) {
  return <><strong>{recordedCurrency(currency)} {revenueMoney(recordedMetricValue(metric))}</strong><small>{recordedMetricNote(metric)}</small></>;
}

export default function PortfolioRecordedInvoices({ state, connections, onRefreshWorkbook, onReviewConnections, printing = false }) {
  const source = state.data;
  const readable = RECORDED_INVOICE_STATUSES.has(source?.status);
  const coverage = source?.coverage || {};
  const rows = source?.rows || [];
  const count = source?.total_rows ?? coverage.invoice_count;
  const pages = Math.max(1, Math.ceil(Number(count || 0) / state.pageSize));
  const connectionRows = connections?.rows || [];
  return <section className="prv-panel prc-invoices" data-testid="portfolio-recorded-invoices" aria-label="Recorded outgoing invoices" aria-busy={state.loading}>
    <header className="prv-panel-heading"><div><h2>Recorded outgoing invoices</h2><p>Current Finance records · All recorded invoice dates · Original currencies</p></div>{readable && <RouteLink route={portfolioSourceRoute(source.source?.route)} arrow>Open Outgoing Invoices</RouteLink>}</header>
    <RecordedInvoiceState state={state} onRefreshWorkbook={onRefreshWorkbook} />
    {readable && <>
      <p className="prv-note">{source.description || source.source?.description || 'Current recorded receipts and balances are not a historical balance at the workbook reporting cutoff. No currency conversion or VAT basis is assumed.'}{source.source?.as_of_date ? ` As of ${formatDate(source.source.as_of_date)}.` : ''}</p>
      <div className="prc-currency-totals">{(source.totals_by_currency || []).map(group => <section key={group.currency} aria-label={`${recordedCurrency(group.currency)} invoice totals`}><header><h3>{recordedCurrency(group.currency)}</h3><span>{revenueDecimal(group.included_invoice_count ?? group.invoice_count)} included of {revenueDecimal(group.invoice_count)} invoices</span></header><div>{INVOICE_TOTALS.map(([key, label]) => <div key={key}><span>{label}</span><RecordedMoney metric={group[key]} currency={group.currency} /></div>)}</div></section>)}</div>
      {!(source.totals_by_currency || []).length && <p className="prv-note">No included invoices have a recorded currency in this scope.</p>}
      <div className="prc-coverage" aria-label="Invoice linkage coverage"><span><strong>{revenueDecimal(coverage.matched_source_identity_count)}</strong> exact source identities linked</span><span><strong>{revenueDecimal(coverage.unmatched_source_identity_count)}</strong> without an exact invoice link</span><span><strong>{revenueDecimal(coverage.parent_only_project_count)}</strong> parent-only invoice groups</span><span><strong>{revenueDecimal(coverage.conflicting_invoice_count)}</strong> conflicting invoices</span>{onReviewConnections && <button type="button" className="cc-text-button" onClick={onReviewConnections}>Review project connections</button>}</div>
      <p className="prv-note">Totals include unambiguous, non-cancelled invoices and exclude credit notes. An absent invoice link does not establish zero invoicing. Parent-level invoices remain unallocated to individual subprojects.{Number(coverage.excluded_invoice_count) > 0 ? ` ${revenueDecimal(coverage.excluded_invoice_count)} cancelled or credit-note records are excluded from totals.` : ''}{Number(coverage.withheld_parent_project_count) > 0 ? ` ${revenueDecimal(coverage.withheld_parent_project_count)} parent groups are withheld in this scope.` : ''}</p>
      {source.project_groups?.length > 0 && <details className="prc-groups"><summary>Invoices by project reference ({source.project_groups.length})</summary><div className="prv-table-wrap" tabIndex={0} role="region" aria-label="Recorded invoice project links"><table><caption className="cc-sr-only">Source project references and matching recorded invoice groups</caption><thead><tr><th scope="col">Project reference</th><th scope="col">Match</th><th scope="col">Invoices</th><th scope="col">Conflicts</th><th scope="col">Linked records</th></tr></thead><tbody>{source.project_groups.map((group, index) => { const linked = connectionRows.find(row => row.project_code === group.project_code && row.subproject_code === group.subproject_code); return <tr key={`${group.project_number}-${index}`}><th scope="row">{group.project_number || revenueIdentity(group)}</th><td>{group.match_level === 'parent' ? 'Parent only · unallocated' : 'Exact subproject'}</td><td>{revenueDecimal(group.invoice_count)}</td><td>{revenueDecimal(group.conflict_count)}</td><td><div className="prc-links"><RouteLink route={portfolioSourceRoute(group.register_route)}>Open invoices</RouteLink><RouteLink route={portfolioSourceRoute(linked?.project?.url)}>Open project</RouteLink></div></td></tr>; })}</tbody></table></div></details>}
      <div className="prc-register-heading"><h3>Invoice register</h3><span>{revenueDecimal(count)} recorded rows</span></div>
      {state.loading ? <p role="status" className="prc-state">Updating invoice page…</p> : rows.length ? <div className="prv-table-wrap" tabIndex={0} role="region" aria-label="Recorded outgoing invoice register"><table className="prc-invoice-table"><caption className="cc-sr-only">Current recorded outgoing invoices in their original currency; each detail link opens its verified invoice record</caption><thead><tr>{['Invoice', 'Project reference', 'Invoice date', 'Due date', 'Currency', 'Invoice amount', 'Receipts', 'Outstanding', 'Status / linkage', 'Action'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.id ?? 'unresolved'}-${row.invoice_number}-${index}`}><th scope="row">{row.invoice_number || 'Not recorded'}</th><td>{row.rad_project_no || row.project_id || revenueIdentity(row)}<small>{row.match_level === 'parent' ? 'Parent-only invoice' : row.subproject_code}</small></td><td>{formatDate(row.invoice_date)}</td><td>{formatDate(row.due_date)}</td><td>{recordedCurrency(row.currency)}</td><td>{revenueMoney(row.invoice_amount)}</td><td>{revenueMoney(row.actual_payment_received)}</td><td>{revenueMoney(row.calculated_receivable_balance)}</td><td>{String(row.payment_status || 'Not recorded').replaceAll('_', ' ')}<small>{row.match_status === 'conflict' ? `Needs review${row.conflict_codes?.length ? ` · ${row.conflict_codes.join(', ').replaceAll('_', ' ')}` : ''}` : row.match_level === 'parent' ? 'Unallocated to subprojects' : 'Matched project reference'}</small></td><td>{portfolioSourceRoute(row.detail_route) ? <RouteLink route={portfolioSourceRoute(row.detail_route)}>Open invoice</RouteLink> : <span className="prc-muted">Detail unavailable</span>}</td></tr>)}</tbody></table></div> : <p className="prv-note">No recorded invoices match the authorized portfolio references.</p>}
      {!printing && <div className="prv-pagination"><span>{rows.length ? `${state.page * state.pageSize + 1}–${state.page * state.pageSize + rows.length} of ${revenueDecimal(count)} invoices` : 'No invoice rows'}</span><nav aria-label="Recorded invoice pages"><button type="button" aria-label="Previous recorded invoice page" disabled={state.loading || state.page === 0} onClick={() => state.setPage(state.page - 1)}><ChevronLeftIcon aria-hidden="true" /></button><span>Page {state.page + 1} of {pages}</span><button type="button" aria-label="Next recorded invoice page" disabled={state.loading || state.page + 1 >= pages} onClick={() => state.setPage(state.page + 1)}><ChevronRightIcon aria-hidden="true" /></button></nav><span>Totals cover included matching invoices only</span></div>}
      {printing && Number(count) > rows.length && <p className="prv-note">This printout includes {rows.length} of {revenueDecimal(count)} invoice rows. Totals cover included matching invoices only; conflicts, cancelled invoices and credit notes are excluded.</p>}
    </>}
  </section>;
}
