import { useEffect, useState } from 'react'
import PropTypes from 'prop-types'
import PlanningDelayPaths from './PlanningDelayPaths'
import { controlsList as list, controlsLabel as label, controlsValue as value } from './planningControlsPresentation'

function ImpactResult({ result, title }) {
  const [search, setSearch] = useState(''), [page, setPage] = useState(0)
  const rows = list(result?.affected_activities).filter(row => `${row.external_id} ${row.name}`.toLowerCase().includes(search.trim().toLowerCase()))
  return <section className="poc-section" aria-label={title}><h4>{title}</h4><p>Status: {label(result?.status)}</p><dl className="poc-metrics"><div><dt>Forecast finish</dt><dd>{label(result?.forecast_finish)}</dd></div><div><dt>Net finish shift</dt><dd>{value(result?.net_finish_shift_calendar_days, ' calendar days')}</dd></div><div><dt>Contractual finish overrun</dt><dd>{value(result?.contract_overrun_calendar_days, ' calendar days')}</dd></div>{result && 'recovered_calendar_days' in result && <div><dt>Proposed recovery</dt><dd>{value(result.recovered_calendar_days, ' calendar days')}</dd></div>}</dl>
    <label>Find affected activity<input aria-label={`Find ${title} activity`} value={search} onChange={e => { setSearch(e.target.value); setPage(0) }} /></label><div className="poc-table" role="region" aria-label={`${title} activity comparison`} tabIndex={0}><table><thead><tr>{['Activity', 'Reference start', 'Reference finish', 'Scenario start', 'Scenario finish', 'Start shift (calendar d)', 'Finish shift (calendar d)', 'Reference float (d)', 'Scenario float (d)'].map(text => <th key={text}>{text}</th>)}</tr></thead><tbody>{rows.slice(page * 25, (page + 1) * 25).map(row => <tr key={row.activity_id}><th scope="row">{row.external_id || row.activity_id}<span>{row.name}</span></th><td>{label(row.reference_start)}</td><td>{label(row.reference_finish)}</td><td>{label(row.scenario_start)}</td><td>{label(row.scenario_finish)}</td><td>{value(row.start_shift_calendar_days)}</td><td>{value(row.finish_shift_calendar_days)}</td><td>{value(row.reference_float)}</td><td>{value(row.scenario_float)}</td></tr>)}{!rows.length && <tr><td colSpan={9}>No affected activity rows reported for this selection.</td></tr>}</tbody></table></div><div className="poc-pagination"><span>{rows.length} matching activities · Page {page + 1}</span><button type="button" aria-label={`Previous ${title} results`} disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button type="button" aria-label={`Next ${title} results`} disabled={(page + 1) * 25 >= rows.length} onClick={() => setPage(page + 1)}>Next</button></div>
    {list(result?.affected_milestones).length > 0 && <details><summary>Affected milestones ({result.affected_milestones.length})</summary><ul>{result.affected_milestones.map((row, index) => <li key={row.activity_id || index}>{row.external_id || row.activity_id} · {row.name} — {label(row.reference_finish)} → {label(row.scenario_finish)} · {value(row.finish_shift_calendar_days, ' calendar days')}</li>)}</ul></details>}
    {result?.paths && <PlanningDelayPaths paths={result.paths} title={title} />}
  </section>
}
ImpactResult.propTypes = { result: PropTypes.object, title: PropTypes.string.isRequired }

export default function PlanningDelayReview({ data, busy, dirty, readOnly, onCommand, onExport }) {
  const [reason, setReason] = useState('')
  const current = data.case, result = current?.run?.result, permissions = current?.permissions || {}
  useEffect(() => setReason(''), [current?.id, current?.revision])
  if (!current) return <p>Create or select a delay case to review calculated impact.</p>
  const decision = async action => {
    const response = await onCommand(action, { case_id: current.id, ...(action === 'revise_case' ? {} : { revision: current.revision, source_fingerprint: current.source_fingerprint }), reason: reason.trim() }, action === 'approve_case' ? 'Internal recommendation approved. No contractual entitlement was awarded and no baseline dates were changed.' : action === 'reject_case' ? 'Internal recommendation rejected with the review reason. The reviewed case remains preserved.' : action === 'submit_case' ? 'Case submitted for independent review.' : action === 'revise_case' ? 'A separate revision draft is open. The earlier reviewed case is preserved.' : 'Case returned for correction.')
    if (response) setReason('')
  }
  const allowed = key => permissions[key] === true && !busy && !dirty && !readOnly && (!['can_submit', 'can_approve'].includes(key) || !current.source_stale)
  const issues = [...list(data.issues), ...list(current.issues), ...list(result?.issues)]
  return <section className="pda-review" aria-label="Delay impact and recommendation review"><header><div><h3>Impact and recommendation review</h3><p>{current.name} · {label(current.status)} · Revision {current.revision}</p></div><div className="poc-actions">{permissions.can_calculate && <button type="button" className="poc-primary" disabled={!allowed('can_calculate')} onClick={() => onCommand('calculate_case', { case_id: current.id, revision: current.revision }, 'Impact and recovery comparisons calculated against the published reference. Schedule and baseline remain unchanged.')}>Calculate impact and alternatives</button>}{permissions.can_export && ['json', 'xlsx'].map(format => <button key={format} type="button" disabled={busy || dirty} onClick={() => onExport(format)}>Download case {format.toUpperCase()}</button>)}</div></header>
    {dirty && <p className="poc-message is-warning">Save the case inputs before calculating or making a review decision.</p>}{current.source_stale && <p className="poc-message is-warning">This case refers to changed source evidence. Review the changes and recalculate before submitting.</p>}
    <p>Calculated technical impact is a scenario comparison. Proposed recovery and requested extensions are not measured progress or approved entitlement. Internal approval does not apply changes to the Master Schedule.</p><p>Positive finish shifts mean later completion. Positive recovery means improvement against the combined impact case; overlapping event effects are evaluated together.</p>
    {result ? <><section className="poc-section" aria-label="Published delay reference"><span className="pda-badge">Published reference</span><dl className="poc-metrics"><div><dt>Published report</dt><dd>{result.reference?.report_id ?? current.reference_report_id}</dd></div><div><dt>Data date</dt><dd>{label(result.reference?.data_date)}</dd></div><div><dt>Reference forecast finish</dt><dd>{label(result.reference?.forecast_finish)}</dd></div><div><dt>Contractual finish</dt><dd>{label(result.reference?.contractual_finish)}</dd></div></dl><p>Method: {label(result.method)}</p></section>
      <div className="poc-table" role="region" aria-label="Impact and recovery comparison" tabIndex={0}><table><thead><tr><th>Alternative</th><th>Basis</th><th>Status</th><th>Forecast finish</th><th>Net finish shift</th><th>Proposed recovery</th><th>Contract overrun</th></tr></thead><tbody><tr><th scope="row">Combined impact</th><td>Calculated technical impact</td><td>{label(result.impact?.status)}</td><td>{label(result.impact?.forecast_finish)}</td><td>{value(result.impact?.net_finish_shift_calendar_days, ' calendar d')}</td><td>Not applicable</td><td>{value(result.impact?.contract_overrun_calendar_days, ' calendar d')}</td></tr>{list(result.scenarios).map(row => <tr key={row.id}><th scope="row">{row.name}</th><td><span className="pda-badge is-proposed">Proposed recovery</span></td><td>{label(row.status)}</td><td>{label(row.forecast_finish)}</td><td>{value(row.net_finish_shift_calendar_days, ' calendar d')}</td><td>{value(row.recovered_calendar_days, ' calendar d')}</td><td>{value(row.contract_overrun_calendar_days, ' calendar d')}</td></tr>)}</tbody></table></div><ImpactResult title="Combined impact" result={result.impact} />{list(result.scenarios).map(row => <ImpactResult key={row.id} title={`Recovery: ${row.name}`} result={row} />)}
      {list(result.limitations).length > 0 && <details open><summary>Calculation limits</summary><ul>{result.limitations.map((item, index) => <li key={index}>{typeof item === 'string' ? item : item.message || label(item.code)}</li>)}</ul></details>}
    </> : <p className="poc-message">No calculation is recorded for this case. Enter evidence-supported changes, save them, then calculate their combined effect.</p>}
    {issues.length > 0 && <ul className="poc-issues">{issues.map((item, index) => <li key={index}>{typeof item === 'string' ? item : item.message || label(item.code)}</li>)}</ul>}
    {list(current.run?.events).length > 0 && <details className="poc-section"><summary>Event evidence frozen with this calculation</summary>{current.run.events.map(event => <section key={event.id}><h4>{event.title} · Revision {event.revision}</h4><p>{event.description}</p><p>{label(event.start_date)} → {label(event.end_date)}</p>{list(event.evidence).map((item, index) => <p key={index}>{item.reference}{item.document_version_id && <small> · Document version {item.document_version_id}</small>}{item.fact_id && <small> · Evidence fact {item.fact_id}</small>}</p>)}</section>)}</details>}
    <section className="poc-section" aria-label="Internal delay recommendation"><h4>Internal recommendation</h4><dl className="poc-metrics"><div><dt>Selected recovery</dt><dd>{list(current.scenarios).find(row => row.id === current.recommendation?.selected_scenario_id)?.name || 'Not Specified'}</dd></div><div><dt>Requested extension</dt><dd>{value(current.recommendation?.requested_extension_calendar_days, ' calendar days')}</dd></div><div><dt>Entitlement</dt><dd>Not awarded by this review</dd></div></dl>{current.recommendation && <details><summary>Saved recommendation basis and references</summary><dl>{Object.entries(current.recommendation).filter(([key]) => !['selected_scenario_id', 'requested_extension_calendar_days'].includes(key)).map(([key, item]) => <div key={key}><dt>{label(key)}</dt><dd>{label(item)}</dd></div>)}</dl></details>}{(result?.recommendation_assessment || current.recommendation_assessment) && <details><summary>Recommendation assessment</summary><pre className="pda-json">{JSON.stringify(result?.recommendation_assessment || current.recommendation_assessment, null, 2)}</pre></details>}
      {current.reviewed_by_id != null && <p>Reviewed by user {current.reviewed_by_id} · {label(current.reviewed_at)}</p>}{current.reason && <div><strong>Recorded decision reason</strong><p>{current.reason}</p></div>}
      {!readOnly && ['can_submit', 'can_approve', 'can_return', 'can_revise'].some(key => permissions[key]) && <><label>Review reason<textarea aria-label="Delay case review reason" value={reason} onChange={e => setReason(e.target.value)} /></label><div className="poc-actions">{[['can_submit', 'submit_case', 'Submit case for review'], ['can_approve', 'approve_case', 'Approve internal recommendation'], ['can_approve', 'reject_case', 'Reject recommendation'], ['can_return', 'return_case', 'Return case for correction'], ['can_revise', 'revise_case', 'Create case revision']].filter(([key]) => permissions[key]).map(([key, action, title]) => <button key={action} type="button" disabled={!allowed(key) || !reason.trim()} onClick={() => decision(action)}>{title}</button>)}</div></>}{current.status === 'submitted' && !permissions.can_approve && <p>An authorised independent reviewer must approve this recommendation.</p>}
    </section>{current.source_fingerprint && <details><summary>Case source fingerprint</summary><code>{current.source_fingerprint}</code>{current.run?.fingerprint && <code>Calculation: {current.run.fingerprint}</code>}</details>}
  </section>
}
PlanningDelayReview.propTypes = { data: PropTypes.object.isRequired, busy: PropTypes.bool, dirty: PropTypes.bool, readOnly: PropTypes.bool, onCommand: PropTypes.func.isRequired, onExport: PropTypes.func.isRequired }
