import PropTypes from 'prop-types'
import PlanningDelayActivityPicker from './PlanningDelayActivityPicker'
import { controlsList as list, controlsNumber as numeric } from './planningControlsPresentation'

export const serializeDelayChanges = rows => rows.map(row => ({ event_id: row.event_id, field: row.field, evidence: row.evidence.trim(), reason: row.reason.trim(), ...(row.field === 'relationship' ? { predecessor_id: row.predecessor_id, successor_id: row.successor_id, expected_before: row.expected_before == null ? null : { type: row.expected_before.type, lag_days: numeric(row.expected_before.lag_days) }, value: row.value == null ? null : { type: row.value.type, lag_days: numeric(row.value.lag_days) } } : { activity_id: row.activity_id, expected_before: row.field === 'remaining_duration_days' ? numeric(row.expected_before) : row.expected_before || null, value: row.field === 'remaining_duration_days' ? numeric(row.value) : row.value || null }) }))

export const validDelayChanges = rows => rows.every(row => row.event_id && row.field && row.evidence?.trim() && row.reason?.trim() && (row.field === 'relationship' ? row.predecessor_id && row.successor_id && (row.expected_before == null || (row.expected_before.type && numeric(row.expected_before.lag_days) != null)) && (row.value == null || (row.value.type && numeric(row.value.lag_days) != null)) && !(row.expected_before == null && row.value == null) : row.activity_id && row.value !== '' && (row.value != null || (row.field === 'remaining_not_before' && row.expected_before)) ))

function referenceValue(row, caseData, impacts) {
  const same = change => change.field === row.field && (row.field === 'relationship' ? String(change.predecessor_id) === String(row.predecessor_id) && String(change.successor_id) === String(row.successor_id) : String(change.activity_id) === String(row.activity_id))
  const impact = list(impacts).findLast(same)
  if (impact) return impact.value
  if (row.field === 'relationship') {
    const relation = list(caseData.reference_relationships).find(item => String(item.predecessor_id) === String(row.predecessor_id) && String(item.successor_id) === String(row.successor_id))
    return relation ? { type: relation.type || relation.relationship_type || '', lag_days: relation.lag_days ?? '' } : null
  }
  return list(caseData.reference_observations).find(item => String(item.activity_id) === String(row.activity_id))?.[row.field] ?? null
}

function RelationshipValue({ value, onChange, title, nullableLabel }) {
  return <fieldset className="pda-relationship"><legend>{title}</legend><label className="poc-check"><input type="checkbox" checked={value == null} onChange={e => onChange(e.target.checked ? null : { type: '', lag_days: '' })} />{nullableLabel}</label>{value != null && <div className="poc-fields"><label>Relationship<select aria-label={`${title} relationship type`} required value={value.type || ''} onChange={e => onChange({ ...value, type: e.target.value })}><option value="">Select type</option>{['FS', 'SS', 'FF', 'SF'].map(type => <option key={type}>{type}</option>)}</select></label><label>Lag (whole working days)<input type="number" step="1" aria-label={`${title} lag`} required value={value.lag_days ?? ''} onChange={e => onChange({ ...value, lag_days: e.target.value })} /></label></div>}</fieldset>
}
RelationshipValue.propTypes = { value: PropTypes.object, onChange: PropTypes.func.isRequired, title: PropTypes.string.isRequired, nullableLabel: PropTypes.string.isRequired }

export default function PlanningDelayChanges({ title, rows, onChange, activities, events, caseData, impactChanges, disabled }) {
  const update = (index, field, value) => onChange(rows.map((row, at) => {
    if (at !== index) return row
    let next = { ...row, [field]: value }
    if (field === 'field') next = { event_id: row.event_id, activity_id: '', predecessor_id: '', successor_id: '', field: value, expected_before: null, value: value === 'relationship' ? { type: '', lag_days: '' } : '', evidence: row.evidence, reason: row.reason }
    if (field === 'event_id') {
      const event = events.find(item => String(item.id) === String(value)), target = row.field === 'relationship' ? 'successor_id' : 'activity_id'
      if (next[target] && !list(event?.activity_ids).some(id => String(id) === String(next[target]))) { next[target] = ''; next.expected_before = null }
    }
    if (['activity_id', 'predecessor_id', 'successor_id'].includes(field)) next.expected_before = referenceValue(next, caseData, impactChanges)
    return next
  }))
  return <section className="pda-changes" aria-label={title}><header><h4>{title}</h4><button type="button" disabled={disabled} onClick={() => onChange([...rows, { event_id: '', activity_id: '', field: '', expected_before: null, value: '', evidence: '', reason: '' }])}>Add {title.toLowerCase()} change</button></header>
    <p>Reference values are copied only from the selected published report{impactChanges ? ' or the recorded impact changes' : ''}. Check the expected value before saving. No dates are calculated in this form.</p>
    {!rows.length && <p>No {title.toLowerCase()} changes specified.</p>}
    {rows.map((row, index) => { const event = events.find(item => String(item.id) === String(row.event_id)), eventActivities = activities.filter(item => list(event?.activity_ids).some(id => String(id) === String(item.id))); return <fieldset disabled={disabled} className="pda-change" key={index}><legend>{title} change {index + 1}</legend><div className="poc-fields"><label>Related event<select aria-label={`${title} event ${index + 1}`} required value={row.event_id || ''} onChange={e => update(index, 'event_id', e.target.value ? events.find(event => String(event.id) === e.target.value)?.id ?? e.target.value : '')}><option value="">Select recorded event</option>{events.map(event => <option key={event.id} value={event.id}>{event.title} · Revision {event.revision}</option>)}</select></label><label>Change field<select aria-label={`${title} field ${index + 1}`} required value={row.field} onChange={e => update(index, 'field', e.target.value)}><option value="">Choose explicit change</option><option value="remaining_duration_days">Remaining duration</option><option value="remaining_not_before">Remaining work cannot start before</option><option value="relationship">Dependency relationship (advanced)</option></select></label></div>
      {row.field === 'relationship' ? <><div className="poc-fields"><PlanningDelayActivityPicker activities={activities} value={row.predecessor_id} multiple={false} title={`${title} predecessor ${index + 1}`} onChange={value => update(index, 'predecessor_id', value)} /><PlanningDelayActivityPicker activities={eventActivities} value={row.successor_id} multiple={false} title={`${title} successor ${index + 1}`} onChange={value => update(index, 'successor_id', value)} /></div><div className="poc-fields"><RelationshipValue title={`${title} expected ${index + 1}`} nullableLabel="No existing relationship" value={row.expected_before} onChange={value => update(index, 'expected_before', value)} /><RelationshipValue title={`${title} proposed ${index + 1}`} nullableLabel="Remove this relationship" value={row.value} onChange={value => update(index, 'value', value)} /></div><p>Relationship types and whole working-day lags are explicit scenario inputs. Actual progress and baseline logic remain unchanged.</p></> : row.field && <><PlanningDelayActivityPicker activities={eventActivities} value={row.activity_id} multiple={false} title={`${title} activity ${index + 1}`} onChange={value => update(index, 'activity_id', value)} /><div className="poc-fields"><label>Expected before{row.field === 'remaining_duration_days' ? ' (whole working days)' : ''}<input aria-label={`${title} expected before ${index + 1}`} type={row.field === 'remaining_duration_days' ? 'number' : 'date'} step={row.field === 'remaining_duration_days' ? '1' : undefined} min={row.field === 'remaining_duration_days' ? '0' : undefined} placeholder="Not Specified" value={row.expected_before ?? ''} onChange={e => update(index, 'expected_before', e.target.value)} /></label><label>Proposed value{row.field === 'remaining_duration_days' ? ' (whole working days)' : ''}<input aria-label={`${title} proposed value ${index + 1}`} required={row.value !== null} disabled={row.field === 'remaining_not_before' && row.value === null} type={row.field === 'remaining_duration_days' ? 'number' : 'date'} step={row.field === 'remaining_duration_days' ? '1' : undefined} min={row.field === 'remaining_duration_days' ? '0' : undefined} value={row.value ?? ''} onChange={e => update(index, 'value', e.target.value)} /></label></div>{row.field === 'remaining_not_before' && <label className="poc-check"><input aria-label={`${title} remove hold ${index + 1}`} type="checkbox" checked={row.value === null} onChange={e => update(index, 'value', e.target.checked ? null : '')} />Remove the recorded hold boundary</label>}<p>{row.field === 'remaining_duration_days' ? 'Remaining duration uses whole working days on the frozen reference calendar.' : 'This date is an explicit hold or restart boundary for remaining work; it does not replace actual dates.'}</p></>}
      <div className="poc-fields"><label>Evidence reference<input aria-label={`${title} evidence ${index + 1}`} required value={row.evidence} onChange={e => update(index, 'evidence', e.target.value)} /></label><label>Technical reason<input aria-label={`${title} reason ${index + 1}`} required value={row.reason} onChange={e => update(index, 'reason', e.target.value)} /></label></div><button type="button" onClick={() => onChange(rows.filter((_, at) => at !== index))}>Remove {title.toLowerCase()} change {index + 1}</button>
    </fieldset> })}
  </section>
}
PlanningDelayChanges.propTypes = { title: PropTypes.string.isRequired, rows: PropTypes.array.isRequired, onChange: PropTypes.func.isRequired, activities: PropTypes.array.isRequired, events: PropTypes.array.isRequired, caseData: PropTypes.object.isRequired, impactChanges: PropTypes.array, disabled: PropTypes.bool }
