import { useState } from 'react'
import PropTypes from 'prop-types'
import PlanningDelayActivityPicker from './PlanningDelayActivityPicker'
import { controlsList as list, controlsLabel as label } from './planningControlsPresentation'

export default function PlanningDelayEventForm({ data, event, busy, onCommand, onClose }) {
  const [draft, setDraft] = useState({ title: event?.title || '', description: event?.description || '', start_date: event?.start_date || '', end_date: event?.end_date || '', status: event?.status || 'recorded', activity_ids: event?.activity_ids || [], evidence: list(event?.evidence).length ? event.evidence : [{ reference: '' }], governance_item_id: event?.governance_item_id || '', risk_id: event?.risk_id || '', reason: '' })
  const change = (field, value) => setDraft(current => ({ ...current, [field]: value }))
  const save = async e => {
    e.preventDefault()
    const payload = { title: draft.title.trim(), description: draft.description.trim(), start_date: draft.start_date || null, end_date: draft.end_date || null, activity_ids: draft.activity_ids, evidence: draft.evidence.map(row => ({ ...row, reference: row.reference.trim() })), governance_item_id: draft.governance_item_id || null, risk_id: draft.risk_id || null }
    const result = await onCommand(event ? 'update_event' : 'create_event', { ...payload, ...(event ? { event_id: event.id, revision: event.revision, status: draft.status, reason: draft.reason.trim() } : { baseline_id: data.baseline.id }) }, event ? 'Event updated. Existing impact calculations must be reviewed against this revision.' : 'Delay event recorded with its evidence. No schedule dates were changed.')
    if (result) onClose()
  }
  return <form className="poc-section" aria-label={event ? 'Edit delay event' : 'Record delay event'} onSubmit={save}><h3>{event ? 'Edit delay event' : 'Record delay event'}</h3><p>Record what happened and its evidence. Event dates do not automatically become delay days or establish entitlement.</p><fieldset disabled={busy}><div className="poc-fields"><label>Event title<input aria-label="Delay event title" required value={draft.title} onChange={e => change('title', e.target.value)} /></label>{event && <label>Status<select aria-label="Delay event status" value={draft.status} onChange={e => change('status', e.target.value)}><option value="recorded">Recorded</option><option value="closed">Closed</option></select></label>}<label>Event start<input aria-label="Delay event start" type="date" value={draft.start_date} onChange={e => change('start_date', e.target.value)} /></label><label>Event end<input aria-label="Delay event end" type="date" value={draft.end_date} onChange={e => change('end_date', e.target.value)} /></label></div><label>Description<textarea aria-label="Delay event description" required value={draft.description} onChange={e => change('description', e.target.value)} /></label>
    <PlanningDelayActivityPicker activities={list(data.activities)} value={draft.activity_ids} onChange={value => change('activity_ids', value)} />
    <fieldset><legend>Evidence references</legend>{draft.evidence.map((row, index) => <div className="pda-evidence-line" key={index}><label>Reference {index + 1}<input aria-label={`Delay event evidence ${index + 1}`} required value={row.reference} onChange={e => change('evidence', draft.evidence.map((item, at) => at === index ? { ...item, reference: e.target.value } : item))} /></label>{draft.evidence.length > 1 && <button type="button" aria-label={`Remove event evidence ${index + 1}`} onClick={() => change('evidence', draft.evidence.filter((_, at) => at !== index))}>Remove</button>}</div>)}<button type="button" onClick={() => change('evidence', [...draft.evidence, { reference: '' }])}>Add evidence reference</button></fieldset>
    <details><summary>Link existing risk or governance evidence</summary><div className="poc-fields">{[['governance_item_id', 'governance', 'Governance item'], ['risk_id', 'risks', 'Risk record']].map(([field, key, title]) => <label key={key}>{title}<select aria-label={`Delay event ${title.toLowerCase()}`} value={draft[field]} onChange={e => change(field, e.target.value)}><option value="">Not linked</option>{list(data.linked_items?.[key]).map(row => <option key={row.id} value={row.id}>{row.title || row.name || `${title} ${row.id}`} · {label(row.status)}</option>)}</select></label>)}</div><p>Linked records are supporting evidence. They do not approve this impact analysis.</p></details>
    {event && <label>Change reason<textarea aria-label="Delay event change reason" required value={draft.reason} onChange={e => change('reason', e.target.value)} /></label>}</fieldset><div className="poc-actions"><button type="submit" className="poc-primary" disabled={busy || !draft.title.trim() || !draft.description.trim() || !draft.activity_ids.length || draft.evidence.some(row => !row.reference.trim()) || Boolean(event && !draft.reason.trim())}>{event ? 'Save event revision' : 'Record event'}</button><button type="button" disabled={busy} onClick={onClose}>Cancel event</button></div></form>
}
PlanningDelayEventForm.propTypes = { data: PropTypes.object.isRequired, event: PropTypes.object, busy: PropTypes.bool, onCommand: PropTypes.func.isRequired, onClose: PropTypes.func.isRequired }
