import { useEffect, useState } from 'react'
import PropTypes from 'prop-types'
import PlanningDelayChanges, { serializeDelayChanges, validDelayChanges } from './PlanningDelayChanges'
import { controlsList as list, controlsNumber as numeric } from './planningControlsPresentation'

const recommendationFields = [['contract_clause_reference', 'Contract clause reference'], ['notice_reference', 'Notice reference'], ['causation_assessment', 'Causation assessment'], ['concurrency_assessment', 'Concurrency assessment'], ['mitigation_assessment', 'Mitigation assessment'], ['basis', 'Recommendation basis']]
export default function PlanningDelayCaseEditor({ data, busy, readOnly, onCommand, onDirty }) {
  const current = data.case
  const [draft, setDraft] = useState(() => ({ event_ids: [...list(current.event_ids)], changes: structuredClone(list(current.changes)), scenarios: structuredClone(list(current.scenarios)), recommendation: { selected_scenario_id: null, requested_extension_calendar_days: null, contract_clause_reference: '', notice_reference: '', causation_assessment: '', concurrency_assessment: '', mitigation_assessment: '', basis: '', ...current.recommendation } }))
  const [dirty, setDirty] = useState(false)
  useEffect(() => { onDirty(dirty) }, [dirty, onDirty])
  useEffect(() => () => onDirty(false), [onDirty])
  const set = (field, value) => { setDraft(previous => ({ ...previous, [field]: value })); setDirty(true) }
  const events = list(data.events).filter(row => draft.event_ids.some(id => String(id) === String(row.id)))
  const editable = !readOnly && current.permissions?.can_edit === true && !busy
  const extensionRequested = numeric(draft.recommendation.requested_extension_calendar_days) > 0
  const valid = draft.event_ids.length > 0 && validDelayChanges(draft.changes) && draft.scenarios.every(row => row.name.trim() && row.changes.length > 0 && validDelayChanges(row.changes)) && (!extensionRequested || recommendationFields.every(([key]) => draft.recommendation[key]?.trim()))
  const save = async e => {
    e.preventDefault()
    const result = await onCommand('save_case', { case_id: current.id, revision: current.revision, event_ids: draft.event_ids, changes: serializeDelayChanges(draft.changes), scenarios: draft.scenarios.map(row => ({ id: row.id, name: row.name.trim(), changes: serializeDelayChanges(row.changes) })), recommendation: { ...draft.recommendation, requested_extension_calendar_days: numeric(draft.recommendation.requested_extension_calendar_days) } }, 'Impact and recovery inputs saved. Calculate the case to review their combined effect.')
    if (result) setDirty(false)
  }
  const changeScenario = (id, field, value) => set('scenarios', draft.scenarios.map(row => row.id === id ? { ...row, [field]: value } : row))
  return <form aria-label="Delay case inputs" className="poc-section" onSubmit={save}><header><div><h3>{current.name}</h3><p>Reference report {current.reference_report_id} · Revision {current.revision}. Actual dates and the approved baseline are preserved.</p></div><span className="pda-badge is-proposed">Proposed scenario inputs</span></header>
    {dirty && <p className="poc-message is-warning">Unsaved case changes. Save or discard them before calculating or reviewing a decision.</p>}
    <fieldset disabled={!editable}><fieldset className="pda-event-choices"><legend>Events included in this case</legend>{list(data.events).map(row => <label className="poc-check" key={row.id}><input type="checkbox" checked={draft.event_ids.some(id => String(id) === String(row.id))} onChange={e => set('event_ids', e.target.checked ? [...draft.event_ids, row.id] : draft.event_ids.filter(id => String(id) !== String(row.id)))} />{row.title} · Revision {row.revision}</label>)}{!data.events?.length && <p>Record an event first.</p>}</fieldset>
      <PlanningDelayChanges title="Impact" rows={draft.changes} onChange={value => set('changes', value)} activities={list(data.activities)} events={events} caseData={current} disabled={!editable} />
      <section aria-label="Recovery alternatives" className="pda-alternatives"><header><div><h4>Recovery alternatives</h4><p>Each alternative is tested against the combined impact case. Recovery is proposed, not achieved progress.</p></div><button type="button" disabled={!editable} onClick={() => set('scenarios', [...draft.scenarios, { id: `recovery-${crypto.randomUUID()}`, name: '', changes: [] }])}>Add recovery alternative</button></header>
      {draft.scenarios.map((scenario, index) => <section className="pda-alternative" key={scenario.id}><label>Alternative name<input aria-label={`Recovery alternative name ${index + 1}`} required value={scenario.name} onChange={e => changeScenario(scenario.id, 'name', e.target.value)} /></label><PlanningDelayChanges title={`Recovery ${index + 1}`} rows={scenario.changes} onChange={value => changeScenario(scenario.id, 'changes', value)} activities={list(data.activities)} events={events} caseData={current} impactChanges={draft.changes} disabled={!editable} /><button type="button" onClick={() => { set('scenarios', draft.scenarios.filter(row => row.id !== scenario.id)); if (draft.recommendation.selected_scenario_id === scenario.id) set('recommendation', { ...draft.recommendation, selected_scenario_id: null }) }}>Remove recovery alternative {index + 1}</button></section>)}{!draft.scenarios.length && <p>No recovery alternatives recorded.</p>}</section>
      <section className="pda-recommendation" aria-label="Proposed recommendation"><h4>Proposed recommendation</h4><p>Technical delay and a requested time extension are separate. Internal review records a recommendation; it does not award contractual entitlement.</p><div className="poc-fields"><label>Preferred recovery alternative<select aria-label="Recommended recovery alternative" value={draft.recommendation.selected_scenario_id || ''} onChange={e => set('recommendation', { ...draft.recommendation, selected_scenario_id: e.target.value || null })}><option value="">Not Specified</option>{draft.scenarios.map(row => <option key={row.id} value={row.id}>{row.name || 'Unnamed alternative'}</option>)}</select></label><label>Requested extension (calendar days)<input aria-label="Requested extension calendar days" type="number" min="0" step="1" placeholder="Not Specified" value={draft.recommendation.requested_extension_calendar_days ?? ''} onChange={e => set('recommendation', { ...draft.recommendation, requested_extension_calendar_days: e.target.value })} /></label></div><div className="poc-fields">{recommendationFields.map(([key, title]) => <label key={key}>{title}<textarea aria-label={title} required={extensionRequested} value={draft.recommendation[key] || ''} onChange={e => set('recommendation', { ...draft.recommendation, [key]: e.target.value })} /></label>)}</div>{extensionRequested && <p>Support this request with the contract clause, notice, causation, concurrency, mitigation and recommendation basis.</p>}</section>
    </fieldset><div className="poc-actions"><button type="submit" className="poc-primary" disabled={!editable || !dirty || !valid}>Save case inputs</button><button type="button" disabled={busy || !dirty} onClick={() => { setDraft({ event_ids: [...list(current.event_ids)], changes: structuredClone(list(current.changes)), scenarios: structuredClone(list(current.scenarios)), recommendation: { ...current.recommendation } }); setDirty(false) }}>Discard case changes</button></div>
  </form>
}
PlanningDelayCaseEditor.propTypes = { data: PropTypes.object.isRequired, busy: PropTypes.bool, readOnly: PropTypes.bool, onCommand: PropTypes.func.isRequired, onDirty: PropTypes.func.isRequired }
