/* eslint-disable react/prop-types */
import React, { useId, useState } from 'react'
import { CalendarCheck, GitBranch, Link2, Plus, ShieldCheck, ShoppingCart } from 'lucide-react'
import * as EPC from '../../../services/epcLifecycle.service'
import { EPCBlockers, EPCEmpty, EPCFacts, EPCModal, EPCNotice, EPCPanel, EPCScroll, EPCStatus, epcDate, epcError, epcMoney, epcControlRole, epcControlRoleLabel } from './EPCLifecycleCommon'

function LinkEditor({ project, row, data, onClose, onSaved }) {
  const formId = useId(), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState(() => ({ wbs_node: String(row?.wbs_node || ''), activity: String(row?.activity || ''), link_type: row?.link_type || '', notes: row?.notes || '' }))
  const [version, setVersion] = useState(String(row?.version || ''))
  const field = (key, value) => setForm(current => ({ ...current, [key]: value }))
  const activities = (data.activities || []).filter(activity => !version || String(activity.version) === version)
  const save = async event => {
    event.preventDefault(); if (busy || !data.can_edit) return
    setBusy(true); setError('')
    try { await EPC.saveLink(project.id, { ...form, ...(row ? { id: row.id } : {}), wbs_node: Number(form.wbs_node), activity: Number(form.activity) }); await onSaved('WBS and schedule activity link saved.'); onClose() } catch (failure) { setError(epcError(failure)); setBusy(false) }
  }
  return <EPCModal title={row ? 'Edit activity link' : 'Link schedule activity'} busy={busy} onClose={onClose} footer={<><button type="button" className="pp-button" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" form={formId} className="pp-button pp-primary" disabled={busy || !data.can_edit}>Save activity link</button></>}><form id={formId} className="epc-form" onSubmit={save}><div className="epc-wide"><EPCNotice error>{error}</EPCNotice></div>
    <label>Project WBS<select required value={form.wbs_node} onChange={event => field('wbs_node', event.target.value)}><option value="">Select WBS</option>{(data.wbs || []).map(item => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></label>
    <label>EPC phase<select required value={form.link_type} onChange={event => field('link_type', event.target.value)}><option value="">Select phase</option>{(data.link_types || []).map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>
    <label>Schedule version<select value={version} onChange={event => { setVersion(event.target.value); field('activity', '') }}><option value="">All available versions</option>{(data.versions || []).map(item => <option key={item.id} value={item.id}>{item.name || `Schedule ${item.schedule}`} · Version {item.version} · {item.status}</option>)}</select></label>
    <label>Schedule activity<select required value={form.activity} onChange={event => field('activity', event.target.value)}><option value="">Select activity</option>{activities.map(item => <option key={item.id} value={item.id}>{item.external_id} — {item.name}</option>)}</select></label>
    <label className="epc-wide">Link notes<textarea maxLength={4000} value={form.notes} onChange={event => field('notes', event.target.value)} /></label><p className="epc-note epc-wide">Controlled activity links identify where accepted work earns progress. External activity links track dependencies without earning controlled progress. Baseline capture validates the selected schedule version.</p>
  </form></EPCModal>
}

function BaselineCapture({ project, data, controlScope, onClose, onSaved }) {
  const formId = useId(), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [name, setName] = useState(''), [date, setDate] = useState(''), [schedule, setSchedule] = useState(''), [budgets, setBudgets] = useState([])
  const save = async event => {
    event.preventDefault(); if (busy || !data.can_capture || !budgets.length) return
    setBusy(true); setError('')
    try { await EPC.captureBaseline(project.id, { name: name.trim(), data_date: date, schedule_baseline: Number(schedule), budget_ids: budgets.map(Number) }); await onSaved('Integrated EPC baseline captured from the approved sources.'); onClose() } catch (failure) { setError(epcError(failure)); setBusy(false) }
  }
  return <EPCModal title="Capture EPC baseline" onClose={onClose} busy={busy} footer={<><button type="button" className="pp-button" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" form={formId} className="pp-button pp-primary" disabled={busy || !data.can_capture || !budgets.length}>Capture baseline</button></>}><p>Capture an immutable reference to the approved schedule, approved budgets for controlled work and their WBS links. External dependencies do not earn project progress or control budget.</p><p className="epc-note">{controlScope.description}</p><EPCBlockers blockers={data.blockers || []} /><form id={formId} className="epc-form" onSubmit={save}><div className="epc-wide"><EPCNotice error>{error}</EPCNotice></div>
    <label>Baseline name<input required maxLength={255} value={name} onChange={event => setName(event.target.value)} /></label><label>Baseline data date<input type="date" required value={date} onChange={event => setDate(event.target.value)} /></label>
    <label className="epc-wide">Approved schedule baseline<select required value={schedule} onChange={event => setSchedule(event.target.value)}><option value="">Select an approved baseline</option>{(data.schedule_baselines || []).map(item => <option key={item.id} value={item.id}>{item.name} · Approved {epcDate(item.approved_at)}</option>)}</select></label>
    <fieldset className="epc-wide"><legend>Approved budget allocations</legend><div className="epc-check-list">{(data.budgets || []).map(item => <label className="epc-check" key={item.id}><input type="checkbox" checked={budgets.includes(String(item.id))} onChange={event => setBudgets(current => event.target.checked ? [...current, String(item.id)] : current.filter(id => id !== String(item.id)))} /><span>{item.code} — {item.name} · {epcMoney(item.amount, item.currency)}</span></label>)}</div>{!data.budgets?.length && <EPCEmpty>No approved budget allocations are available.</EPCEmpty>}</fieldset>
  </form></EPCModal>
}

function RequisitionLink({ project, row, data, onClose, onSaved }) {
  const formId = useId(), [wbs, setWbs] = useState(String(row.wbs_node || '')), [reason, setReason] = useState(''), [reviewed, setReviewed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const save = async event => {
    event.preventDefault(); if (busy || !data.can_edit) return
    setBusy(true); setError('')
    try { await EPC.associateRequisition(project.id, { requisition: row.id, wbs_node: Number(wbs), reason: reason.trim(), review_confirmed: reviewed }); await onSaved('Purchase requisition association saved.'); onClose() } catch (failure) { setError(epcError(failure)); setBusy(false) }
  }
  return <EPCModal title="Associate purchase requisition" busy={busy} onClose={onClose} footer={<><button type="button" className="pp-button" disabled={busy} onClick={onClose}>Cancel</button><button type="submit" form={formId} className="pp-button pp-primary" disabled={busy || !data.can_edit}>Save requisition association</button></>}><EPCFacts rows={[[ 'Requisition', row.pr_number ], ['Title', row.title], ['Reference match', row.match_status || 'Not assessed']]} /><form id={formId} className="epc-form" onSubmit={save}><div className="epc-wide"><EPCNotice error>{error}</EPCNotice></div>
    <label className="epc-wide">Procurement WBS<select required value={wbs} onChange={event => setWbs(event.target.value)}><option value="">Select WBS</option>{(data.wbs || []).map(item => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select></label>
    <label className="epc-wide">Association reason<textarea required minLength={10} maxLength={500} value={reason} onChange={event => setReason(event.target.value)} /></label>
    <label className="epc-check epc-wide"><input type="checkbox" checked={reviewed} onChange={event => setReviewed(event.target.checked)} /><span>I reviewed the requisition reference and confirm this project and WBS assignment.</span></label><p className="epc-note epc-wide">Ambiguous or unmatched references require an authorized commercial review. The server checks authority and rejects conflicting project assignments.</p>
  </form></EPCModal>
}

export default function EPCBaselinePanel({ project, data, links, requisitions, controlScope, onSaved, onOpenSchedule, onSelectView }) {
  const [dialog, setDialog] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const close = () => setDialog(null)
  const remove = async () => {
    if (busy) return
    setBusy(true); setError('')
    try { await EPC.deleteLink(project.id, dialog.row.id); await onSaved('Activity link removed.'); close() } catch (failure) { setError(epcError(failure)) } finally { setBusy(false) }
  }
  return <><div className="epc-section-grid"><div className="epc-stack"><EPCPanel title="WBS and schedule links" icon={GitBranch} actions={<button type="button" className="pp-button" disabled={!links?.can_edit} onClick={() => setDialog({ type: 'link' })}><Plus size={15} />Link activity</button>}><p className="epc-note">{controlScope.description} Link controlled activities for earned progress and external activities for dependency tracking.</p><EPCScroll label="WBS schedule links"><table className="epc-table"><thead><tr><th>WBS</th><th>Activity</th><th>Phase / version</th><th>Responsibility</th><th>Actions</th></tr></thead><tbody>{(links?.results || []).map(row => <tr key={row.id}><td><strong>{row.wbs_code}</strong>{row.wbs_name}</td><td><strong>{row.activity_code}</strong>{row.activity_name}</td><td>{row.link_type}<small>Version {row.version}</small></td><td><EPCStatus value={row.control_role || epcControlRole(controlScope, row.link_type)} label={epcControlRoleLabel(row.control_role || epcControlRole(controlScope, row.link_type))} /></td><td><div className="epc-actions"><button type="button" className="pp-button" disabled={!links.can_edit} onClick={() => setDialog({ type: 'link', row })}>Edit</button><button type="button" className="pp-button" disabled={!links.can_edit} onClick={() => { setError(''); setDialog({ type: 'remove', row }) }}>Remove</button></div></td></tr>)}</tbody></table></EPCScroll>{!links?.results?.length && <EPCEmpty>{links ? 'No WBS/activity links recorded.' : 'Activity links are unavailable. Refresh to retry.'}</EPCEmpty>}</EPCPanel>
    <EPCPanel title="Purchase requisition associations" icon={ShoppingCart}><p className="epc-note">Review exact project references and explicitly associate each requisition with the project WBS.</p><EPCScroll label="Project requisition associations"><table className="epc-table"><thead><tr><th>Requisition</th><th>Reference match</th><th>WBS</th><th>Action</th></tr></thead><tbody>{(requisitions?.results || []).map(row => <tr key={row.id}><td><strong>{row.pr_number}</strong>{row.title}</td><td><EPCStatus value={row.match_status} /></td><td>{row.wbs_node ? (requisitions.wbs || []).find(item => String(item.id) === String(row.wbs_node))?.code || row.wbs_node : 'Not associated'}</td><td><button type="button" className="pp-button" disabled={!requisitions.can_edit} onClick={() => setDialog({ type: 'requisition', row })}>Associate</button></td></tr>)}</tbody></table></EPCScroll>{!requisitions?.results?.length && <EPCEmpty>{requisitions ? 'No matching or associated requisitions are available to your account.' : 'Requisition associations are unavailable. Refresh to retry.'}</EPCEmpty>}</EPCPanel></div>
    <div className="epc-stack"><EPCPanel title="Baseline readiness" icon={ShieldCheck} actions={<button type="button" className="pp-button pp-primary" disabled={!data?.can_capture} onClick={() => setDialog({ type: 'baseline' })}>Capture EPC baseline</button>}><p className="epc-note">Schedule and budget approvals remain in their controlled workflows. This capture binds those approved sources to execution.</p><EPCBlockers blockers={data?.blockers || []} />{data && !data.blockers?.length && <EPCNotice>Choose approved sources to validate and capture the integrated baseline.</EPCNotice>}<div className="epc-actions"><button type="button" className="pp-button" onClick={onOpenSchedule}>Open schedule approvals</button><button type="button" className="pp-button" onClick={() => onSelectView('cost-dashboard')}>Open budget control</button></div></EPCPanel>
    <EPCPanel title="Captured EPC baselines" icon={CalendarCheck}><EPCScroll label="Captured EPC baseline records"><table className="epc-table"><thead><tr><th>Baseline</th><th>Data date</th><th>Budget</th><th>Action</th></tr></thead><tbody>{(data?.results || []).map(row => <tr key={row.id}><td><strong>{row.name}</strong>Revision {row.revision}</td><td>{epcDate(row.data_date)}</td><td>{epcMoney(row.budget_total, row.currency)}</td><td><button type="button" className="pp-button" onClick={() => setDialog({ type: 'details', row })}>View source</button></td></tr>)}</tbody></table></EPCScroll>{!data?.results?.length && <EPCEmpty>{data ? 'No integrated EPC baseline has been captured.' : 'Baseline records are unavailable. Refresh to retry.'}</EPCEmpty>}</EPCPanel></div></div>
    {dialog?.type === 'link' && <LinkEditor project={project} row={dialog.row} data={links} onSaved={onSaved} onClose={close} />}
    {dialog?.type === 'baseline' && <BaselineCapture project={project} data={data} controlScope={controlScope} onSaved={onSaved} onClose={close} />}
    {dialog?.type === 'requisition' && <RequisitionLink project={project} row={dialog.row} data={requisitions} onSaved={onSaved} onClose={close} />}
    {dialog?.type === 'remove' && <EPCModal title="Remove activity link" busy={busy} onClose={close} footer={<><button type="button" className="pp-button" disabled={busy} onClick={close}>Cancel</button><button type="button" className="pp-button pp-primary" disabled={busy} onClick={remove}>Confirm removal</button></>}><EPCNotice error>{error}</EPCNotice><p>Remove the link between <strong>{dialog.row.wbs_code}</strong> and <strong>{dialog.row.activity_code}</strong>? The server checks whether a controlled baseline or execution record depends on it.</p></EPCModal>}
    {dialog?.type === 'details' && <EPCModal title="EPC baseline source" onClose={close} footer={<button type="button" className="pp-button" onClick={close}>Close</button>}><EPCFacts rows={[[ 'Baseline', dialog.row.name], ['Revision', dialog.row.revision], ['Data date', epcDate(dialog.row.data_date)], ['Captured', epcDate(dialog.row.approved_at)], ['Approved budget', epcMoney(dialog.row.budget_total, dialog.row.currency)], ['Checksum', dialog.row.checksum]]} /><h3><Link2 size={15} aria-hidden="true" /> Recorded source manifest</h3><pre className="epc-source-json" tabIndex={0} aria-label="Baseline source manifest">{JSON.stringify(dialog.row.manifest || {}, null, 2)}</pre></EPCModal>}
  </>
}
