/* eslint-disable react/prop-types */
import React from 'react'
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, ChevronRight, ClipboardList, Database, Flag, ShieldCheck, Timer, Wallet, AlertTriangle } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { formatDate, formatDateTime, formatMoney } from '../useProjectPerformance'

const valueLabel = value => value === null || value === undefined ? 'Not available' : Number(value).toFixed(2)
const percentLabel = value => value === null || value === undefined ? 'Not available' : `${Number(value).toLocaleString('en-GB', { maximumFractionDigits: 1 })}%`
const monthLabel = value => new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })

function TextAction({ children, onClick }) {
  return <button type="button" className="pp-text-action" onClick={onClick}>{children}<ArrowRight size={15} /></button>
}

export function PerformancePanel({ title, icon: Icon, action, children, className = '' }) {
  return <section className={`pp-panel ${className}`} aria-label={title}><header className="pp-panel-heading"><h2><Icon size={19} aria-hidden="true" />{title}</h2>{action}</header>{children}</section>
}

export function ManagementActions({ actions, onAction, limit }) {
  return <div className="pp-table-wrap"><table className="pp-table pp-actions-table" data-table-typography="preserve"><colgroup>{[5, 12, 36, 17, 15, 15].map((width, index) => <col key={index} style={{ width: `${width}%` }} />)}</colgroup><thead><tr><th scope="col">#</th><th scope="col">Priority</th><th scope="col">Action</th><th scope="col">Owner</th><th scope="col">Due date</th><th scope="col"><span className="sr-only">Open action</span></th></tr></thead><tbody>{actions.slice(0, limit || actions.length).map((item, index) => <tr key={item.id}><td>{index + 1}</td><td><span className={`pp-priority pp-${item.priority}`}>{item.priority?.replace(/^./, letter => letter.toUpperCase())}</span></td><td><strong title={item.title}>{item.title}</strong><small title={item.detail}>{item.detail}</small></td><td>{item.owner || 'Not assigned'}</td><td>{item.dueDate ? formatDate(item.dueDate) : '—'}</td><td><button type="button" className="pp-button" onClick={() => onAction(item.view)}>{item.button || 'Review'}</button></td></tr>)}</tbody></table></div>
}

export function ActivityTable({ events, limit }) {
  return <div className="pp-table-wrap" role="region" aria-label="Project activity records" tabIndex={0}><table className="pp-table pp-activity-table" data-table-typography="preserve"><thead><tr><th scope="col">Time</th><th scope="col">Event</th><th scope="col">Source</th><th scope="col">User</th><th scope="col">Impact</th></tr></thead><tbody>{events.slice(0, limit || events.length).map(event => <tr key={event.id}><td>{formatDateTime(event.event_at)}</td><td>{event.event_type_display || event.event_type}</td><td>{({ purchase_order: 'Procurement', invoice: 'Finance', payment: 'Finance' })[event.source_type] || event.source_type?.replaceAll('_', ' ') || 'Commercial'}</td><td>{event.actor || 'Not recorded'}</td><td>{event.processing_error ? 'Processing requires review' : event.ledger_rebuilt ? 'Cost ledger updated' : 'Commercial record updated'}</td></tr>)}</tbody></table></div>
}

function ScheduleChart({ model }) {
  const points = model.chartPoints || []
  const latest = points.at(-1)
  const hasPlanned = points.some(point => point.planned !== null && point.planned !== undefined)
  const hasActual = points.some(point => point.actual !== null && point.actual !== undefined)
  return <div className="pp-schedule-body"><div className="pp-chart">
    <div className="pp-chart-legend"><span><i className="pp-planned-line" />Recorded planned progress</span><span><i className="pp-actual-line" />Actual progress</span></div>
    {points.length && (hasPlanned || hasActual) ? <div className="pp-chart-canvas" role="img" aria-label={`Schedule progress history: ${points.length} recorded periods. Latest planned ${percentLabel(latest.planned)}, actual ${percentLabel(latest.actual)}.`}>
      <ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{ top: 8, right: 15, bottom: 4, left: -13 }}><CartesianGrid stroke="#e7eef8" /><XAxis dataKey="date" tickFormatter={monthLabel} tick={{ fill: '#506a91', fontSize: 10 }} axisLine={{ stroke: '#b9cce5' }} tickLine={{ stroke: '#b9cce5' }} minTickGap={20} /><YAxis domain={[0, 100]} ticks={[0, 20, 40, 60, 80, 100]} tickFormatter={value => `${value}%`} tick={{ fill: '#506a91', fontSize: 10 }} axisLine={{ stroke: '#b9cce5' }} tickLine={{ stroke: '#b9cce5' }} /><Tooltip labelFormatter={formatDate} formatter={(value, name) => [percentLabel(value), name]} contentStyle={{ fontSize: 12, borderRadius: 6, borderColor: '#dbe5f1' }} />{latest && <ReferenceLine x={latest.date} stroke="#9badc7" strokeDasharray="4 4" />}<Line name="Planned progress" dataKey="planned" type="linear" stroke="#1555ff" strokeWidth={2} dot={{ r: 3 }} activeDot={{ r: 5 }} connectNulls={false} isAnimationActive={false} /><Line name="Actual progress" dataKey="actual" type="linear" stroke="#dd1245" strokeWidth={2} dot={{ r: 3 }} activeDot={{ r: 5 }} connectNulls={false} isAnimationActive={false} /></LineChart></ResponsiveContainer>
    </div> : <div className="pp-empty pp-chart-canvas"><BarChart3 size={30} /><strong>{model.availability?.snapshots === false ? 'Progress history unavailable' : 'No recorded progress history'}</strong><p>Capture reporting snapshots to compare planned and actual progress over time.</p></div>}
    <p className="pp-chart-note" title={model.chartNote}>{points.length ? "Sealed reporting periods. Lines connect recorded observations." : model.availability?.snapshots === false ? "Reporting history could not be loaded." : "Capture a reporting snapshot to start this chart."}</p>
  </div><dl className="pp-schedule-summary"><div><dt>Variance</dt><dd className={model.variance < 0 ? 'pp-danger' : 'pp-blue'}>{model.variance === null || model.variance === undefined ? 'Not available' : `${model.variance > 0 ? '+' : ''}${Number(model.variance).toLocaleString('en-GB', { maximumFractionDigits: 1 })} pp`}</dd></div><div><dt>SPI</dt><dd className={model.spi !== null && model.spi < 1 ? 'pp-danger' : ''}>{valueLabel(model.spi)}</dd></div><div><dt>{model.baselineApproved ? 'Baseline finish' : 'Working planned finish'}</dt><dd>{formatDate(model.baselineFinish)}</dd></div><div><dt>Working forecast finish</dt><dd>{model.forecastFinish ? formatDate(model.forecastFinish) : 'Pending schedule update'}</dd></div></dl></div>
}

export default function ProjectDashboardTab({ performance, onSelectView, onEdit, onOpenDialog }) {
  const { model, loading, issues, reload } = performance
  const action = view => {
    if (view === 'edit-project') onEdit()
    else if (['data-quality', 'actions', 'activity', 'reporting-source'].includes(view)) onOpenDialog(view)
    else onSelectView(view || 'project-dashboard')
  }
  if (loading || !model) return <div className="pp-loading" role="status"><span>Loading project performance…</span>{[84, 277, 158].map(height => <div key={height} style={{ height }} />)}</div>
  const milestoneRows = model.milestones || []
  const forecastDetail = model.milestones === null ? 'Milestones unavailable' : !milestoneRows.length ? 'Milestones incomplete' : model.forecastFinish ? 'Current working forecast' : 'Schedule update required'
  const cards = [
    { label: 'Overall health', value: model.health.label, detail: `${model.actions.length} items need review`, icon: AlertTriangle, tone: model.health.tone, view: 'actions' },
    { label: 'Physical progress', value: percentLabel(model.progress), detail: `${model.workingFallback ? 'Working data date' : 'Report date'} ${formatDate(model.dataDate)}`, icon: BarChart3, tone: 'blue', view: 'reporting-source' },
    { label: 'Schedule', value: model.spi === null ? 'Not available' : `SPI ${valueLabel(model.spi)}`, detail: model.spi === null ? 'No sealed performance index' : model.spi < 1 ? 'Behind sealed period plan' : 'On or ahead of sealed plan', icon: CalendarDays, tone: model.spi !== null && model.spi < 1 ? 'warning' : 'blue', view: 'reporting-source' },
    { label: 'Cost', value: model.cpi === null ? 'Not available' : `CPI ${valueLabel(model.cpi)}`, detail: model.legacyCostBasis ? 'Legacy period cost basis' : model.cpi === null ? 'No sealed performance index' : model.cpi < 1 ? 'Sealed cost efficiency below plan' : 'Within sealed period cost plan', icon: Wallet, tone: model.cpi !== null && model.cpi >= 1 ? 'success' : 'warning', view: 'reporting-source' },
    { label: 'Forecast finish', value: model.milestones === null ? 'Unavailable' : !milestoneRows.length ? 'Not reliable' : model.forecastFinish ? formatDate(model.forecastFinish) : 'Not available', detail: forecastDetail, icon: Flag, tone: !model.forecastFinish || !milestoneRows.length ? 'danger' : 'blue', view: 'milestones' },
  ]
  const completed = milestoneRows.filter(item => item.is_completed).length
  return <div className="pp-dashboard">
    {issues.length > 0 && <section className="pp-notice pp-error" role="alert"><AlertTriangle size={20} /><div><strong>Some project data is unavailable</strong><ul>{issues.map(issue => <li key={typeof issue === 'string' ? issue : issue.label}>{typeof issue === 'string' ? issue : issue.message}</li>)}</ul></div><button type="button" className="pp-button" onClick={reload}>Retry data</button></section>}
    <section className="pp-reporting-source" aria-label="Reporting source"><div><strong>{model.progressSource}</strong><span>{formatDate(model.dataDate, 'Data date not recorded')}{model.reportingVersion !== null ? ` · Version ${model.reportingVersion}` : ''}</span><small>Ledger totals and registers show current records.</small>{model.legacyCostBasis && <small className="pp-danger">Legacy cost basis: CPI/EAC unavailable</small>}</div><button type="button" className="pp-text-action" onClick={() => action('reporting-source')}>View reporting source<ArrowRight size={14} /></button></section>
    <section className="pp-kpis" aria-label="Performance indicators">{cards.map(({ label, value, detail, icon: Icon, tone, view }) => <button type="button" key={label} className={`pp-kpi pp-${tone}`} onClick={() => action(view)}><Icon size={29} aria-hidden="true" /><span className="pp-kpi-copy"><span>{label}</span><strong>{value}</strong><small>{detail}</small></span><ChevronRight size={19} /></button>)}</section>
    <div className="pp-main-grid">
      <PerformancePanel title="Schedule performance" icon={Timer} className="pp-schedule" action={<TextAction onClick={() => action('plan-baseline')}>Open schedule</TextAction>}><ScheduleChart model={model} /></PerformancePanel>
      <PerformancePanel title="Management actions" icon={Flag} className="pp-attention" action={<div className="pp-panel-actions"><span>{model.actions.length} actions to review</span><TextAction onClick={() => action('actions')}>View all</TextAction></div>}>{model.actions.length ? <ManagementActions actions={model.actions} onAction={action} limit={4} /> : <div className="pp-empty"><CheckCircle2 size={28} /><p>No management actions identified from the available data.</p></div>}</PerformancePanel>
    </div>
    <div className="pp-detail-grid">
      <PerformancePanel title="Cost & forecast" icon={Wallet} className="pp-cost" action={<TextAction onClick={() => action('commercial-dashboard')}>Open cost control</TextAction>}>
        {model.costWarning && <div className="pp-cost-warning"><AlertTriangle size={19} /><span>{model.costWarning}</span></div>}
        <dl className="pp-cost-facts">{[['Contract value', model.contract], ['Control budget', model.budget], ['Actual cost', model.actual], ['Commitments', model.committed], ['Estimate at completion', model.eac], ['Remaining budget', model.remaining]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{formatMoney(value, label === 'Contract value' ? model.contractCurrency || model.currency : label === 'Estimate at completion' ? model.reportingCurrency : model.currency)}{label === 'Control budget' && model.costWarning && <small>Review required</small>}{label === 'Estimate at completion' && <small>Sealed {formatDate(model.forecastDataDate, 'period unavailable')}</small>}</dd></div>)}</dl>
      </PerformancePanel>
      <PerformancePanel title="Milestone readiness" icon={ClipboardList} className="pp-milestones"><div className="pp-readiness-body"><Flag size={28} /><div><h3>{model.milestones === null ? 'Milestones unavailable' : milestoneRows.length ? `${completed} of ${milestoneRows.length} complete` : 'No milestones recorded'}</h3><p>{model.milestones === null ? 'Retry the project data request to review milestones.' : milestoneRows.length ? 'Review upcoming dates and outstanding project milestones.' : 'Add contractual and internal milestones to improve forecast readiness.'}</p></div></div><div className="pp-readiness-footer"><button type="button" className="pp-button" onClick={() => action('milestones')}>{milestoneRows.length ? 'Review milestones' : 'Add milestones'}</button></div></PerformancePanel>
      <PerformancePanel title="Risks & changes" icon={ShieldCheck} className="pp-risks"><div className="pp-readiness-body"><ShieldCheck size={28} /><div><h3>{model.riskAvailable ? `${model.risk.counts.openRisks} open risk${model.risk.counts.openRisks === 1 ? '' : 's'}` : model.risk.availability.notConfigured ? 'Risk register not connected' : 'Risk register unavailable'}</h3><p>{model.riskAvailable ? `${model.risk.counts.highRisks} high or critical · ${model.risk.counts.openIssues} open issues. ${model.risk.scopeLabel}.` : model.risk.availability.notConfigured ? 'Connect a planning workspace and schedule to manage the project register.' : 'Refresh project data to retry the current linked register.'}</p></div></div><div className="pp-readiness-footer"><div><span>Pending changes</span><strong>{model.risk.countsComplete ? model.risk.counts.pendingChanges : 'Unavailable'}</strong></div><button type="button" className="pp-button" onClick={() => action('risk')}>Review register</button></div></PerformancePanel>
    </div>
    <PerformancePanel title="Recent project activity" icon={CalendarDays} className="pp-activity" action={<TextAction onClick={() => action('activity')}>View activity</TextAction>}>{model.recentEvents?.length ? <ActivityTable events={model.recentEvents} limit={3} /> : <div className="pp-empty"><p>{model.recentEvents === null ? 'Commercial activity is unavailable.' : 'No audited commercial activity has been recorded.'}</p></div>}</PerformancePanel>
    <section className="pp-confidence" aria-label="Data confidence"><div className="pp-confidence-title"><Database size={25} /><h2>Data confidence</h2></div><div className="pp-confidence-items">{model.confidence.map(item => <button type="button" key={item.label} onClick={() => action(item.view)}><span className={`pp-${item.tone}`}>{item.tone === 'success' ? <CheckCircle2 size={20} /> : <AlertTriangle size={20} />}</span><span><span>{item.label}</span><strong className={`pp-${item.tone}`}>{item.status}</strong></span></button>)}</div><div className="pp-confidence-score" title="The percentage of required data checks that are ready; it is not a forecast probability."><span>Data completeness</span><strong>{model.readinessScore}% {model.readinessScore < 80 ? 'Limited' : 'Available'}</strong><div role="progressbar" aria-label="Project data completeness" aria-valuemin={0} aria-valuemax={100} aria-valuenow={model.readinessScore}><span style={{ width: `${model.readinessScore}%` }} /></div></div><button type="button" className="pp-button" onClick={() => action('data-quality')}>Review data quality</button></section>
  </div>
}
