/* eslint-disable react/prop-types */
import React, { useMemo, useState } from 'react'
import { AlertCircle, AlertTriangle, ArrowRight, BarChart3, CheckCircle2, ChevronRight, Coins, FileText, Info, Landmark, Link2, ListChecks, MessageSquare, Plus, Search, ShieldCheck, SlidersHorizontal, TrendingUp } from 'lucide-react'
import { RiskDialog, RiskRecordForm, RiskUpdateForm, RISK_STATUSES, recordLabel, titleCase } from '../components/RiskChangeDialogs'

const date = value => value && !Number.isNaN(Date.parse(value)) ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' }) : 'Not recorded'
const amount = (value, currency, compact = false) => value == null ? 'Not assessed' : `${currency || 'Currency unknown'} ${Number(value).toLocaleString('en-GB', { maximumFractionDigits: compact ? 1 : 2, ...(compact ? { notation: 'compact' } : {}) })}`
const days = value => value == null ? 'Not assessed' : `${Number(value) > 0 ? '+' : ''}${Number(value)} days`
const scoreBand = score => score == null ? 'neutral' : score >= 16 ? 'critical' : score >= 10 ? 'high' : score >= 5 ? 'medium' : 'low'
const scalarScore = score => typeof score === 'number' ? score : score?.score ?? null
const riskScore = (row, mode = 'inherent') => scalarScore(mode === 'residual' ? row.residualScore : row.riskScore)
const cellValue = value => { const text = String(value ?? ''); return `"${(/^[=+@\-\t\r]/.test(text) ? `'${text}` : text).replaceAll('"', '""')}"` }

export function downloadRiskRegisterCsv(model, project) {
  const headings = ['Project', 'Reference', 'Type', 'Title', 'Source', 'Status', 'Priority', 'Owner', 'Category', 'Due date', 'Inherent probability', 'Inherent impact', 'Inherent score', 'Residual probability', 'Residual impact', 'Residual score', 'Inherent cost exposure', 'Residual cost exposure', 'Exposure currency', 'Change cost impact', 'Cost currency', 'Schedule impact days', 'Linked activity', 'Response', 'Resolution', 'Description']
  const records = (model?.rows || []).map(row => [project?.code || project?.id, row.code, row.typeLabel, row.title, row.sourceLabel, row.statusLabel, row.priority, row.owner, row.category, row.dueDate, row.assessment?.inherentProbability, row.assessment?.inherentImpact, riskScore(row), row.assessment?.residualProbability, row.assessment?.residualImpact, riskScore(row, 'residual'), row.assessment?.inherentCostExposure, row.assessment?.residualCostExposure, row.assessment?.currency, row.costImpact, row.costCurrency, row.scheduleImpactDays, row.linkedActivity?.code, row.assessment?.responseStrategy, row.resolution, row.description])
  const blob = new Blob(['\uFEFF' + [headings, ...records].map(record => record.map(cellValue).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob), anchor = document.createElement('a')
  anchor.href = url; anchor.download = `risk-change-register-${String(project?.code || project?.id || 'project').replace(/[^a-z0-9_-]/gi, '-')}.csv`
  document.body.appendChild(anchor); anchor.click(); anchor.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}

function Panel({ title, icon: Icon = ShieldCheck, className = '', actions, children }) { return <section className={`rc-panel ${className}`} aria-label={title}><header><h2><Icon aria-hidden="true" />{title}</h2>{actions && <div className="rc-panel-actions">{actions}</div>}</header>{children}</section> }
function TextButton({ children, onClick, arrow = false }) { return <button type="button" className="rc-text-button" onClick={onClick}>{children}{arrow && <ArrowRight aria-hidden="true" />}</button> }
function Status({ label, tone = 'neutral' }) { const Icon = tone === 'success' ? CheckCircle2 : ['danger', 'critical', 'high', 'warning'].includes(tone) ? AlertTriangle : Info; return <span className={`rc-status rc-${tone}`}><Icon aria-hidden="true" />{label}</span> }
function Empty({ children }) { return <div className="rc-empty"><ShieldCheck aria-hidden="true" /><p>{children}</p></div> }
function Table({ name, headings, children, className = '' }) { return <div className="rc-table-wrap" role="region" aria-label={name} tabIndex={0}><table className={`rc-table ${className}`}><thead><tr>{headings.map((label, index) => <th scope="col" key={`${label}-${index}`}>{label}</th>)}</tr></thead><tbody>{children}</tbody></table></div> }
function Field({ label, value, onChange, options }) { return <label className="rc-toolbar-field">{label}<select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option value={option.id} key={option.id}>{option.label}</option>)}</select></label> }
function Score({ row, mode = 'inherent' }) { const value = riskScore(row, mode); return value == null ? <span>Not assessed</span> : <span className={`rc-score rc-${scoreBand(value)}`} title="Probability × impact, using the recorded 1–5 ratings">{value} <small>/ 25</small></span> }

function Exposure({ risks, mode, onMode, currency, onCurrency, onSelect, onRegister }) {
  const openRisks = risks.filter(row => row.isOpen)
  const currencies = [...new Set(openRisks.map(row => row.assessment?.currency).filter(Boolean))].sort()
  const activeCurrency = currencies.includes(currency) ? currency : currencies[0] || ''
  const moneyKey = mode === 'residual' ? 'residualCostExposure' : 'inherentCostExposure'
  const rated = openRisks.filter(row => row.assessment?.[`${mode}Probability`] != null && row.assessment?.[`${mode}Impact`] != null)
  const categories = new Map()
  for (const row of openRisks) {
    const value = row.assessment?.[moneyKey]
    if (value == null || row.assessment?.currency !== activeCurrency) continue
    const key = row.category || 'Uncategorized'
    categories.set(key, (categories.get(key) || 0) + Number(value))
  }
  const bars = [...categories].sort((a, b) => b[1] - a[1]), maximum = Math.max(1, ...bars.map(([, value]) => value))
  const slots = new Map()
  return <Panel title="Risk exposure" icon={BarChart3} className="rc-exposure-panel" actions={<TextButton onClick={onRegister} arrow>Open risk register</TextButton>}><div className="rc-exposure-body"><div className="rc-heatmap-wrap"><div className="rc-heatmap-layout"><span className="rc-heatmap-y-label">Probability (1–5)</span><div className="rc-probability-labels">{[5, 4, 3, 2, 1].map(value => <span key={value}>{value}</span>)}</div><div className="rc-heatmap-grid" aria-label={`${titleCase(mode)} risk matrix`}>
    {[5, 4, 3, 2, 1].flatMap(probability => [1, 2, 3, 4, 5].map(impact => <span key={`${probability}-${impact}`} className={`rc-heatmap-cell rc-${scoreBand(probability * impact)}`} aria-hidden="true" />))}
    {rated.map(row => { const p = Number(row.assessment[`${mode}Probability`]), i = Number(row.assessment[`${mode}Impact`]), key = `${p}-${i}`, slot = slots.get(key) || 0; slots.set(key, slot + 1); return <button type="button" className={`rc-risk-point rc-${scoreBand(p * i)}`} key={row.id} style={{ left: `${(i - .5) * 20}%`, top: `${(5.5 - p) * 20}%`, marginTop: `${slot % 3 * 5 - 3}px`, marginLeft: `${Math.floor(slot / 3) % 3 * 5}px` }} aria-label={`Select ${row.code} ${row.title}: ${titleCase(mode)} probability ${p}, impact ${i}`} title={`${row.code}: ${row.title} · score ${p * i}`} onClick={() => onSelect(row.id)}><i aria-hidden="true" /><span className={i > 3 ? 'rc-label-left' : ''}>{row.code}</span></button> })}
  </div><div className="rc-impact-labels">{[1, 2, 3, 4, 5].map(value => <span key={value}>{value}</span>)}</div><span className="rc-heatmap-x-label">Impact (1–5)</span></div><p className="rc-matrix-note">{rated.length} assessed · {openRisks.length - rated.length} not assessed</p></div>
    <div className="rc-category-bars"><div className="rc-segmented">{['Inherent', 'Residual'].map(value => <button type="button" key={value} aria-pressed={mode === value.toLowerCase()} onClick={() => onMode(value.toLowerCase())}>{value}</button>)}</div><h3>Exposure by category ({mode})</h3>{currencies.length > 1 && <label className="rc-currency-selector">Currency<select aria-label="Exposure currency" value={activeCurrency} onChange={event => onCurrency(event.target.value)}>{currencies.map(value => <option key={value}>{value}</option>)}</select></label>}
    {bars.length ? bars.map(([category, value]) => <div className="rc-category-row" key={category}><span title={category}>{category}</span><span className="rc-category-track"><span className="rc-category-fill" style={{ width: `${value / maximum * 100}%` }} /></span><strong>{amount(value, activeCurrency, true)}</strong></div>) : <p className="rc-note">No {mode} cost exposure has been assessed for these risks.</p>}<p className="rc-note">Recorded estimates; currencies are kept separate. Unassessed risks are excluded.</p></div></div></Panel>
}

function RiskRegister({ rows, mode, onMode, counts, selectedId, onSelect, loading, unavailable }) {
  return <Panel title="Risk & issue register" icon={ListChecks} className="rc-register-panel" actions={<div className="rc-segmented">{[['risk', 'Risks'], ['issue', 'Issues']].map(([type, label]) => <button type="button" key={type} aria-pressed={mode === type} onClick={() => onMode(type)}>{label} ({counts[type]})</button>)}</div>}>
    {rows.length ? <Table name="Risk and issue records" headings={['ID', 'Risk / Issue', 'Category', mode === 'risk' ? 'Inherent' : 'Priority', 'Response', 'Residual', 'Owner', 'Due date', 'Status', 'Action']} className="rc-register-table">{rows.map(row => <tr key={row.id} className={row.id === selectedId ? 'is-selected' : ''}><td>{row.code}</td><td><button type="button" className="rc-row-link" onClick={() => onSelect(row.id)}>{row.title}</button></td><td>{row.category || 'Uncategorized'}</td><td>{mode === 'risk' ? <Score row={row} /> : <Status label={titleCase(row.priority)} tone={row.priority} />}</td><td>{row.assessment?.responseStrategy && row.assessment.responseStrategy !== 'unset' ? titleCase(row.assessment.responseStrategy) : 'Not recorded'}</td><td>{mode === 'risk' ? <Score row={row} mode="residual" /> : '—'}</td><td>{row.owner || 'Unassigned'}</td><td>{date(row.dueDate)}</td><td><Status label={row.isOverdue ? `${row.statusLabel} · overdue` : row.statusLabel} tone={row.isOverdue ? 'danger' : row.tone} /></td><td><button type="button" className="pp-button" onClick={() => onSelect(row.id)}>Review</button></td></tr>)}</Table> : <Empty>{loading ? 'Loading risk and issue records…' : unavailable ? 'Risk and issue data is unavailable. Refresh to retry.' : 'No risk or issue records match the current filters.'}</Empty>}
  </Panel>
}

function ChangeRegister({ rows, selectedId, onSelect, onCreate, canCreate, unavailable }) {
  return <Panel title="Change control" icon={FileText} className="rc-changes-panel" actions={<button type="button" className="pp-button pp-primary" onClick={onCreate} disabled={!canCreate}><Plus aria-hidden="true" />Add change</button>}>
    {rows.length ? <Table name="Change records" headings={['ID', 'Change', 'Type', 'Recorded status', 'Cost impact', 'Schedule impact', 'Owner', 'Next action', 'Action']} className="rc-changes-table">{rows.map(row => <tr key={row.id} className={selectedId === row.id ? 'is-selected' : ''}><td>{row.code}</td><td><button type="button" className="rc-row-link" onClick={() => onSelect(row.id)}>{row.title}</button></td><td>{row.source === 'document' ? 'Document finding' : 'Change request'}</td><td><Status label={row.statusLabel} tone={row.tone} /></td><td>{amount(row.costImpact, row.costCurrency, true)}</td><td className={row.scheduleImpactDays > 0 ? 'rc-danger' : ''}>{days(row.scheduleImpactDays)}</td><td>{row.owner || 'Unassigned'}</td><td>{row.source === 'document' ? 'Review document' : row.isOpen ? 'Review record' : 'No open action'}</td><td><button type="button" className="pp-button" onClick={() => onSelect(row.id)}>Open</button></td></tr>)}</Table> : <Empty>{unavailable ? 'Change data is unavailable. Refresh to retry.' : 'No change records match the current filters.'}</Empty>}
  </Panel>
}

function ManagementActions({ rows, onEdit, onAll, all = false }) {
  const content = rows.length ? <Table name="Risk management action records" headings={['Priority', 'Action', 'Owner', 'Due date', 'Open record']} className="rc-actions-table">{(all ? rows : rows.slice(0, 4)).map(row => <tr key={row.id}><td><Status label={titleCase(row.priority)} tone={row.priority} /></td><td>{row.title}</td><td>{row.owner || 'Unassigned'}</td><td className={row.isOverdue ? 'rc-danger' : ''}>{date(row.dueDate)}</td><td><button type="button" className="pp-button" onClick={() => onEdit(row)}>{row.canEdit ? 'Review' : 'View'}</button></td></tr>)}</Table> : <Empty>No open management actions match the current filters.</Empty>
  return all ? content : <Panel title="Management actions" icon={ListChecks} className="rc-actions-panel" actions={<><span>{rows.length} open actions</span><TextButton onClick={onAll} arrow>View all</TextButton></>}>{content}</Panel>
}

function Assessment({ row, mode }) { const assessment = row.assessment || {}; return <><h4>{titleCase(mode)} assessment</h4><dl className="rc-assessment-facts"><div><dt>Probability</dt><dd>{assessment[`${mode}Probability`] ?? 'Not assessed'}</dd></div><div><dt>Impact</dt><dd>{assessment[`${mode}Impact`] ?? 'Not assessed'}</dd></div><div><dt>Score</dt><dd><Score row={row} mode={mode} /></dd></div></dl></> }
function RiskDetails({ row, onEdit, onUpdate, onResponse, onHistory, onSchedule }) {
  const title = row?.type === 'issue' ? 'Issue details' : 'Risk details'
  return <Panel title={title} icon={Landmark} className="rc-details-panel" actions={<TextButton onClick={onHistory} arrow>Activity history</TextButton>}>
    {!row ? <Empty>Select a risk or issue to review its assessment and response.</Empty> : <><div className="rc-details-title"><div><h3>{row.title}</h3><small>{row.code} · {row.category || 'Uncategorized'} · <Status label={titleCase(row.priority)} tone={row.priority} /></small></div><div className="rc-panel-actions">{row.canComment && <button type="button" className="pp-button" onClick={onUpdate}>Add update</button>}<button type="button" className="pp-button pp-primary" onClick={onResponse}>Review response</button></div></div>
    <div className="rc-risk-details-grid"><div className="rc-cause-details">{['cause', 'event', 'effect'].map(key => <div key={key}><h4>{titleCase(key)}</h4><p>{row.assessment?.[key] || 'Not recorded'}</p></div>)}<dl><div><dt>Owner</dt><dd>{row.owner || 'Unassigned'}</dd></div><div><dt>Raised</dt><dd>{date(row.createdAt)}</dd></div><div><dt>Due date</dt><dd>{date(row.dueDate)}</dd></div></dl></div><div>{row.type === 'risk' ? <Assessment row={row} mode="inherent" /> : <><h4>Issue status</h4><p><Status label={row.statusLabel} tone={row.tone} /></p><h4>Recorded impact</h4><p>{amount(row.costImpact, row.costCurrency)} · {days(row.scheduleImpactDays)}</p></>}<h4>Response strategy</h4><p>{row.assessment?.responseStrategy && row.assessment.responseStrategy !== 'unset' ? titleCase(row.assessment.responseStrategy) : 'Not recorded'}</p><h4>Response updates</h4>{row.comments?.length ? <ul className="rc-response-list">{row.comments.slice(-2).map(comment => <li key={comment.id}><MessageSquare aria-hidden="true" /><span>{comment.body}</span></li>)}</ul> : <p>No response updates recorded.</p>}{row.canEdit && <TextButton onClick={onEdit}>Edit {recordLabel(row.type)}</TextButton>}</div><div>{row.type === 'risk' && <><Assessment row={row} mode="residual" /><h4>Residual cost exposure</h4><p>{amount(row.assessment?.residualCostExposure, row.assessment?.currency)}</p></>}<h4>Linked items</h4>{row.linkedActivity ? <TextButton onClick={onSchedule}><Link2 aria-hidden="true" />{row.linkedActivity.code} {row.linkedActivity.name}</TextButton> : <p>No activity linked.</p>}<h4>Resolution</h4><p>{row.resolution || 'No resolution recorded.'}</p></div></div></>}
  </Panel>
}

function ChangeApprovals({ row, pipeline, onStage, onOpen, onEdit, onDocuments }) {
  return <Panel title="Change impact & approvals" icon={ShieldCheck} className="rc-approval-panel" actions={<TextButton onClick={onOpen}>Open approval record</TextButton>}>
    <div className="rc-workflow">{pipeline.filter(item => !['closed', 'rejected'].includes(item.status)).map(item => <button type="button" key={item.status} className={`rc-workflow-stage ${row?.source === 'governance' && row.status === item.status ? 'is-current' : ''}`} onClick={() => onStage(item.status)}><span>{item.count}</span>{item.label}<ChevronRight aria-hidden="true" /></button>)}</div>
    {row ? <div className="rc-change-summary"><p><span>Selected change:</span> <strong>{row.code}</strong> {row.title}</p><dl><div><dt>Cost impact</dt><dd>{amount(row.costImpact, row.costCurrency, true)}</dd></div><div><dt>Schedule impact</dt><dd className={row.scheduleImpactDays > 0 ? 'rc-danger' : ''}>{days(row.scheduleImpactDays)}</dd></div><div><dt>Recorded status</dt><dd><Status label={row.statusLabel} tone={row.tone} /></dd></div><div><dt>Owner</dt><dd>{row.owner || 'Unassigned'}</dd></div></dl><div className="rc-change-summary-footer"><span>{row.sourceLabel}</span>{row.canEdit ? <TextButton onClick={onEdit}>Edit change</TextButton> : row.source === 'document' ? <TextButton onClick={onDocuments}>Open project documents</TextButton> : null}</div></div> : <p className="rc-note">Select a change to review its recorded impact and status.</p>}
    <p className="rc-warning-note"><AlertTriangle aria-hidden="true" />Register status does not update approved budgets or baseline dates.</p>
  </Panel>
}

function RecordHistory({ model, row }) {
  const events = row?.source === 'governance' ? (model.auditEvents || []).filter(event => event.entityType === 'GovernanceItem' && String(event.entityId) === String(row.sourceId) || event.entityType === 'GovernanceComment' && (String(event.after?.item_id) === String(row.sourceId) || row.comments?.some(comment => String(comment.id) === String(event.entityId)))) : []
  return <><h3>{row ? `${row.code} · ${row.title}` : 'No record selected'}</h3>{events.length ? <Table name="Recorded risk and change history" headings={['Date', 'Event', 'User']}>{events.map(event => <tr key={event.id}><td>{date(event.date)}</td><td>{titleCase(event.action?.replaceAll('.', ' '))}</td><td>{event.actor || 'Not recorded'}</td></tr>)}</Table> : <p>No record-specific audit events are available in the returned history.</p>}<p className="rc-note">Created {date(row?.createdAt)} · Last updated {date(row?.updatedAt)}</p></>
}

export default function RiskChangeControlTab({ project, riskControl, riskDialog, onRiskDialog, onOpenSchedule, onSelectView }) {
  const { model, loading, issues, reload } = riskControl
  const [mode, setMode] = useState('management'), [registerType, setRegisterType] = useState('risk'), [exposureMode, setExposureMode] = useState('residual'), [exposureCurrency, setExposureCurrency] = useState('')
  const [selectedId, setSelectedId] = useState(null), [selectedChangeId, setSelectedChangeId] = useState(null)
  const [search, setSearch] = useState(''), [type, setType] = useState('all'), [rating, setRating] = useState('all'), [owner, setOwner] = useState('all'), [category, setCategory] = useState('all')
  const [openOnly, setOpenOnly] = useState(false)
  const [mine, setMine] = useState(false), [filters, setFilters] = useState(false), [source, setSource] = useState('all'), [due, setDue] = useState('all'), [feedback, setFeedback] = useState('')
  const filtered = useMemo(() => model.rows.filter(row => (type === 'all' || row.type === type || type === 'change_request' && row.source === 'document') && (rating === 'all' || row.priority === rating || row.status === rating || rating === 'unassessed' && row.type === 'risk' && riskScore(row) == null || rating === 'pending' && (row.type === 'change_request' && ['open', 'in_review'].includes(row.status) || row.source === 'document' && ['detected', 'reviewed'].includes(row.status))) && (owner === 'all' || owner === 'unassigned' && !row.ownerId || String(row.ownerId) === owner) && (category === 'all' || (row.category || 'Uncategorized') === category) && (!openOnly || row.isOpen) && (!mine || model.currentUserId != null && String(row.ownerId) === String(model.currentUserId)) && (source === 'all' || row.source === source) && (due === 'all' || due === 'overdue' && row.isOverdue || due === 'missing' && !row.dueDate) && `${row.code} ${row.title} ${row.owner || ''}`.toLowerCase().includes(search.trim().toLowerCase())), [model, type, rating, owner, category, mine, source, due, search, openOnly])
  const riskRows = filtered.filter(row => row.type === 'risk'), issueRows = filtered.filter(row => row.type === 'issue'), changes = filtered.filter(row => row.type === 'change_request' || row.source === 'document')
  const registerRows = registerType === 'risk' ? riskRows : issueRows
  const selected = registerRows.find(row => row.id === selectedId) || registerRows[0] || null
  const selectedChange = changes.find(row => row.id === selectedChangeId) || changes[0] || null
  const actionRows = filtered.filter(row => row.type === 'action' && row.isOpen)
  const dialogRow = riskDialog?.rowId ? model.rows.find(row => row.id === riskDialog.rowId) : null
  const open = onRiskDialog, close = () => open(null)
  const edit = row => open({ type: row.canEdit ? 'edit' : 'response', rowId: row.id })
  const clear = () => { setSearch(''); setType('all'); setRating('all'); setOwner('all'); setCategory('all'); setMine(false); setSource('all'); setDue('all'); setOpenOnly(false) }
  const goSchedule = () => { close(); onOpenSchedule() }, goDocuments = () => { close(); onSelectView('documents') }
  const openRegister = () => { setMode('registers'); setRegisterType('risk') }
  const selectRisk = id => { setRegisterType('risk'); setSelectedId(id) }
  const saved = result => { close(); clear(); if (result?.id) { const id = `governance:${result.id}`; if (result.item_type === 'change_request') setSelectedChangeId(id); else { setRegisterType(result.item_type === 'issue' ? 'issue' : 'risk'); setSelectedId(id) } } setFeedback('Register updated.'); reload() }
  const exposureSummary = key => { const groups = model.exposureByCurrency.filter(group => group[`${key}Count`] > 0); return groups.length > 1 ? `${groups.length} currencies` : groups.length ? amount(groups[0][key], groups[0].currency, true) : 'Not assessed' }
  const cards = [
    { label: 'Open risks', value: model.counts.openRisks, detail: 'Open register records', icon: ShieldCheck, run: () => { clear(); setType('risk'); setRegisterType('risk'); setOpenOnly(true) } },
    { label: 'Critical / High', value: model.counts.highRisks, detail: 'Recorded priority', icon: AlertTriangle, tone: 'danger', run: () => open({ type: 'priority' }) },
    { label: 'Risk exposure', value: exposureSummary('inherent'), detail: 'Quantified open risks only', icon: Coins, run: () => open({ type: 'exposure' }) },
    { label: 'Residual exposure', value: exposureSummary('residual'), detail: 'After recorded response', icon: TrendingUp, tone: 'success', run: () => open({ type: 'exposure' }) },
    { label: 'Open issues', value: model.counts.openIssues, detail: 'Realized events', icon: AlertCircle, tone: 'danger', run: () => { clear(); setType('issue'); setRegisterType('issue'); setOpenOnly(true) } },
    { label: 'Pending changes', value: model.counts.pendingChanges, detail: 'Awaiting recorded decision', icon: FileText, run: () => { clear(); setType('change_request'); setRating('pending') } },
  ]
  const register = <RiskRegister rows={registerRows} mode={registerType} onMode={setRegisterType} counts={{ risk: riskRows.length, issue: issueRows.length }} selectedId={selected?.id} onSelect={setSelectedId} loading={loading} unavailable={issues.length > 0 && !model.availability?.governance} />
  const changeRegister = <ChangeRegister rows={changes} selectedId={selectedChange?.id} onSelect={setSelectedChangeId} onCreate={() => open({ type: 'create', itemType: 'change_request' })} canCreate={model.canCreate} unavailable={issues.length > 0} />
  const details = <RiskDetails row={selected} onEdit={() => edit(selected)} onUpdate={() => open({ type: 'update', rowId: selected.id })} onResponse={() => open({ type: 'response', rowId: selected.id })} onHistory={() => open({ type: 'history', rowId: selected?.id })} onSchedule={goSchedule} />
  const approvals = <ChangeApprovals row={selectedChange} pipeline={model.changePipeline} onStage={status => { clear(); setType('change_request'); setRating(status) }} onOpen={() => open({ type: 'approval', rowId: selectedChange?.id })} onEdit={() => edit(selectedChange)} onDocuments={goDocuments} />
  return <div className="rc-workspace" aria-busy={loading}>
    <div className="rc-toolbar"><div className="rc-mode-switch">{['Management', 'Registers'].map(value => <button type="button" key={value} aria-pressed={mode === value.toLowerCase()} onClick={() => setMode(value.toLowerCase())}>{value}</button>)}</div><label className="rc-toolbar-search"><Search aria-hidden="true" /><input type="search" aria-label="Search reference, title or owner" placeholder="Search reference, title or owner…" value={search} onChange={event => setSearch(event.target.value)} /></label>
      <Field label="Type" value={type} onChange={value => { setType(value); if (value === 'risk' || value === 'issue') setRegisterType(value) }} options={[{ id: 'all', label: 'All types' }, { id: 'risk', label: 'Risks' }, { id: 'issue', label: 'Issues' }, { id: 'change_request', label: 'Changes' }, { id: 'action', label: 'Actions' }]} />
      <Field label="Rating / Status" value={rating} onChange={setRating} options={[{ id: 'all', label: 'All' }, ...['critical', 'high', 'medium', 'low'].map(value => ({ id: value, label: `${titleCase(value)} priority` })), ...[...new Set([...RISK_STATUSES, ...model.rows.map(row => row.status)])].map(value => ({ id: value, label: titleCase(value) })), { id: 'unassessed', label: 'Unassessed risks' }, { id: 'pending', label: 'Pending changes' }]} />
      <Field label="Owner" value={owner} onChange={setOwner} options={[{ id: 'all', label: 'All owners' }, { id: 'unassigned', label: 'Unassigned' }, ...model.members.map(member => ({ id: String(member.id), label: member.name || member.email }))]} />
      <Field label="Category" value={category} onChange={setCategory} options={[{ id: 'all', label: 'All categories' }, ...[...new Set(model.rows.map(row => row.category || 'Uncategorized'))].sort().map(value => ({ id: value, label: value }))]} /><label className="rc-toolbar-toggle"><input type="checkbox" checked={mine} onChange={event => setMine(event.target.checked)} />My actions</label><button type="button" className="pp-button" aria-expanded={filters} onClick={() => setFilters(!filters)}><SlidersHorizontal aria-hidden="true" />Filters</button><span className="rc-record-count">{filtered.length} records</span></div>
    {filters && <div className="rc-filters"><Field label="Source" value={source} onChange={setSource} options={[{ id: 'all', label: 'All sources' }, { id: 'governance', label: 'Schedule register' }, { id: 'document', label: 'Document findings' }]} /><Field label="Due date" value={due} onChange={setDue} options={[{ id: 'all', label: 'All dates' }, { id: 'overdue', label: 'Overdue' }, { id: 'missing', label: 'Missing due date' }]} /><label><input type="checkbox" checked={openOnly} onChange={event => setOpenOnly(event.target.checked)} />Open records only</label><TextButton onClick={clear}>Clear filters</TextButton><span>{model.scopeLabel}</span></div>}
    {issues.length > 0 && <div className="rc-warning-note" role="alert"><AlertTriangle aria-hidden="true" />{issues.join(' ')}</div>}{feedback && <p role="status" className="rc-note"><CheckCircle2 aria-hidden="true" />{feedback}</p>}
    {!loading && !model.versionId && <div className="rc-connection-note"><Info aria-hidden="true" /><span>Connect a project schedule to create risks, issues and change requests.</span><button type="button" className="pp-button" onClick={goSchedule}>Open schedule</button></div>}
    <section className="rc-kpis" aria-label="Risk and change indicators">{cards.map(({ label, value, detail, icon: Icon, tone = 'blue', run }) => <button type="button" className={`rc-kpi rc-${tone}`} key={label} onClick={run}><Icon aria-hidden="true" /><span className="rc-kpi-copy"><span>{label}</span><strong>{loading ? '…' : !model.countsComplete && typeof value === 'number' && !model.rows.length ? '—' : value}</strong><small>{!model.countsComplete ? 'Partial data · ' : ''}{detail}</small></span><ChevronRight aria-hidden="true" /></button>)}</section>
    {mode === 'management' ? <div className="rc-grid"><div className="rc-left"><Exposure risks={riskRows} mode={exposureMode} onMode={setExposureMode} currency={exposureCurrency} onCurrency={setExposureCurrency} onSelect={selectRisk} onRegister={openRegister} />{register}{changeRegister}</div><div className="rc-right"><ManagementActions rows={actionRows} onEdit={edit} onAll={() => open({ type: 'actions' })} />{details}{approvals}</div></div> : <div className="rc-grid rc-registers-view"><div className="rc-left">{register}{changeRegister}<ManagementActions rows={actionRows} onEdit={edit} onAll={() => open({ type: 'actions' })} /></div><div className="rc-right">{details}{approvals}</div></div>}
    <section className="rc-quality" aria-label="Control status & data quality"><h2>Control status & data quality</h2>{model.quality.map(item => <button type="button" className={`rc-${item.tone || (item.ready ? 'success' : 'warning')}`} key={item.id || item.label} onClick={() => open({ type: 'quality' })}>{item.ready ? <CheckCircle2 aria-hidden="true" /> : <AlertTriangle aria-hidden="true" />}<span><small>{item.label}</small><strong>{item.status}</strong></span></button>)}<button type="button" className="pp-button" onClick={() => open({ type: 'quality' })}>Review control data</button></section>
    {riskDialog?.type === 'create' && model.canCreate && <RiskRecordForm project={project} model={model} itemType={riskDialog.itemType} onClose={close} onSaved={saved} />}
    {riskDialog?.type === 'edit' && dialogRow?.canEdit && <RiskRecordForm project={project} model={model} row={dialogRow} onClose={close} onSaved={saved} />}
    {riskDialog?.type === 'update' && dialogRow?.canComment && <RiskUpdateForm model={model} row={dialogRow} onClose={close} onSaved={saved} />}
    {riskDialog?.type === 'history' && <RiskDialog title="Risk & change activity history" onClose={close}><RecordHistory model={model} row={dialogRow} /></RiskDialog>}
    {riskDialog?.type === 'response' && <RiskDialog title="Review response" onClose={close} footer={<><button type="button" className="pp-button" onClick={close}>Close</button>{dialogRow?.canComment && <button type="button" className="pp-button" onClick={() => open({ type: 'update', rowId: dialogRow.id })}>Add update</button>}{dialogRow?.canEdit && <button type="button" className="pp-button pp-primary" onClick={() => edit(dialogRow)}>Edit {recordLabel(dialogRow.type)}</button>}</>}><h3>{dialogRow?.title || 'No record selected'}</h3><p>{dialogRow?.description || 'No description recorded.'}</p><p><strong>Resolution:</strong> {dialogRow?.resolution || 'Not recorded'}</p>{dialogRow?.comments?.length ? <Table name="Response updates" headings={['Date', 'Update', 'Author']}>{dialogRow.comments.map(comment => <tr key={comment.id}><td>{date(comment.date || comment.created_at)}</td><td>{comment.body}</td><td>{typeof comment.author === 'string' ? comment.author : comment.author?.name || comment.author?.email || 'Not recorded'}</td></tr>)}</Table> : <p>No response updates recorded.</p>}</RiskDialog>}
    {riskDialog?.type === 'approval' && <RiskDialog title="Change approval record" onClose={close} footer={<><button type="button" className="pp-button" onClick={close}>Close</button>{dialogRow?.canEdit && <button type="button" className="pp-button pp-primary" onClick={() => edit(dialogRow)}>Edit change</button>}{dialogRow?.source === 'document' && <button type="button" className="pp-button" onClick={goDocuments}>Open project documents</button>}</>}><p>Recorded status: <strong>{dialogRow?.statusLabel || 'No change selected'}</strong>. Formal client approval is not linked to this record.</p><RecordHistory model={model} row={dialogRow} /><p>Pending changes are estimates. The register does not apply changes to approved budgets or baseline dates.</p></RiskDialog>}
    {riskDialog?.type === 'actions' && <RiskDialog title="Management actions" onClose={close}><ManagementActions rows={actionRows} onEdit={edit} all /></RiskDialog>}
    {riskDialog?.type === 'priority' && <RiskDialog title="Critical and high priority risks" onClose={close}><Table name="Priority risk records" headings={['Reference', 'Risk', 'Priority', 'Action']}>{model.risks.filter(row => row.isOpen && ['critical', 'high'].includes(row.priority)).map(row => <tr key={row.id}><td>{row.code}</td><td>{row.title}</td><td>{titleCase(row.priority)}</td><td><button type="button" className="pp-button" onClick={() => { close(); clear(); selectRisk(row.id) }}>Review</button></td></tr>)}</Table></RiskDialog>}
    {riskDialog?.type === 'exposure' && <RiskDialog title="Risk exposure by currency" onClose={close}><p>Exposure uses explicit assessments of open risks. Unassessed values are excluded; amounts in different currencies are not added together.</p>{model.exposureByCurrency.length ? <Table name="Exposure currency groups" headings={['Currency', 'Inherent exposure', 'Quantified risks', 'Residual exposure', 'Quantified risks']}>{model.exposureByCurrency.map(group => <tr key={group.currency}><td>{group.currency}</td><td>{group.inherentCount ? amount(group.inherent, group.currency) : 'Not assessed'}</td><td>{group.inherentCount}</td><td>{group.residualCount ? amount(group.residual, group.currency) : 'Not assessed'}</td><td>{group.residualCount}</td></tr>)}</Table> : <p>No risk cost exposure has been assessed.</p>}</RiskDialog>}
    {riskDialog?.type === 'quality' && <RiskDialog title="Control data quality" onClose={close}><p>{model.scopeLabel}. Data date: {date(model.dataDate)}.</p><Table name="Control data readiness" headings={['Check', 'Status', 'Details']}>{model.quality.map(item => <tr key={item.id || item.label}><td>{item.label}</td><td>{item.status}</td><td>{item.detail}</td></tr>)}</Table><p className="rc-note">Matrix score = probability × impact. Display bands: Low 1–4, Medium 5–9, High 10–15, Critical 16–25. Recorded priority is a separate management assessment.</p><p>Register confidence is not calculated. Review the underlying records and missing assessments.</p></RiskDialog>}
  </div>
}
