import React, { useEffect, useState } from 'react';
import { BadgeCheck, Clock3, Timer, MessageSquare } from 'lucide-react';
import analyticsService from '../../services/analyticsService';
import './AIWorkflowMeasurements.css';

const defaults = { module: 'planning_package', title: '', task_reference: '', evidence_url: '', comparison: '', baseline_minutes: '', ai_minutes: '', review_minutes: '', rework_minutes: '', measurement: 'measured', contribution_type: 'task', hourly_rate: '', value_currency: '', workflow: null };
const fields = [['title', 'Task title'], ['task_reference', 'Unique task / job reference'], ['evidence_url', 'Evidence link (HTTPS)'], ['baseline_minutes', 'Comparable manual baseline (minutes)'], ['ai_minutes', 'AI-assisted work (minutes)'], ['review_minutes', 'Review time (minutes)'], ['rework_minutes', 'Rework time (minutes)']];

export default function AIOutcomes({ initialWorkflow = null }) {
  const [data, setData] = useState(null);
  const [page, setPage] = useState(1);
  const [revision, setRevision] = useState(0);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [form, setForm] = useState(() => initialWorkflow ? { ...defaults, workflow: initialWorkflow.id, module: initialWorkflow.module, task_reference: `${initialWorkflow.source_type}:${initialWorkflow.source_id}`, title: `${initialWorkflow.module} outcome` } : null);
  const [selected, setSelected] = useState(null);
  const [reason, setReason] = useState('');
  const [confirmed, setConfirmed] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); let active = true;
    setData(null); setError('');
    analyticsService.getAIOutcomes(page, { signal: controller.signal }).then(value => { if (active) setData(value); })
      .catch(() => { if (active) setError('Unable to load outcome evidence. Retry.'); });
    return () => { active = false; controller.abort(); };
  }, [page, revision]);
  const save = async decision => {
    setBusy(true); setError('');
    try {
      if (decision) await analyticsService.reviewAIOutcome({ id: selected.id, decision, reason, comparable_quality_confirmed: confirmed });
      else await analyticsService.submitAIOutcome({ ...form, hourly_rate: form.hourly_rate === '' ? null : form.hourly_rate });
      setForm(null); setSelected(null); setReason(''); setConfirmed(false); setRevision(v => v + 1);
    } catch (e) { setError(e?.response?.data ? JSON.stringify(e.response.data) : 'Could not save evidence. Try again.'); }
    finally { setBusy(false); }
  };
  return <div className="ai-outcomes">
    <div className="ad-panel-heading"><div><h2>Productivity evidence</h2><p>Pilots: Planning packages and P&amp;ID analysis. All-time reviewed observations in your administrative scope.</p></div><button onClick={() => { setForm({ ...defaults }); setSelected(null); }} disabled={busy || !data}>Record outcome</button><button disabled={busy} onClick={() => setRevision(v => v + 1)}>Refresh evidence</button></div>
    {error && <div role="alert" className="ad-info">{error}</div>}
    {!data && !error && <p role="status">Loading outcome evidence…</p>}
    {data && <><div className="ad-kpis">{[['Approved observations', data.totals.approved, BadgeCheck, 'green'], ['Awaiting review', data.totals.pending, Clock3, data.totals.pending ? 'amber' : 'slate'], ['Measured hours freed', data.totals.measured_minutes_saved == null ? 'Not measured' : (data.totals.measured_minutes_saved / 60).toFixed(2), Timer, data.totals.measured_minutes_saved == null ? 'slate' : 'green'], ['Self-reported hours freed', data.totals.self_reported_minutes_saved == null ? 'Not reported' : (data.totals.self_reported_minutes_saved / 60).toFixed(2), MessageSquare, 'slate']].map(([label, value, Icon, tone]) => <div className="ad-kpi" data-tone={tone} key={label}><span className="ad-kpi-icon"><Icon /></span><span><span className="ad-kpi-label">{label}</span><strong>{value}</strong></span></div>)}</div>
      <p>Time freed = manual baseline − AI-assisted work − review − rework. Negative savings remain visible. Hours freed are not cash savings; approval does not convert self-reported estimates into measured results.</p>
      {data.estimated_values?.length > 0 && <section className="ad-panel ao-form"><h2>Estimated capacity value</h2>{data.estimated_values.map(v => <p key={`${v.currency}-${v.measurement}`}>{v.currency} {v.estimated_capacity_value} ? {v.measurement.replace('_', '-')} time ? supplied hourly rate</p>)}<p>Estimated capacity value is not realized revenue, cash savings or ROI. Currencies and measurement sources remain separate.</p></section>}<section className="ad-panel"><div className="ad-table-scroll"><table><thead><tr><th>Task</th><th>Module</th><th>Evidence type</th><th>Net minutes</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.results.map(row => <tr key={row.id}><td>{row.title}</td><td>{row.module}</td><td>{row.measurement.replace('_', '-')}</td><td>{row.saved_minutes}</td><td>{row.status}</td><td><button onClick={() => { setSelected(row); setForm(null); setReason(''); setConfirmed(false); }}>{row.can_review ? 'Review evidence' : 'View details'}</button></td></tr>)}{!data.results.length && <tr><td colSpan="6">No outcome evidence recorded yet.</td></tr>}</tbody></table></div><div className="ad-panel-heading"><button disabled={page === 1 || busy} onClick={() => setPage(v => v - 1)}>Previous</button><span>Page {page} · {data.count} observations</span><button disabled={page * 10 >= data.count || busy} onClick={() => setPage(v => v + 1)}>Next</button></div></section>
      {form && <form className="ad-panel ao-form" onSubmit={e => { e.preventDefault(); save(); }}><h2>Record comparable task evidence</h2>{form.workflow && <p>Linked server workflow: {form.workflow}. Task reference and module are fixed to its persisted output.</p>}<label>AI module<select disabled={!!form.workflow} value={form.module} onChange={e => setForm({ ...form, module: e.target.value })}>{data.modules.map(m => <option key={m.code} value={m.code}>{m.name}</option>)}</select></label>{fields.map(([key, label]) => <label key={key}>{label}<input required maxLength={key === 'evidence_url' ? 1000 : 200} readOnly={key === 'task_reference' && !!form.workflow} type={key.endsWith('minutes') ? 'number' : key === 'evidence_url' ? 'url' : 'text'} min={key === 'baseline_minutes' ? 1 : 0} max={525600} step={1} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></label>)}<label>Contribution evidence<select value={form.contribution_type} onChange={e => setForm({ ...form, contribution_type: e.target.value })}><option value="task">Comparable task outcome</option><option value="workflow_integration" disabled={!form.workflow}>Workflow integration (reviewed maturity 4)</option><option value="automation_creator" disabled={!form.workflow}>Automation creator (reviewed maturity 5)</option></select></label><label>Optional hourly rate for estimated capacity value<input type="number" min="0" max="99999999.99" step="0.01" value={form.hourly_rate} onChange={e => setForm({ ...form, hourly_rate: e.target.value })} /></label><label>Rate currency<select value={form.value_currency} onChange={e => setForm({ ...form, value_currency: e.target.value })}><option value="">No value estimate</option>{['USD','AED','EUR','GBP','SEK'].map(c => <option key={c}>{c}</option>)}</select></label><label>Measurement source<select value={form.measurement} onChange={e => setForm({ ...form, measurement: e.target.value })}><option value="measured">Measured task timings</option><option value="self_reported">Self-reported estimate</option></select></label><label>Explain baseline source, comparable scope and accepted output quality<textarea required minLength={20} maxLength={4000} value={form.comparison} onChange={e => setForm({ ...form, comparison: e.target.value })} /></label><div><button type="button" disabled={busy} onClick={() => setForm(null)}>Cancel</button><button disabled={busy}>Submit for independent review</button></div></form>}
      {selected && <section className="ad-panel ao-form"><h2>{selected.title}</h2><p>{selected.task_reference} · Submitted by {selected.submitted_by}</p><p>{selected.comparison}</p><p>Contribution: {selected.contribution_type || 'task'} ? Workflow: {selected.workflow || 'Not linked'}</p><a href={selected.evidence_url} target="_blank" rel="noopener noreferrer">Open supporting evidence</a><p>Manual: {selected.baseline_minutes} min · AI work: {selected.ai_minutes} min · Review: {selected.review_minutes} min · Rework: {selected.rework_minutes} min</p>{selected.review_reason && <p>Review decision: {selected.review_reason}</p>}{selected.can_review && <><label>Review reason<textarea minLength={10} maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} /></label><label><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /> I checked comparable task scope, baseline evidence, accepted output quality and any integration or automation claim.</label><div><button disabled={busy || reason.trim().length < 10} onClick={() => save('rejected')}>Reject evidence</button><button disabled={busy || reason.trim().length < 10 || !confirmed} onClick={() => save('approved')}>Approve evidence</button></div></>}<button disabled={busy} onClick={() => setSelected(null)}>Close details</button></section>}
    </>}
  </div>;
}
